// TileKernels CUDA dump (generated by scripts/dump_cuda_sources.py)
// Source Python: tile_kernels/quant/cast_back_kernel.py
// JIT factory: get_cast_back_kernel
// prim_func: cast_back_kernel
// Compile args: {"args": [7168, {"sf_block": [128, 128], "torch_dtype": "torch.float8_e4m3fn", "use_packed_ue8m0": false, "use_tma_aligned_col_major_sf": false, "with_sf": true}, "bfloat16"], "kwargs": {}}
// Public API: tile_kernels.quant.cast_back
#include <tl_templates/cuda/cuda_fp8.h>
#include <tl_templates/cuda/gemm.h>
#include <tl_templates/cuda/copy.h>
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#include <tl_templates/cuda/debug.h>
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void cast_back_kernel_kernel(bfloat16_t* __restrict__ out, const fp8_e4_t* __restrict__ x, const float* __restrict__ x_sf, int num_tokens, int sf_stride);
extern "C" __global__ void __launch_bounds__(128, 1) cast_back_kernel_kernel(bfloat16_t* __restrict__ out, const fp8_e4_t* __restrict__ x, const float* __restrict__ x_sf, int num_tokens, int sf_stride) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  bfloat16_t out_fragment[64];
  fp8_e4_t x_shared_local_cast[16];
  #pragma unroll
  for (int i = 0; i < 4; ++i) {
    uint4 v_ = tl::load_global_128_conditional((&(x[(((((((int64_t)((int)blockIdx.x)) * (int64_t)917504) + (((int64_t)i) * (int64_t)229376)) + ((((int64_t)((int)threadIdx.x)) >> (int64_t)2) * (int64_t)7168)) + (((int64_t)((int)blockIdx.y)) * (int64_t)64)) + ((((int64_t)((int)threadIdx.x)) & (int64_t)3) * (int64_t)16))])), ((((((int)blockIdx.x) * 128) + (i * 32)) + (((int)threadIdx.x) >> 2)) < num_tokens));
    *(fp8_e4_16_t*)(((fp8_e4_t*)buf_dyn_shmem) + ((i * 2048) + (((int)threadIdx.x) * 16))) = (*(fp8_e4_16_t *)(&(v_)));
  }
  if (((int)threadIdx.x) < 1) {
    float sf = x_sf[((((int64_t)((int)blockIdx.y)) >> (int64_t)1) + (((int64_t)((int)blockIdx.x)) * ((int64_t)sf_stride)))];
    ((float*)buf_dyn_shmem)[2048] = sf;
  }
  __syncthreads();
  #pragma unroll
  for (int i_1 = 0; i_1 < 4; ++i_1) {
    *(fp8_e4_16_t*)(x_shared_local_cast + 0) = *(fp8_e4_16_t*)(((fp8_e4_t*)buf_dyn_shmem) + ((i_1 * 2048) + (((int)threadIdx.x) * 16)));
    for (int vec = 0; vec < 4; ++vec) {
      uint2 __1;
      float4 __2;
        float4 __3;
        fp8_e4_4_t v__1 = *(fp8_e4_4_t*)(x_shared_local_cast + (vec * 4));
        ((float2*)(&__3))[0] = __tl_cvt_fp8x2_to_float2((reinterpret_cast<__nv_fp8x2_storage_t*>(&v__1))[0], __NV_E4M3);
        ((float2*)(&__3))[1] = __tl_cvt_fp8x2_to_float2((reinterpret_cast<__nv_fp8x2_storage_t*>(&v__1))[1], __NV_E4M3);
        float4 v__2 = make_float4(((float*)buf_dyn_shmem)[2048], ((float*)buf_dyn_shmem)[2048], ((float*)buf_dyn_shmem)[2048], ((float*)buf_dyn_shmem)[2048]);
        *(float2*)(&(__2.x)) = tl::mul2(*(float2*)(&(__3.x)), *(float2*)(&(v__2.x)));
        *(float2*)(&(__2.z)) = tl::mul2(*(float2*)(&(__3.z)), *(float2*)(&(v__2.z)));
      (reinterpret_cast<__nv_bfloat162*>(&__1))[0] = __float22bfloat162_rn(((float2*)(&__2))[0]);
      (reinterpret_cast<__nv_bfloat162*>(&__1))[1] = __float22bfloat162_rn(((float2*)(&__2))[1]);
      *(uint2*)(out_fragment + ((i_1 * 16) + (vec * 4))) = __1;
    }
  }
  #pragma unroll
  for (int i_2 = 0; i_2 < 4; ++i_2) {
    ulonglong4 v__3 = *(ulonglong4*)(out_fragment + (i_2 * 16));
    tl::store_global_256_conditional((&(out[(((((((int64_t)((int)blockIdx.x)) * (int64_t)917504) + (((int64_t)i_2) * (int64_t)229376)) + ((((int64_t)((int)threadIdx.x)) >> (int64_t)2) * (int64_t)7168)) + (((int64_t)((int)blockIdx.y)) * (int64_t)64)) + ((((int64_t)((int)threadIdx.x)) & (int64_t)3) * (int64_t)16))])), (*(ulonglong4 *)(&(v__3))), ((((((int)blockIdx.x) * 128) + (i_2 * 32)) + (((int)threadIdx.x) >> 2)) < num_tokens));
  }
}

