// TileKernels CUDA dump (generated by scripts/dump_cuda_sources.py)
// Source Python: tile_kernels/quant/cast_back_e5m6_kernel.py
// JIT factory: get_cast_back_e5m6_kernel
// prim_func: cast_back_e5m6_kernel
// Compile args: {"args": [7168, {"sf_block": [128, 128], "torch_dtype": "torch.uint32", "use_packed_ue8m0": false, "use_tma_aligned_col_major_sf": false, "with_sf": true}, "bfloat16"], "kwargs": {}}
// Public API: tile_kernels.quant.cast_back_e5m6
#include <tl_templates/cuda/gemm.h>
#include <tl_templates/cuda/copy.h>
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#include <tl_templates/cuda/debug.h>
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void cast_back_e5m6_kernel_kernel(bfloat16_t* __restrict__ out, const uint* __restrict__ x, const float* __restrict__ x_sf, int num_tokens, int sf_stride);
extern "C" __global__ void __launch_bounds__(128, 1) cast_back_e5m6_kernel_kernel(bfloat16_t* __restrict__ out, const uint* __restrict__ x, const float* __restrict__ x_sf, int num_tokens, int sf_stride) {
  extern __shared__ __align__(1024) float sf_shared[];
  bfloat16_t out_fragment[64];
  uint in_local[3];
  half_t f16_local[8];
  float out_local[8];
  if (((int)threadIdx.x) < 1) {
    float sf = x_sf[(((((int64_t)((int)blockIdx.x)) >> (int64_t)1) * ((int64_t)sf_stride)) + ((int64_t)((int)blockIdx.y)))];
    sf_shared[0] = sf;
  }
  __syncthreads();
  #pragma unroll
  for (int i = 0; i < 8; ++i) {
    for (int k = 0; k < 3; ++k) {
      in_local[k] = tl::load_global_32_conditional((&(x[((((((((int64_t)((int)blockIdx.x)) * (int64_t)172032) + (((int64_t)i) * (int64_t)21504)) + ((((int64_t)((int)threadIdx.x)) >> (int64_t)4) * (int64_t)2688)) + (((int64_t)((int)blockIdx.y)) * (int64_t)48)) + ((((int64_t)((int)threadIdx.x)) & (int64_t)15) * (int64_t)3)) + ((int64_t)k))])), ((((((int)blockIdx.x) * 64) + (i * 8)) + (((int)threadIdx.x) >> 4)) < num_tokens));
    }
    ushort v_ = (ushort)((in_local[0] >> (uint)16) & (uint)65520);
    f16_local[0] = (*(half_t *)(&(v_)));
    ushort v__1 = (ushort)((in_local[0] >> (uint)4) & (uint)65520);
    f16_local[1] = (*(half_t *)(&(v__1)));
    ushort v__2 = (ushort)(((in_local[0] << (uint)8) | (in_local[1] >> (uint)24)) & (uint)65520);
    f16_local[2] = (*(half_t *)(&(v__2)));
    ushort v__3 = (ushort)((in_local[1] >> (uint)12) & (uint)65520);
    f16_local[3] = (*(half_t *)(&(v__3)));
    ushort v__4 = (ushort)(in_local[1] & (uint)65520);
    f16_local[4] = (*(half_t *)(&(v__4)));
    ushort v__5 = (ushort)(((in_local[1] << (uint)12) | (in_local[2] >> (uint)20)) & (uint)65520);
    f16_local[5] = (*(half_t *)(&(v__5)));
    ushort v__6 = (ushort)((in_local[2] >> (uint)8) & (uint)65520);
    f16_local[6] = (*(half_t *)(&(v__6)));
    ushort v__7 = (ushort)((in_local[2] << (uint)4) & (uint)65520);
    f16_local[7] = (*(half_t *)(&(v__7)));
    for (int i_1 = 0; i_1 < 2; ++i_1) {
      float4 __1;
      uint2 v__8 = *(uint2*)(f16_local + (i_1 * 4));
      ((float2*)(&__1))[0] = __half22float2(((half2*)(&v__8))[0]);
      ((float2*)(&__1))[1] = __half22float2(((half2*)(&v__8))[1]);
      *(float4*)(out_local + (i_1 * 4)) = __1;
    }
    for (int k_1 = 0; k_1 < 2; ++k_1) {
      float4 __2;
        float4 v__9 = *(float4*)(out_local + (k_1 * 4));
        float4 v__10 = make_float4(sf_shared[0], sf_shared[0], sf_shared[0], sf_shared[0]);
        *(float2*)(&(__2.x)) = tl::mul2(*(float2*)(&(v__9.x)), *(float2*)(&(v__10.x)));
        *(float2*)(&(__2.z)) = tl::mul2(*(float2*)(&(v__9.z)), *(float2*)(&(v__10.z)));
      float4 scaled = __2;
      uint2 __3;
      (reinterpret_cast<__nv_bfloat162*>(&__3))[0] = __float22bfloat162_rn(((float2*)(&scaled))[0]);
      (reinterpret_cast<__nv_bfloat162*>(&__3))[1] = __float22bfloat162_rn(((float2*)(&scaled))[1]);
      *(uint2*)(out_fragment + ((i * 8) + (k_1 * 4))) = __3;
    }
  }
  #pragma unroll
  for (int i_2 = 0; i_2 < 8; ++i_2) {
    uint4 v__11 = *(uint4*)(out_fragment + (i_2 * 8));
    tl::store_global_128_conditional((&(out[(((((((int64_t)((int)blockIdx.x)) * (int64_t)458752) + (((int64_t)i_2) * (int64_t)57344)) + ((((int64_t)((int)threadIdx.x)) >> (int64_t)4) * (int64_t)7168)) + (((int64_t)((int)blockIdx.y)) * (int64_t)128)) + ((((int64_t)((int)threadIdx.x)) & (int64_t)15) * (int64_t)8))])), (*(uint4 *)(&(v__11))), ((((((int)blockIdx.x) * 64) + (i_2 * 8)) + (((int)threadIdx.x) >> 4)) < num_tokens));
  }
}

