// TileKernels CUDA dump (generated by scripts/dump_cuda_sources.py)
// Source Python: tile_kernels/quant/per_channel_cast_fused_kernel.py
// JIT factory: get_per_channel_cast_fused_kernel
// prim_func: per_channel_cast_fused_kernel
// Compile args: {"args": [7168, false, {"sf_block": [1, 1], "torch_dtype": "torch.bfloat16", "use_packed_ue8m0": false, "use_tma_aligned_col_major_sf": false, "with_sf": false}, {"custom_clamp_min_value": null, "round_sf": true, "sf_block": [128, 1], "torch_dtype": "torch.float8_e4m3fn", "use_packed_ue8m0": false, "use_tma_aligned_col_major_sf": false}], "kwargs": {}}
// Public API: tile_kernels.quant.per_channel_cast_fused
#include <tl_templates/cuda/cuda_fp8.h>
#include <tl_templates/cuda/gemm.h>
#include <tl_templates/cuda/copy.h>
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#include <tl_templates/cuda/debug.h>
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void per_channel_cast_fused_kernel_kernel(fp8_e4_t* __restrict__ out, float* __restrict__ out_sf, const bfloat16_t* __restrict__ x, int num_tokens, int num_tokens_out);
extern "C" __global__ void __launch_bounds__(256, 1) per_channel_cast_fused_kernel_kernel(fp8_e4_t* __restrict__ out, float* __restrict__ out_sf, const bfloat16_t* __restrict__ x, int num_tokens, int num_tokens_out) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  float amax_local[4];
  bfloat16_t in_local[4];
  float sf = 0x0p+0f/*0.000000e+00*/;
  float sf_1 = 0x0p+0f/*0.000000e+00*/;
  fp8_e4_t out_local[4];
  float broadcast_var = 0x0p+0f/*0.000000e+00*/;
  *(float4*)(amax_local + 0) = make_float4(broadcast_var, broadcast_var, broadcast_var, broadcast_var);
  for (int i = 0; i < 16; ++i) {
    *(uint2*)(in_local + 0) = *(uint2*)(x + (((((((int64_t)((int)blockIdx.x)) * (int64_t)917504) + ((((int64_t)((int)threadIdx.x)) >> (int64_t)5) * (int64_t)114688)) + (((int64_t)i) * (int64_t)7168)) + (((int64_t)((int)blockIdx.y)) * (int64_t)128)) + ((((int64_t)((int)threadIdx.x)) & (int64_t)31) * (int64_t)4)));
    *(uint2*)(((bfloat16_t*)buf_dyn_shmem) + ((((((int)threadIdx.x) >> 5) * 2048) + (i * 128)) + ((((int)threadIdx.x) & 31) * 4))) = *(uint2*)(in_local + 0);
    float4 __1;
      float4 v_ = *(float4*)(amax_local + 0);
      float4 __2;
      uint2 __3;
      uint2 v__1 = *(uint2*)(in_local + 0);
      ((nv_bfloat162*)(&(__3.x)))->x = __habs(((nv_bfloat162*)(&(v__1.x)))->x);
      ((nv_bfloat162*)(&(__3.x)))->y = __habs(((nv_bfloat162*)(&(v__1.x)))->y);
      ((nv_bfloat162*)(&(__3.y)))->x = __habs(((nv_bfloat162*)(&(v__1.y)))->x);
      ((nv_bfloat162*)(&(__3.y)))->y = __habs(((nv_bfloat162*)(&(v__1.y)))->y);
      ((float2*)(&__2))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&__3))[0]);
      ((float2*)(&__2))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&__3))[1]);
      *(float2*)(&(__1.x)) = tl::max2(*(float2*)(&(v_.x)), *(float2*)(&(__2.x)));
      *(float2*)(&(__1.z)) = tl::max2(*(float2*)(&(v_.z)), *(float2*)(&(__2.z)));
    *(float4*)(amax_local + 0) = __1;
  }
  #pragma unroll
  for (int i_1 = 0; i_1 < 4; ++i_1) {
    ((float*)buf_dyn_shmem)[(((i_1 * 256) + ((int)threadIdx.x)) + 8192)] = amax_local[i_1];
  }
  sf = 0x0p+0f/*0.000000e+00*/;
  __syncthreads();
  if (((int)threadIdx.x) < 128) {
    for (int _tmp = 0; _tmp < ((287 - (((int)threadIdx.x) & 31)) >> 5); ++_tmp) {
      sf = max(sf, ((float*)buf_dyn_shmem)[(((((((int)threadIdx.x) >> 5) * 256) + (_tmp * 32)) + (((int)threadIdx.x) & 31)) + 8192)]);
    }
  }
  __syncthreads();
  if (((int)threadIdx.x) < 128) {
    float amax = sf;
    float clamped_amax = max(amax, 0x1.a36e2eb1c432dp-14f/*1.000000e-04*/);
    sf_1 = (clamped_amax / 0x1.cp+8f/*4.480000e+02*/);
    float _reinterpret_tmp = sf_1;
    uint bits = (*(uint *)(&(_reinterpret_tmp)));
    uint exp_sf = ((((bits - (uint)1) >> (uint)23) + (uint)1) - (uint)127);
    uint v__2 = ((uint)127 - exp_sf) << (uint)23;
    float sf_inv = (*(float *)(&(v__2)));
    uint v__3 = ((uint)127 + exp_sf) << (uint)23;
    float _tmp_1 = (*(float *)(&(v__3)));
    sf = _tmp_1;
    out_sf[((((((int64_t)((int)blockIdx.x)) * (int64_t)7168) + (((int64_t)((int)blockIdx.y)) * (int64_t)128)) + ((((int64_t)((int)threadIdx.x)) & (int64_t)31) * (int64_t)4)) + (((int64_t)((int)threadIdx.x)) >> (int64_t)5))] = sf;
    ((float*)buf_dyn_shmem)[(((int)threadIdx.x) + 8192)] = sf_inv;
  }
  __syncthreads();
  for (int i_2 = 0; i_2 < 4; ++i_2) {
    amax_local[i_2] = ((float*)buf_dyn_shmem)[(((i_2 * 32) + (((int)threadIdx.x) & 31)) + 8192)];
  }
  for (int i_3 = 0; i_3 < 16; ++i_3) {
    *(uint2*)(in_local + 0) = *(uint2*)(((bfloat16_t*)buf_dyn_shmem) + ((((((int)threadIdx.x) >> 5) * 2048) + (i_3 * 128)) + ((((int)threadIdx.x) & 31) * 4)));
    fp8_e4_4_t __4;
    float4 __5;
      float4 __6;
      uint2 v__4 = *(uint2*)(in_local + 0);
      ((float2*)(&__6))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__4))[0]);
      ((float2*)(&__6))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__4))[1]);
      float4 v__5 = *(float4*)(amax_local + 0);
      *(float2*)(&(__5.x)) = tl::mul2(*(float2*)(&(__6.x)), *(float2*)(&(v__5.x)));
      *(float2*)(&(__5.z)) = tl::mul2(*(float2*)(&(__6.z)), *(float2*)(&(v__5.z)));
    (reinterpret_cast<__nv_fp8x2_storage_t*>(&__4))[0] = __nv_cvt_float2_to_fp8x2(((float2*)(&__5))[0], __NV_SATFINITE, __NV_E4M3);
    (reinterpret_cast<__nv_fp8x2_storage_t*>(&__4))[1] = __nv_cvt_float2_to_fp8x2(((float2*)(&__5))[1], __NV_SATFINITE, __NV_E4M3);
    *(fp8_e4_4_t*)(out_local + 0) = __4;
    *(fp8_e4_4_t*)(out + (((((((int64_t)((int)blockIdx.x)) * (int64_t)917504) + ((((int64_t)((int)threadIdx.x)) >> (int64_t)5) * (int64_t)114688)) + (((int64_t)i_3) * (int64_t)7168)) + (((int64_t)((int)blockIdx.y)) * (int64_t)128)) + ((((int64_t)((int)threadIdx.x)) & (int64_t)31) * (int64_t)4))) = *(fp8_e4_4_t*)(out_local + 0);
  }
}

