// TileKernels CUDA dump (generated by scripts/dump_cuda_sources.py)
// Source Python: tile_kernels/quant/per_block_cast_kernel.py
// JIT factory: get_per_block_cast_kernel
// prim_func: per_block_cast_kernel
// Variant: e4m3
// Compile args: {"args": [7168, {"sf_block": [1, 1], "torch_dtype": "torch.bfloat16", "use_packed_ue8m0": false, "use_tma_aligned_col_major_sf": false, "with_sf": false}, {"custom_clamp_min_value": null, "round_sf": true, "sf_block": [128, 128], "torch_dtype": "torch.float8_e4m3fn", "use_packed_ue8m0": false, "use_tma_aligned_col_major_sf": false}], "kwargs": {}, "variant": "e4m3"}
// Public API: tile_kernels.quant.per_block_cast
#include <tl_templates/cuda/cuda_fp8.h>
#include <math_constants.h>
#include <tl_templates/cuda/gemm.h>
#include <tl_templates/cuda/copy.h>
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#include <tl_templates/cuda/debug.h>
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void per_block_cast_kernel_kernel(fp8_e4_t* __restrict__ out, float* __restrict__ out_sf, const bfloat16_t* __restrict__ x, int num_tokens, int sf_stride);
extern "C" __global__ void __launch_bounds__(256, 1) per_block_cast_kernel_kernel(fp8_e4_t* __restrict__ out, float* __restrict__ out_sf, const bfloat16_t* __restrict__ x, int num_tokens, int sf_stride) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  bfloat16_t x_fragment[64];
  bfloat16_t amax_reducer[1];
  float amax_fragment[1];
  float sf_fragment[1];
  bfloat16_t amax_reducer_1[1];
  float amax_fragment_1[1];
  float sf = 0x0p+0f/*0.000000e+00*/;
  fp8_e4_t out_local_cast[16];
  float sf_1 = 0x0p+0f/*0.000000e+00*/;
  fp8_e4_t out_local_cast_1[16];
  if (((((int)blockIdx.x) + 1) < ((num_tokens + 127) >> 7)) && (((int)blockIdx.y) < 55)) {
    #pragma unroll
    for (int i = 0; i < 4; ++i) {
      *(ulonglong4*)(x_fragment + (i * 16)) = tl::load_global_256(&(*(ulonglong4*)(x + (((((((int64_t)((int)blockIdx.x)) * (int64_t)917504) + (((int64_t)i) * (int64_t)229376)) + ((((int64_t)((int)threadIdx.x)) >> (int64_t)3) * (int64_t)7168)) + (((int64_t)((int)blockIdx.y)) * (int64_t)128)) + ((((int64_t)((int)threadIdx.x)) & (int64_t)7) * (int64_t)16)))));
    }
    amax_reducer[0] = bfloat16_t(0x0p+0f/*0.000000e+00*/);
    #pragma unroll
    for (int i_1 = 0; i_1 < 64; ++i_1) {
      amax_reducer[0] = cutlass::bfloat16_t(__hmax((amax_reducer[0]).to_nv_bfloat16(), (__habs(x_fragment[i_1])).to_nv_bfloat16()));
    }
    amax_fragment[0] = -CUDART_INF_F;
    amax_fragment[0] = max(amax_fragment[0], ((float)amax_reducer[0]));
    amax_fragment[0] = tl::AllReduce<tl::MaxOp, 256, 1, 0, tl::NamedBarrier<256>>::run(amax_fragment[0], (&(((float*)buf_dyn_shmem)[256])));
    float amax = amax_fragment[0];
    float clamped_amax = max(amax, 0x1.a36e2eb1c432dp-14f/*1.000000e-04*/);
    sf = (clamped_amax / 0x1.cp+8f/*4.480000e+02*/);
    float _reinterpret_tmp = sf;
    uint bits = (*(uint *)(&(_reinterpret_tmp)));
    uint exp_sf = ((((bits - (uint)1) >> (uint)23) + (uint)1) - (uint)127);
    uint v_ = ((uint)127 - exp_sf) << (uint)23;
    float sf_2 = (*(float *)(&(v_)));
    uint v__1 = ((uint)127 + exp_sf) << (uint)23;
    float sf_3 = (*(float *)(&(v__1)));
    out_sf[((((int64_t)((int)blockIdx.x)) * ((int64_t)sf_stride)) + ((int64_t)((int)blockIdx.y)))] = sf_3;
    sf_fragment[0] = sf_2;
    #pragma unroll
    for (int i_2 = 0; i_2 < 4; ++i_2) {
      for (int vec = 0; vec < 4; ++vec) {
        fp8_e4_4_t __1;
        float4 __2;
          float4 __3;
          uint2 v__2 = *(uint2*)(x_fragment + ((i_2 * 16) + (vec * 4)));
          ((float2*)(&__3))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__2))[0]);
          ((float2*)(&__3))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__2))[1]);
          float4 v__3 = make_float4(sf_fragment[0], sf_fragment[0], sf_fragment[0], sf_fragment[0]);
          *(float2*)(&(__2.x)) = tl::mul2(*(float2*)(&(__3.x)), *(float2*)(&(v__3.x)));
          *(float2*)(&(__2.z)) = tl::mul2(*(float2*)(&(__3.z)), *(float2*)(&(v__3.z)));
        (reinterpret_cast<__nv_fp8x2_storage_t*>(&__1))[0] = __nv_cvt_float2_to_fp8x2(((float2*)(&__2))[0], __NV_SATFINITE, __NV_E4M3);
        (reinterpret_cast<__nv_fp8x2_storage_t*>(&__1))[1] = __nv_cvt_float2_to_fp8x2(((float2*)(&__2))[1], __NV_SATFINITE, __NV_E4M3);
        *(fp8_e4_4_t*)(out_local_cast + (vec * 4)) = __1;
      }
      *(fp8_e4_16_t*)(out + (((((((int64_t)((int)blockIdx.x)) * (int64_t)917504) + (((int64_t)i_2) * (int64_t)229376)) + ((((int64_t)((int)threadIdx.x)) >> (int64_t)3) * (int64_t)7168)) + (((int64_t)((int)blockIdx.y)) * (int64_t)128)) + ((((int64_t)((int)threadIdx.x)) & (int64_t)7) * (int64_t)16))) = *(fp8_e4_16_t*)(out_local_cast + 0);
    }
  } else {
    #pragma unroll
    for (int i_3 = 0; i_3 < 4; ++i_3) {
      bfloat16_t broadcast_var = bfloat16_t(0x0p+0f/*0.000000e+00*/);
      ulonglong4 condval;
      if (((((((int)blockIdx.x) * 128) + (i_3 * 32)) + (((int)threadIdx.x) >> 3)) < num_tokens)) {
        condval = tl::load_global_256(&(*(ulonglong4*)(x + (((((((int64_t)((int)blockIdx.x)) * (int64_t)917504) + (((int64_t)i_3) * (int64_t)229376)) + ((((int64_t)((int)threadIdx.x)) >> (int64_t)3) * (int64_t)7168)) + (((int64_t)((int)blockIdx.y)) * (int64_t)128)) + ((((int64_t)((int)threadIdx.x)) & (int64_t)7) * (int64_t)16)))));
      } else {
        condval = make_ulonglong4(tl::pack_bfloat16x4(broadcast_var, broadcast_var, broadcast_var, broadcast_var), tl::pack_bfloat16x4(broadcast_var, broadcast_var, broadcast_var, broadcast_var), tl::pack_bfloat16x4(broadcast_var, broadcast_var, broadcast_var, broadcast_var), tl::pack_bfloat16x4(broadcast_var, broadcast_var, broadcast_var, broadcast_var));
      }
      *(ulonglong4*)(x_fragment + (i_3 * 16)) = condval;
    }
    amax_reducer_1[0] = bfloat16_t(0x0p+0f/*0.000000e+00*/);
    #pragma unroll
    for (int i_4 = 0; i_4 < 64; ++i_4) {
      amax_reducer_1[0] = cutlass::bfloat16_t(__hmax((amax_reducer_1[0]).to_nv_bfloat16(), (__habs(x_fragment[i_4])).to_nv_bfloat16()));
    }
    amax_fragment_1[0] = -CUDART_INF_F;
    amax_fragment_1[0] = max(amax_fragment_1[0], ((float)amax_reducer_1[0]));
    amax_fragment_1[0] = tl::AllReduce<tl::MaxOp, 256, 1, 0, tl::NamedBarrier<256>>::run(amax_fragment_1[0], (&(((float*)buf_dyn_shmem)[0])));
    float amax_1 = amax_fragment_1[0];
    float clamped_amax_1 = max(amax_1, 0x1.a36e2eb1c432dp-14f/*1.000000e-04*/);
    sf_1 = (clamped_amax_1 / 0x1.cp+8f/*4.480000e+02*/);
    float _reinterpret_tmp_1 = sf_1;
    uint bits_1 = (*(uint *)(&(_reinterpret_tmp_1)));
    uint exp_sf_1 = ((((bits_1 - (uint)1) >> (uint)23) + (uint)1) - (uint)127);
    uint v__4 = ((uint)127 - exp_sf_1) << (uint)23;
    float sf_4 = (*(float *)(&(v__4)));
    uint v__5 = ((uint)127 + exp_sf_1) << (uint)23;
    float sf_5 = (*(float *)(&(v__5)));
    out_sf[((((int64_t)((int)blockIdx.x)) * ((int64_t)sf_stride)) + ((int64_t)((int)blockIdx.y)))] = sf_5;
    sf_fragment[0] = sf_4;
    #pragma unroll
    for (int i_5 = 0; i_5 < 4; ++i_5) {
      for (int vec_1 = 0; vec_1 < 4; ++vec_1) {
        fp8_e4_4_t __4;
        float4 __5;
          float4 __6;
          uint2 v__6 = *(uint2*)(x_fragment + ((i_5 * 16) + (vec_1 * 4)));
          ((float2*)(&__6))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__6))[0]);
          ((float2*)(&__6))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__6))[1]);
          float4 v__7 = make_float4(sf_fragment[0], sf_fragment[0], sf_fragment[0], sf_fragment[0]);
          *(float2*)(&(__5.x)) = tl::mul2(*(float2*)(&(__6.x)), *(float2*)(&(v__7.x)));
          *(float2*)(&(__5.z)) = tl::mul2(*(float2*)(&(__6.z)), *(float2*)(&(v__7.z)));
        (reinterpret_cast<__nv_fp8x2_storage_t*>(&__4))[0] = __nv_cvt_float2_to_fp8x2(((float2*)(&__5))[0], __NV_SATFINITE, __NV_E4M3);
        (reinterpret_cast<__nv_fp8x2_storage_t*>(&__4))[1] = __nv_cvt_float2_to_fp8x2(((float2*)(&__5))[1], __NV_SATFINITE, __NV_E4M3);
        *(fp8_e4_4_t*)(out_local_cast_1 + (vec_1 * 4)) = __4;
      }
      if ((((((int)blockIdx.x) * 128) + (i_5 * 32)) + (((int)threadIdx.x) >> 3)) < num_tokens) {
        *(fp8_e4_16_t*)(out + (((((((int64_t)((int)blockIdx.x)) * (int64_t)917504) + (((int64_t)i_5) * (int64_t)229376)) + ((((int64_t)((int)threadIdx.x)) >> (int64_t)3) * (int64_t)7168)) + (((int64_t)((int)blockIdx.y)) * (int64_t)128)) + ((((int64_t)((int)threadIdx.x)) & (int64_t)7) * (int64_t)16))) = *(fp8_e4_16_t*)(out_local_cast_1 + 0);
      }
    }
  }
}

