// TileKernels CUDA dump (generated by scripts/dump_cuda_sources.py)
// Source Python: tile_kernels/quant/per_token_cast_to_e5m6_kernel.py
// JIT factory: get_per_token_cast_to_e5m6_kernel
// prim_func: per_token_cast_to_e5m6_kernel
// Compile args: {"args": [7168, 7168, {"sf_block": [1, 1], "torch_dtype": "torch.bfloat16", "use_packed_ue8m0": false, "use_tma_aligned_col_major_sf": false, "with_sf": false}, {"custom_clamp_min_value": 0.0001, "round_sf": true, "sf_block": [1, 7168], "torch_dtype": "torch.uint32", "use_packed_ue8m0": false, "use_tma_aligned_col_major_sf": false}], "kwargs": {}}
// Public API: tile_kernels.quant.per_token_cast_to_e5m6
#include <tl_templates/cuda/gemm.h>
#include <tl_templates/cuda/copy.h>
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#include <tl_templates/cuda/debug.h>
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void per_token_cast_to_e5m6_kernel_kernel(uint* __restrict__ out, float* __restrict__ out_sf, const bfloat16_t* __restrict__ x, int num_tokens, int out_sf_stride);
extern "C" __global__ void __launch_bounds__(128, 1) per_token_cast_to_e5m6_kernel_kernel(uint* __restrict__ out, float* __restrict__ out_sf, const bfloat16_t* __restrict__ x, int num_tokens, int out_sf_stride) {
  bfloat16_t x_fragment_reshaped[56];
  bfloat16_t amax_fragment[1];
  extern __shared__ __align__(1024) bfloat16_t workspace[];
  float sf = 0x0p+0f/*0.000000e+00*/;
  float sf_inv_fragment[1];
  float out_fragment[56];
  float in_local[8];
  ushort half_u16[8];
  half_t value_half = half_t(0x0p+0f/*0.000000e+00*/);
  uint out_local[3];
  #pragma unroll
  for (int i = 0; i < 7; ++i) {
    *(uint4*)(x_fragment_reshaped + (i * 8)) = *(uint4*)(x + (((((int64_t)((int)blockIdx.x)) * (int64_t)7168) + (((int64_t)i) * (int64_t)1024)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8)));
  }
  amax_fragment[0] = bfloat16_t(0x0p+0f/*0.000000e+00*/);
  #pragma unroll
  for (int rv = 0; rv < 56; ++rv) {
    amax_fragment[0] = cutlass::bfloat16_t(__hmax((amax_fragment[0]).to_nv_bfloat16(), (__habs(x_fragment_reshaped[(((rv % 7) * 8) + (rv / 7))])).to_nv_bfloat16()));
  }
  amax_fragment[0] = tl::AllReduce<tl::MaxOp, 128, 1, 0, tl::NamedBarrier<128>>::run(amax_fragment[0], (&(workspace[0])));
  float amax = ((float)amax_fragment[0]);
  float clamped_amax = max(amax, 0x1.a36e2eb1c432dp-14f/*1.000000e-04*/);
  sf = (clamped_amax / 0x1.fcp+15f/*6.502400e+04*/);
  float _reinterpret_tmp = sf;
  uint bits = (*(uint *)(&(_reinterpret_tmp)));
  uint exp_sf = ((((bits - (uint)1) >> (uint)23) + (uint)1) - (uint)127);
  uint v_ = ((uint)127 - exp_sf) << (uint)23;
  float sf_inv = (*(float *)(&(v_)));
  uint v__1 = ((uint)127 + exp_sf) << (uint)23;
  float sf_1 = (*(float *)(&(v__1)));
  out_sf[(((int64_t)((int)blockIdx.x)) * ((int64_t)out_sf_stride))] = sf_1;
  sf_inv_fragment[0] = sf_inv;
  #pragma unroll
  for (int i_1 = 0; i_1 < 14; ++i_1) {
    float4 __1;
      float4 __2;
      uint2 v__2 = *(uint2*)(x_fragment_reshaped + (i_1 * 4));
      ((float2*)(&__2))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__2))[0]);
      ((float2*)(&__2))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__2))[1]);
      float4 v__3 = make_float4(sf_inv_fragment[0], sf_inv_fragment[0], sf_inv_fragment[0], sf_inv_fragment[0]);
      *(float2*)(&(__1.x)) = tl::mul2(*(float2*)(&(__2.x)), *(float2*)(&(v__3.x)));
      *(float2*)(&(__1.z)) = tl::mul2(*(float2*)(&(__2.z)), *(float2*)(&(v__3.z)));
    *(float4*)(out_fragment + (i_1 * 4)) = __1;
  }
  #pragma unroll
  for (int i_2 = 0; i_2 < 7; ++i_2) {
    for (int j = 0; j < 8; ++j) {
      in_local[j] = out_fragment[((i_2 * 8) + j)];
    }
    #pragma unroll
    for (int i_3 = 0; i_3 < 8; ++i_3) {
      value_half = __float2half_rz(in_local[i_3]);
      half_t _reinterpret_tmp_1 = value_half;
      half_u16[i_3] = (*(ushort *)(&(_reinterpret_tmp_1)));
      float v__4 = in_local[i_3];
      uint value_u32 = (*(uint *)(&(v__4)));
      uint remain_bits = (value_u32 & (uint)131071);
      half_u16[i_3] = (half_u16[i_3] >> (ushort)4);
      bool cond = ((uint)65536 < (((uint)(half_u16[i_3] & (ushort)1)) + remain_bits));
      half_u16[i_3] = (half_u16[i_3] + ((ushort)cond));
    }
    out_local[0] = ((((uint)(half_u16[0] << (ushort)20)) | ((uint)(half_u16[1] << (ushort)8))) | ((uint)(half_u16[2] >> (ushort)4)));
    out_local[1] = (((((uint)(half_u16[2] << (ushort)28)) | ((uint)(half_u16[3] << (ushort)16))) | ((uint)(half_u16[4] << (ushort)4))) | ((uint)(half_u16[5] >> (ushort)8)));
    out_local[2] = ((((uint)(half_u16[5] << (ushort)24)) | ((uint)(half_u16[6] << (ushort)12))) | ((uint)half_u16[7]));
    for (int j_1 = 0; j_1 < 3; ++j_1) {
      out[((((((int64_t)((int)blockIdx.x)) * (int64_t)2688) + (((int64_t)i_2) * (int64_t)384)) + (((int64_t)((int)threadIdx.x)) * (int64_t)3)) + ((int64_t)j_1))] = out_local[j_1];
    }
  }
}

