// TileKernels CUDA dump (generated by scripts/dump_cuda_sources.py)
// Source Python: tile_kernels/quant/per_token_cast_kernel.py
// JIT factory: get_per_token_cast_kernel
// prim_func: per_token_cast_kernel
// Compile args: {"args": [7168, 7168, {"sf_block": [1, 1], "torch_dtype": "torch.bfloat16", "use_packed_ue8m0": false, "use_tma_aligned_col_major_sf": false, "with_sf": false}, {"custom_clamp_min_value": null, "round_sf": true, "sf_block": [1, 128], "torch_dtype": "torch.float8_e4m3fn", "use_packed_ue8m0": false, "use_tma_aligned_col_major_sf": false}], "kwargs": {}}
// Public API: tile_kernels.quant.per_token_cast
#include <tl_templates/cuda/cuda_fp8.h>
#include <tl_templates/cuda/gemm.h>
#include <tl_templates/cuda/copy.h>
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#include <tl_templates/cuda/debug.h>
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void per_token_cast_kernel_kernel(fp8_e4_t* __restrict__ out, float* __restrict__ out_sf, const bfloat16_t* __restrict__ x, int num_tokens, int out_sf_stride);
extern "C" __global__ void __launch_bounds__(128, 1) per_token_cast_kernel_kernel(fp8_e4_t* __restrict__ out, float* __restrict__ out_sf, const bfloat16_t* __restrict__ x, int num_tokens, int out_sf_stride) {
  bfloat16_t x_fragment_reshaped[32];
  bfloat16_t amax_fragment[2];
  float sf_inv_fragment[2];
  float sf = 0x0p+0f/*0.000000e+00*/;
  extern __shared__ __align__(1024) fp8_e4_t out_shared[];
  fp8_e4_t out_shared_local_cast[16];
  #pragma unroll
  for (int i = 0; i < 2; ++i) {
    ulonglong4 v_ = tl::load_global_256_conditional((&(x[(((((((int64_t)((int)blockIdx.x)) * (int64_t)28672) + (((int64_t)i) * (int64_t)14336)) + ((((int64_t)((int)threadIdx.x)) >> (int64_t)6) * (int64_t)7168)) + (((int64_t)((int)blockIdx.y)) * (int64_t)1024)) + ((((int64_t)((int)threadIdx.x)) & (int64_t)63) * (int64_t)16))])), ((((((int)blockIdx.x) * 4) + (i * 2)) + (((int)threadIdx.x) >> 6)) < num_tokens));
    *(ulonglong4*)(x_fragment_reshaped + (i * 16)) = (*(ulonglong4 *)(&(v_)));
  }
  #pragma unroll
  for (int i_1 = 0; i_1 < 2; ++i_1) {
    amax_fragment[i_1] = bfloat16_t(0x0p+0f/*0.000000e+00*/);
    #pragma unroll
    for (int rv = 0; rv < 16; ++rv) {
      amax_fragment[i_1] = cutlass::bfloat16_t(__hmax((amax_fragment[i_1]).to_nv_bfloat16(), (__habs(x_fragment_reshaped[((i_1 * 16) + rv)])).to_nv_bfloat16()));
    }
    amax_fragment[i_1] = tl::AllReduce<tl::MaxOp, 8, 1, 0, tl::NamedBarrier<128>>::run(amax_fragment[i_1]);
  }
  #pragma unroll
  for (int i_2 = 0; i_2 < 2; ++i_2) {
    float amax = ((float)amax_fragment[i_2]);
    float clamped_amax = max(amax, 0x1.a36e2eb1c432dp-14f/*1.000000e-04*/);
    sf = (clamped_amax / 0x1.cp+8f/*4.480000e+02*/);
    float _reinterpret_tmp = sf;
    uint bits = (*(uint *)(&(_reinterpret_tmp)));
    uint exp_sf = ((((bits - (uint)1) >> (uint)23) + (uint)1) - (uint)127);
    uint v__1 = ((uint)127 - exp_sf) << (uint)23;
    float sf_inv = (*(float *)(&(v__1)));
    uint v__2 = ((uint)127 + exp_sf) << (uint)23;
    float sf_1 = (*(float *)(&(v__2)));
    float _reinterpret_tmp_1 = sf_1;
    tl::store_global_32_conditional((&(out_sf[(((((int64_t)((int)blockIdx.y)) * (int64_t)8) + ((((int64_t)((int)threadIdx.x)) & (int64_t)63) >> (int64_t)3)) + ((((((int64_t)((int)blockIdx.x)) * (int64_t)4) + (((int64_t)i_2) * (int64_t)2)) + (((int64_t)((int)threadIdx.x)) >> (int64_t)6)) * ((int64_t)out_sf_stride)))])), (*(uint *)(&(_reinterpret_tmp_1))), ((((((int)blockIdx.x) * 4) + (i_2 * 2)) + (((int)threadIdx.x) >> 6)) < num_tokens));
    sf_inv_fragment[i_2] = sf_inv;
  }
  #pragma unroll
  for (int i_3 = 0; i_3 < 2; ++i_3) {
    for (int vec = 0; vec < 4; ++vec) {
      fp8_e4_4_t __1;
      float4 __2;
        float4 __3;
        uint2 v__3 = *(uint2*)(x_fragment_reshaped + ((i_3 * 16) + (vec * 4)));
        ((float2*)(&__3))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__3))[0]);
        ((float2*)(&__3))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__3))[1]);
        float4 v__4 = make_float4(sf_inv_fragment[i_3], sf_inv_fragment[i_3], sf_inv_fragment[i_3], sf_inv_fragment[i_3]);
        *(float2*)(&(__2.x)) = tl::mul2(*(float2*)(&(__3.x)), *(float2*)(&(v__4.x)));
        *(float2*)(&(__2.z)) = tl::mul2(*(float2*)(&(__3.z)), *(float2*)(&(v__4.z)));
      (reinterpret_cast<__nv_fp8x2_storage_t*>(&__1))[0] = __nv_cvt_float2_to_fp8x2(((float2*)(&__2))[0], __NV_SATFINITE, __NV_E4M3);
      (reinterpret_cast<__nv_fp8x2_storage_t*>(&__1))[1] = __nv_cvt_float2_to_fp8x2(((float2*)(&__2))[1], __NV_SATFINITE, __NV_E4M3);
      *(fp8_e4_4_t*)(out_shared_local_cast + (vec * 4)) = __1;
    }
    *(fp8_e4_16_t*)(out_shared + ((i_3 * 2048) + (((int)threadIdx.x) * 16))) = *(fp8_e4_16_t*)(out_shared_local_cast + 0);
  }
  #pragma unroll
  for (int i_4 = 0; i_4 < 2; ++i_4) {
    fp8_e4_16_t v__5 = *(fp8_e4_16_t*)(out_shared + ((i_4 * 2048) + (((int)threadIdx.x) * 16)));
    tl::store_global_128_conditional((&(out[(((((((int64_t)((int)blockIdx.x)) * (int64_t)28672) + (((int64_t)i_4) * (int64_t)14336)) + ((((int64_t)((int)threadIdx.x)) >> (int64_t)6) * (int64_t)7168)) + (((int64_t)((int)blockIdx.y)) * (int64_t)1024)) + ((((int64_t)((int)threadIdx.x)) & (int64_t)63) * (int64_t)16))])), (*(uint4 *)(&(v__5))), ((((((int)blockIdx.x) * 4) + (i_4 * 2)) + (((int)threadIdx.x) >> 6)) < num_tokens));
  }
}

