// TileKernels CUDA dump (generated by scripts/dump_cuda_sources.py)
// Source Python: tile_kernels/quant/per_block_cast_lossless_kernel.py
// JIT factory: get_per_block_cast_lossless_kernel
// prim_func: per_block_cast_lossless_kernel
// Compile args: {"args": [7168, 7168, {"sf_block": [1, 32], "torch_dtype": "torch.int8", "use_packed_ue8m0": false, "use_tma_aligned_col_major_sf": false, "with_sf": true}, {"custom_clamp_min_value": null, "round_sf": true, "sf_block": [128, 128], "torch_dtype": "torch.float8_e4m3fn", "use_packed_ue8m0": false, "use_tma_aligned_col_major_sf": false}], "kwargs": {}}
// Public API: tile_kernels.quant.per_block_cast_lossless
#include <tl_templates/cuda/cuda_fp8.h>
#include <tl_templates/cuda/cuda_fp4.h>
#include <tl_templates/cuda/gemm.h>
#include <tl_templates/cuda/copy.h>
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#include <tl_templates/cuda/debug.h>
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void per_block_cast_lossless_kernel_kernel(fp8_e4_t* __restrict__ out, float* __restrict__ out_sf, const fp4_e2_t* __restrict__ x, const float* __restrict__ x_sf, int in_sf_stride, int num_tokens, int out_sf_stride);
extern "C" __global__ void __launch_bounds__(256, 1) per_block_cast_lossless_kernel_kernel(fp8_e4_t* __restrict__ out, float* __restrict__ out_sf, const fp4_e2_t* __restrict__ x, const float* __restrict__ x_sf, int in_sf_stride, int num_tokens, int out_sf_stride) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  float x_sf_fragment[2];
  uint x_sf_uint32_fragment[2];
  uint x_sf_uint32_fragment_reshaped[2];
  uint out_sf_uint32_fragment[1];
  fp8_e4_t x_out_fragment[64];
  fp4_e2_2_t x_in_shared_local_cast_packed[16];
  #pragma unroll
  for (int i = 0; i < 2; ++i) {
    fp4_e2_t broadcast_var = fp4_e2_t(0x0p+0f/*0.000000e+00*/);
    fp4_e2_32_t condval;
    if (((((((int)blockIdx.x) * 128) + (i * 64)) + (((int)threadIdx.x) >> 2)) < num_tokens)) {
      condval = *(fp4_e2_32_t*)(x + (((((((int64_t)((int)blockIdx.x)) * (int64_t)458752) + (((int64_t)i) * (int64_t)229376)) + ((((int64_t)((int)threadIdx.x)) >> (int64_t)2) * (int64_t)3584)) + (((int64_t)((int)blockIdx.y)) * (int64_t)64)) + ((((int64_t)((int)threadIdx.x)) & (int64_t)3) * (int64_t)16)));
    } else {
      condval = make_fp4_e2_32_t(broadcast_var, broadcast_var, broadcast_var, broadcast_var, broadcast_var, broadcast_var, broadcast_var, broadcast_var, broadcast_var, broadcast_var, broadcast_var, broadcast_var, broadcast_var, broadcast_var, broadcast_var, broadcast_var, broadcast_var, broadcast_var, broadcast_var, broadcast_var, broadcast_var, broadcast_var, broadcast_var, broadcast_var, broadcast_var, broadcast_var, broadcast_var, broadcast_var, broadcast_var, broadcast_var, broadcast_var, broadcast_var);
    }
    *(fp4_e2_32_t*)(((fp4_e2_t*)buf_dyn_shmem) + ((i * 4096) + (((int)threadIdx.x) * 16))) = condval;
  }
  float broadcast_var_1 = 0x0p+0f/*0.000000e+00*/;
  *(float2*)(x_sf_fragment + 0) = make_float2(broadcast_var_1, broadcast_var_1);
  #pragma unroll
  for (int i_1 = 0; i_1 < 2; ++i_1) {
    float condval_1;
    if (((((((int)blockIdx.x) * 128) + (i_1 * 64)) + (((int)threadIdx.x) >> 2)) < num_tokens)) {
      condval_1 = x_sf[(((((int64_t)((int)blockIdx.y)) * (int64_t)4) + ((((((int64_t)((int)blockIdx.x)) * (int64_t)128) + (((int64_t)i_1) * (int64_t)64)) + (((int64_t)((int)threadIdx.x)) >> (int64_t)2)) * ((int64_t)in_sf_stride))) + (((int64_t)((int)threadIdx.x)) & (int64_t)3))];
    } else {
      condval_1 = 0x0p+0f/*0.000000e+00*/;
    }
    x_sf_fragment[i_1] = condval_1;
  }
  uint broadcast_var_2 = (uint)0;
  *(uint2*)(x_sf_uint32_fragment + 0) = make_uint2(broadcast_var_2, broadcast_var_2);
  uint broadcast_var_3 = (uint)0;
  *(uint2*)(x_sf_uint32_fragment_reshaped + 0) = make_uint2(broadcast_var_3, broadcast_var_3);
  #pragma unroll
  for (int i_2 = 0; i_2 < 2; ++i_2) {
    if ((((((int)blockIdx.x) * 128) + (i_2 * 64)) + (((int)threadIdx.x) >> 2)) < num_tokens) {
      float sf = x_sf_fragment[i_2];
      float _reinterpret_tmp = sf;
      x_sf_uint32_fragment[i_2] = ((*(uint *)(&(_reinterpret_tmp))) >> (uint)23);
      x_sf_uint32_fragment_reshaped[i_2] = x_sf_uint32_fragment[i_2];
    }
  }
  out_sf_uint32_fragment[0] = (uint)0;
  #pragma unroll
  for (int rv = 0; rv < 2; ++rv) {
    out_sf_uint32_fragment[0] = max(out_sf_uint32_fragment[0], x_sf_uint32_fragment_reshaped[rv]);
  }
  __syncthreads();
  out_sf_uint32_fragment[0] = tl::AllReduce<tl::MaxOp, 256, 1, 0, tl::NamedBarrier<256>>::run(out_sf_uint32_fragment[0], (&(((uint*)buf_dyn_shmem)[4096])));
  uint condval_2;
  if (((uint)1 <= (out_sf_uint32_fragment[0] / (uint)6))) {
    condval_2 = (out_sf_uint32_fragment[0] - (uint)6);
  } else {
    condval_2 = (uint)0;
  }
  out_sf_uint32_fragment[0] = condval_2;
  #pragma unroll
  for (int i_3 = 0; i_3 < 2; ++i_3) {
    if ((((((int)blockIdx.x) * 128) + (i_3 * 64)) + (((int)threadIdx.x) >> 2)) < num_tokens) {
      bool condition = (out_sf_uint32_fragment[0] <= (x_sf_uint32_fragment[i_3] + (uint)5));
      device_assert_with_msg(condition, "\n  at per_block_cast_lossless_kernel.py:128 in per_block_cast_lossless_kernel\n");
      x_sf_uint32_fragment[i_3] = ((x_sf_uint32_fragment[i_3] - out_sf_uint32_fragment[0]) + (uint)127);
    }
  }
  __syncthreads();
  #pragma unroll
  for (int i_4 = 0; i_4 < 2; ++i_4) {
    *(fp4_e2_32_t*)(x_in_shared_local_cast_packed + 0) = *(fp4_e2_32_t*)(((fp4_e2_t*)buf_dyn_shmem) + ((i_4 * 4096) + (((int)threadIdx.x) * 16)));
    for (int vec = 0; vec < 8; ++vec) {
      fp8_e4_4_t __1;
      float4 __2;
        float4 __3;
        fp4_e2_4_t v_ = *(fp4_e2_4_t*)(x_in_shared_local_cast_packed + (vec * 2));
        ((float2*)(&__3))[0] = __tl_cvt_fp4x2_to_float2((reinterpret_cast<uint8_t*>(&v_))[0]);
        ((float2*)(&__3))[1] = __tl_cvt_fp4x2_to_float2((reinterpret_cast<uint8_t*>(&v_))[1]);
        uint v__1 = x_sf_uint32_fragment[i_4] << (uint)23;
        float4 v__2 = make_float4((*(float *)(&(v__1))), (*(float *)(&(v__1))), (*(float *)(&(v__1))), (*(float *)(&(v__1))));
        *(float2*)(&(__2.x)) = tl::mul2(*(float2*)(&(__3.x)), *(float2*)(&(v__2.x)));
        *(float2*)(&(__2.z)) = tl::mul2(*(float2*)(&(__3.z)), *(float2*)(&(v__2.z)));
      (reinterpret_cast<__nv_fp8x2_storage_t*>(&__1))[0] = __nv_cvt_float2_to_fp8x2(((float2*)(&__2))[0], __NV_SATFINITE, __NV_E4M3);
      (reinterpret_cast<__nv_fp8x2_storage_t*>(&__1))[1] = __nv_cvt_float2_to_fp8x2(((float2*)(&__2))[1], __NV_SATFINITE, __NV_E4M3);
      *(fp8_e4_4_t*)(x_out_fragment + ((i_4 * 32) + (vec * 4))) = __1;
    }
  }
  if (((int)threadIdx.x) == 0) {
    uint sf_1 = out_sf_uint32_fragment[0];
    uint v__3 = sf_1 << (uint)23;
    float sf_2 = (*(float *)(&(v__3)));
    out_sf[((((int64_t)((int)blockIdx.x)) * ((int64_t)out_sf_stride)) + ((int64_t)((int)blockIdx.y)))] = sf_2;
  }
  #pragma unroll
  for (int i_5 = 0; i_5 < 2; ++i_5) {
    if ((((((int)blockIdx.x) * 128) + (i_5 * 64)) + (((int)threadIdx.x) >> 2)) < num_tokens) {
      tl::store_global_256(&(*(fp8_e4_32_t*)(out + (((((((int64_t)((int)blockIdx.x)) * (int64_t)917504) + (((int64_t)i_5) * (int64_t)458752)) + ((((int64_t)((int)threadIdx.x)) >> (int64_t)2) * (int64_t)7168)) + (((int64_t)((int)blockIdx.y)) * (int64_t)128)) + ((((int64_t)((int)threadIdx.x)) & (int64_t)3) * (int64_t)32)))), *(fp8_e4_32_t*)(x_out_fragment + (i_5 * 32)));
    }
  }
}

