// TileKernels CUDA dump (generated by scripts/dump_cuda_sources.py)
// Source Python: tile_kernels/quant/swiglu_forward_and_per_channel_cast_and_transpose_kernel.py
// JIT factory: get_swiglu_forward_and_per_channel_cast_and_transpose_kernel
// prim_func: swiglu_forward_and_per_channel_cast_and_transpose_kernel
// Compile args: {"args": [7168, false, false, "bfloat16", {"custom_clamp_min_value": null, "round_sf": true, "sf_block": [128, 1], "torch_dtype": "torch.float8_e4m3fn", "use_packed_ue8m0": false, "use_tma_aligned_col_major_sf": false}, 0.0], "kwargs": {}}
// Public API: tile_kernels.quant.swiglu_forward_and_per_channel_cast_and_transpose
#include <tl_templates/cuda/cuda_fp8.h>
#include <tl_templates/cuda/gemm.h>
#include <tl_templates/cuda/copy.h>
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#include <tl_templates/cuda/debug.h>
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void swiglu_forward_and_per_channel_cast_and_transpose_kernel_kernel(fp8_e4_t* __restrict__ out, float* __restrict__ out_sf, const bfloat16_t* __restrict__ x, int num_tokens);
extern "C" __global__ void __launch_bounds__(256, 1) swiglu_forward_and_per_channel_cast_and_transpose_kernel_kernel(fp8_e4_t* __restrict__ out, float* __restrict__ out_sf, const bfloat16_t* __restrict__ x, int num_tokens) {
  extern __shared__ __align__(1024) bfloat16_t act_shared[];
  bfloat16_t x_act_local[16];
  bfloat16_t tmp_l[4];
  bfloat16_t tmp_r[4];
  float val_l = 0x0p+0f/*0.000000e+00*/;
  float val_r = 0x0p+0f/*0.000000e+00*/;
  float out_fragment_reshaped[8];
  bfloat16_t act_shared_local_cast[4];
  float amax_fragment[1];
  float sf = 0x0p+0f/*0.000000e+00*/;
  fp8_e4_t out_local_cast_1[8];
  #pragma unroll
  for (int i_ = 0; i_ < 2; ++i_) {
    #pragma unroll
    for (int j = 0; j < 4; ++j) {
      *(uint2*)(tmp_l + 0) = *(uint2*)(x + ((((((((int64_t)((int)blockIdx.y)) * (int64_t)1835008) + (((int64_t)i_) * (int64_t)917504)) + ((((int64_t)((int)threadIdx.x)) >> (int64_t)4) * (int64_t)57344)) + (((int64_t)j) * (int64_t)14336)) + (((int64_t)((int)blockIdx.x)) * (int64_t)64)) + ((((int64_t)((int)threadIdx.x)) & (int64_t)15) * (int64_t)4)));
      *(uint2*)(tmp_r + 0) = *(uint2*)(x + (((((((((int64_t)((int)blockIdx.y)) * (int64_t)1835008) + (((int64_t)i_) * (int64_t)917504)) + ((((int64_t)((int)threadIdx.x)) >> (int64_t)4) * (int64_t)57344)) + (((int64_t)j) * (int64_t)14336)) + (((int64_t)((int)blockIdx.x)) * (int64_t)64)) + ((((int64_t)((int)threadIdx.x)) & (int64_t)15) * (int64_t)4)) + (int64_t)7168));
      #pragma unroll
      for (int k = 0; k < 4; ++k) {
        val_l = ((float)tmp_l[k]);
        val_r = ((float)tmp_r[k]);
        float val = ((val_l / (0x1p+0f/*1.000000e+00*/ + expf((val_l * -0x1p+0f/*-1.000000e+00*/)))) * val_r);
        x_act_local[((k * 4) + j)] = ((bfloat16_t)val);
      }
    }
    #pragma unroll
    for (int j_1 = 0; j_1 < 4; ++j_1) {
      *(uint2*)(act_shared + (((((((int)threadIdx.x) & 15) * 528) + (j_1 * 132)) + (i_ * 64)) + ((((int)threadIdx.x) >> 4) * 4))) = *(uint2*)(x_act_local + (j_1 * 4));
    }
  }
  __syncthreads();
  #pragma unroll
  for (int stage = 0; stage < 4; ++stage) {
    #pragma unroll
    for (int i = 0; i < 2; ++i) {
      *(uint2*)(act_shared_local_cast + 0) = *(uint2*)(act_shared + ((((stage * 2112) + ((((int)threadIdx.x) >> 4) * 132)) + ((((int)threadIdx.x) & 15) * 8)) + (i * 4)));
      float4 __1;
      uint2 v_ = *(uint2*)(act_shared_local_cast + 0);
      ((float2*)(&__1))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[0]);
      ((float2*)(&__1))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[1]);
      *(float4*)(out_fragment_reshaped + (i * 4)) = __1;
    }
    amax_fragment[0] = 0x0p+0f/*0.000000e+00*/;
    #pragma unroll
    for (int rv = 0; rv < 8; ++rv) {
      amax_fragment[0] = max(amax_fragment[0], fabsf(out_fragment_reshaped[rv]));
    }
    amax_fragment[0] = tl::AllReduce<tl::MaxOp, 16, 1, 0, tl::NamedBarrier<256>>::run(amax_fragment[0]);
    float amax = amax_fragment[0];
    float clamped_amax = max(amax, 0x1.a36e2eb1c432dp-14f/*1.000000e-04*/);
    sf = (clamped_amax / 0x1.cp+8f/*4.480000e+02*/);
    float _reinterpret_tmp = sf;
    uint bits = (*(uint *)(&(_reinterpret_tmp)));
    uint exp_sf = ((((bits - (uint)1) >> (uint)23) + (uint)1) - (uint)127);
    uint v__1 = ((uint)127 - exp_sf) << (uint)23;
    float sf_inv = (*(float *)(&(v__1)));
    uint v__2 = ((uint)127 + exp_sf) << (uint)23;
    float sf_1 = (*(float *)(&(v__2)));
    out_sf[((((((int64_t)((int)blockIdx.y)) * (int64_t)7168) + (((int64_t)((int)blockIdx.x)) * (int64_t)64)) + (((int64_t)stage) * (int64_t)16)) + (((int64_t)((int)threadIdx.x)) >> (int64_t)4))] = sf_1;
    amax_fragment[0] = sf_inv;
    for (int i_1 = 0; i_1 < 2; ++i_1) {
      fp8_e4_4_t __2;
      float4 __3;
        float4 v__3 = *(float4*)(out_fragment_reshaped + (i_1 * 4));
        float4 v__4 = make_float4(amax_fragment[0], amax_fragment[0], amax_fragment[0], amax_fragment[0]);
        *(float2*)(&(__3.x)) = tl::mul2(*(float2*)(&(v__3.x)), *(float2*)(&(v__4.x)));
        *(float2*)(&(__3.z)) = tl::mul2(*(float2*)(&(v__3.z)), *(float2*)(&(v__4.z)));
      (reinterpret_cast<__nv_fp8x2_storage_t*>(&__2))[0] = __nv_cvt_float2_to_fp8x2(((float2*)(&__3))[0], __NV_SATFINITE, __NV_E4M3);
      (reinterpret_cast<__nv_fp8x2_storage_t*>(&__2))[1] = __nv_cvt_float2_to_fp8x2(((float2*)(&__3))[1], __NV_SATFINITE, __NV_E4M3);
      *(fp8_e4_4_t*)(out_local_cast_1 + (i_1 * 4)) = __2;
    }
    *(fp8_e4_8_t*)(out + (((((int64_t)((int)blockIdx.y)) * (int64_t)128) + ((((int64_t)((int)threadIdx.x)) & (int64_t)15) * (int64_t)8)) + ((((((int64_t)((int)blockIdx.x)) * (int64_t)64) + (((int64_t)stage) * (int64_t)16)) + (((int64_t)((int)threadIdx.x)) >> (int64_t)4)) * ((int64_t)num_tokens)))) = *(fp8_e4_8_t*)(out_local_cast_1 + 0);
  }
}

