// TileKernels CUDA dump (generated by scripts/dump_cuda_sources.py)
// Source Python: tile_kernels/quant/swiglu_backward_and_per_token_cast_kernel.py
// JIT factory: get_swiglu_backward_and_per_token_cast_kernel
// prim_func: swiglu_backward_and_per_token_cast_kernel
// Compile args: {"args": [3584, {"custom_clamp_min_value": null, "round_sf": true, "sf_block": [1, 128], "torch_dtype": "torch.float8_e4m3fn", "use_packed_ue8m0": false, "use_tma_aligned_col_major_sf": false}, false], "kwargs": {}}
// Public API: tile_kernels.quant.swiglu_backward_and_per_token_cast
#include <tl_templates/cuda/cuda_fp8.h>
#include <tl_templates/cuda/gemm.h>
#include <tl_templates/cuda/copy.h>
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#include <tl_templates/cuda/debug.h>
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void swiglu_backward_and_per_token_cast_kernel_kernel(const bfloat16_t* __restrict__ grad_out, bfloat16_t* __restrict__ out, const int* __restrict__ pos_to_token_topk, const int* __restrict__ token_topk_to_pos, const float* __restrict__ weight, float* __restrict__ weight_grad, const fp8_e4_t* __restrict__ x, bfloat16_t* __restrict__ x_grad, fp8_e4_t* __restrict__ x_grad_fp8, float* __restrict__ x_grad_fp8_sf_invs, const float* __restrict__ x_sf, int num_expand_tokens, int num_tokens, int num_topk);
extern "C" __global__ void __launch_bounds__(64, 1) swiglu_backward_and_per_token_cast_kernel_kernel(const bfloat16_t* __restrict__ grad_out, bfloat16_t* __restrict__ out, const int* __restrict__ pos_to_token_topk, const int* __restrict__ token_topk_to_pos, const float* __restrict__ weight, float* __restrict__ weight_grad, const fp8_e4_t* __restrict__ x, bfloat16_t* __restrict__ x_grad, fp8_e4_t* __restrict__ x_grad_fp8, float* __restrict__ x_grad_fp8_sf_invs, const float* __restrict__ x_sf, int num_expand_tokens, int num_tokens, int num_topk) {
  float acc[1];
  fp8_e4_t x_fragment[8];
  fp8_e4_t y_fragment[8];
  bfloat16_t grad_out_fragment[8];
  float x_sf_fragment[1];
  float y_sf_fragment[1];
  bfloat16_t out_fragment[8];
  float x_grad_fragment_reshaped[8];
  float y_grad_fragment_reshaped[8];
  float x_fp32 = 0x0p+0f/*0.000000e+00*/;
  float y_fp32 = 0x0p+0f/*0.000000e+00*/;
  float xmax_fragment[1];
  float ymax_fragment[1];
  float sf = 0x0p+0f/*0.000000e+00*/;
  float sf_1 = 0x0p+0f/*0.000000e+00*/;
  fp8_e4_t x_grad_fp8_fragment[8];
  fp8_e4_t y_grad_pt_fragment[8];
  extern __shared__ __align__(1024) float workspace[];
  acc[0] = 0x0p+0f/*0.000000e+00*/;
  if (((int)blockIdx.x) < (num_tokens * num_topk)) {
    int pos = token_topk_to_pos[((int64_t)((int)blockIdx.x))];
    if (pos == -1) {
      weight_grad[((int64_t)((int)blockIdx.x))] = 0x0p+0f/*0.000000e+00*/;
    }
  }
  if (num_expand_tokens <= ((int)blockIdx.x)) {
    return;
  }
  int condval;
  if ((((int)blockIdx.x) < num_expand_tokens)) {
    condval = pos_to_token_topk[((int64_t)((int)blockIdx.x))];
  } else {
    condval = 0;
  }
  int index = condval;
  float w = ((0 <= index) ? weight[((int64_t)index)] : 0x0p+0f/*0.000000e+00*/);
  for (int k = 0; k < 7; ++k) {
    fp8_e4_t broadcast_var = fp8_e4_t(0x0p+0f/*0.000000e+00*/);
    fp8_e4_8_t condval_1;
    if ((((int)blockIdx.x) < num_expand_tokens)) {
      condval_1 = *(fp8_e4_8_t*)(x + (((((int64_t)((int)blockIdx.x)) * (int64_t)7168) + (((int64_t)k) * (int64_t)512)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8)));
    } else {
      condval_1 = make_fp8_e4_8_t(broadcast_var, broadcast_var, broadcast_var, broadcast_var, broadcast_var, broadcast_var, broadcast_var, broadcast_var);
    }
    *(fp8_e4_8_t*)(x_fragment + 0) = condval_1;
    fp8_e4_t broadcast_var_1 = fp8_e4_t(0x0p+0f/*0.000000e+00*/);
    fp8_e4_8_t condval_2;
    if ((((int)blockIdx.x) < num_expand_tokens)) {
      condval_2 = *(fp8_e4_8_t*)(x + ((((((int64_t)((int)blockIdx.x)) * (int64_t)7168) + (((int64_t)k) * (int64_t)512)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8)) + (int64_t)3584));
    } else {
      condval_2 = make_fp8_e4_8_t(broadcast_var_1, broadcast_var_1, broadcast_var_1, broadcast_var_1, broadcast_var_1, broadcast_var_1, broadcast_var_1, broadcast_var_1);
    }
    *(fp8_e4_8_t*)(y_fragment + 0) = condval_2;
    bfloat16_t broadcast_var_2 = bfloat16_t(0x0p+0f/*0.000000e+00*/);
    uint4 condval_3;
    if ((((int)blockIdx.x) < num_expand_tokens)) {
      condval_3 = *(uint4*)(grad_out + (((((int64_t)((int)blockIdx.x)) * (int64_t)3584) + (((int64_t)k) * (int64_t)512)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8)));
    } else {
      condval_3 = make_uint4(__pack_nv_bfloat162(broadcast_var_2, broadcast_var_2), __pack_nv_bfloat162(broadcast_var_2, broadcast_var_2), __pack_nv_bfloat162(broadcast_var_2, broadcast_var_2), __pack_nv_bfloat162(broadcast_var_2, broadcast_var_2));
    }
    *(uint4*)(grad_out_fragment + 0) = condval_3;
    float condval_4;
    if ((((int)blockIdx.x) < num_expand_tokens)) {
      condval_4 = x_sf[(((((int64_t)((int)blockIdx.x)) * (int64_t)56) + (((int64_t)k) * (int64_t)4)) + (((int64_t)((int)threadIdx.x)) >> (int64_t)4))];
    } else {
      condval_4 = 0x0p+0f/*0.000000e+00*/;
    }
    x_sf_fragment[0] = condval_4;
    float condval_5;
    if ((((int)blockIdx.x) < num_expand_tokens)) {
      condval_5 = x_sf[((((((int64_t)((int)blockIdx.x)) * (int64_t)56) + (((int64_t)k) * (int64_t)4)) + (((int64_t)((int)threadIdx.x)) >> (int64_t)4)) + (int64_t)28)];
    } else {
      condval_5 = 0x0p+0f/*0.000000e+00*/;
    }
    y_sf_fragment[0] = condval_5;
    #pragma unroll
    for (int i = 0; i < 8; ++i) {
      x_fp32 = (((float)x_fragment[i]) * x_sf_fragment[0]);
      y_fp32 = (((float)y_fragment[i]) * y_sf_fragment[0]);
      float grad_out_fp32 = ((float)grad_out_fragment[i]);
      float tmp_fp32 = (0x1p+0f/*1.000000e+00*/ + expf((x_fp32 * -0x1p+0f/*-1.000000e+00*/)));
      float act_out = ((x_fp32 / tmp_fp32) * y_fp32);
      acc[0] = (acc[0] + (grad_out_fp32 * act_out));
      float s_fp32 = (0x1p+0f/*1.000000e+00*/ / tmp_fp32);
      float grad_out_fp32_ws = ((grad_out_fp32 * w) * s_fp32);
      out_fragment[i] = ((bfloat16_t)(act_out * w));
      x_grad_fragment_reshaped[i] = ((grad_out_fp32_ws * y_fp32) * (0x1p+0f/*1.000000e+00*/ + (x_fp32 * (0x1p+0f/*1.000000e+00*/ - s_fp32))));
      y_grad_fragment_reshaped[i] = (grad_out_fp32_ws * x_fp32);
    }
    if (((int)blockIdx.x) < num_expand_tokens) {
      uint4 __1;
      ulonglong4 v_ = *(ulonglong4*)(x_grad_fragment_reshaped + 0);
      (reinterpret_cast<__nv_bfloat162*>(&__1))[0] = __float22bfloat162_rn(((float2*)(&v_))[0]);
      (reinterpret_cast<__nv_bfloat162*>(&__1))[1] = __float22bfloat162_rn(((float2*)(&v_))[1]);
      (reinterpret_cast<__nv_bfloat162*>(&__1))[2] = __float22bfloat162_rn(((float2*)(&v_))[2]);
      (reinterpret_cast<__nv_bfloat162*>(&__1))[3] = __float22bfloat162_rn(((float2*)(&v_))[3]);
      *(uint4*)(x_grad + (((((int64_t)((int)blockIdx.x)) * (int64_t)7168) + (((int64_t)k) * (int64_t)512)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8))) = __1;
      uint4 __2;
      ulonglong4 v__1 = *(ulonglong4*)(y_grad_fragment_reshaped + 0);
      (reinterpret_cast<__nv_bfloat162*>(&__2))[0] = __float22bfloat162_rn(((float2*)(&v__1))[0]);
      (reinterpret_cast<__nv_bfloat162*>(&__2))[1] = __float22bfloat162_rn(((float2*)(&v__1))[1]);
      (reinterpret_cast<__nv_bfloat162*>(&__2))[2] = __float22bfloat162_rn(((float2*)(&v__1))[2]);
      (reinterpret_cast<__nv_bfloat162*>(&__2))[3] = __float22bfloat162_rn(((float2*)(&v__1))[3]);
      *(uint4*)(x_grad + ((((((int64_t)((int)blockIdx.x)) * (int64_t)7168) + (((int64_t)k) * (int64_t)512)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8)) + (int64_t)3584)) = __2;
      *(uint4*)(out + (((((int64_t)((int)blockIdx.x)) * (int64_t)3584) + (((int64_t)k) * (int64_t)512)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8))) = *(uint4*)(out_fragment + 0);
    }
    xmax_fragment[0] = 0x0p+0f/*0.000000e+00*/;
    #pragma unroll
    for (int rv = 0; rv < 8; ++rv) {
      xmax_fragment[0] = max(xmax_fragment[0], fabsf(x_grad_fragment_reshaped[rv]));
    }
    xmax_fragment[0] = tl::AllReduce<tl::MaxOp, 16, 1, 0, tl::NamedBarrier<64>>::run(xmax_fragment[0]);
    ymax_fragment[0] = 0x0p+0f/*0.000000e+00*/;
    #pragma unroll
    for (int rv_1 = 0; rv_1 < 8; ++rv_1) {
      ymax_fragment[0] = max(ymax_fragment[0], fabsf(y_grad_fragment_reshaped[rv_1]));
    }
    ymax_fragment[0] = tl::AllReduce<tl::MaxOp, 16, 1, 0, tl::NamedBarrier<64>>::run(ymax_fragment[0]);
    float amax = xmax_fragment[0];
    float clamped_amax = max(amax, 0x1.a36e2eb1c432dp-14f/*1.000000e-04*/);
    sf = (clamped_amax / 0x1.cp+8f/*4.480000e+02*/);
    float _reinterpret_tmp = sf;
    uint bits = (*(uint *)(&(_reinterpret_tmp)));
    uint exp_sf = ((((bits - (uint)1) >> (uint)23) + (uint)1) - (uint)127);
    uint v__2 = ((uint)127 - exp_sf) << (uint)23;
    float x_sf_inv = (*(float *)(&(v__2)));
    uint v__3 = ((uint)127 + exp_sf) << (uint)23;
    float x_sf_1 = (*(float *)(&(v__3)));
    float amax_1 = ymax_fragment[0];
    float clamped_amax_1 = max(amax_1, 0x1.a36e2eb1c432dp-14f/*1.000000e-04*/);
    sf_1 = (clamped_amax_1 / 0x1.cp+8f/*4.480000e+02*/);
    float _reinterpret_tmp_1 = sf_1;
    uint bits_1 = (*(uint *)(&(_reinterpret_tmp_1)));
    uint exp_sf_1 = ((((bits_1 - (uint)1) >> (uint)23) + (uint)1) - (uint)127);
    uint v__4 = ((uint)127 - exp_sf_1) << (uint)23;
    float y_sf_inv = (*(float *)(&(v__4)));
    uint v__5 = ((uint)127 + exp_sf_1) << (uint)23;
    float y_sf = (*(float *)(&(v__5)));
    if (((int)blockIdx.x) < num_expand_tokens) {
      x_grad_fp8_sf_invs[(((((int64_t)((int)blockIdx.x)) * (int64_t)56) + (((int64_t)k) * (int64_t)4)) + (((int64_t)((int)threadIdx.x)) >> (int64_t)4))] = x_sf_1;
      x_grad_fp8_sf_invs[((((((int64_t)((int)blockIdx.x)) * (int64_t)56) + (((int64_t)k) * (int64_t)4)) + (((int64_t)((int)threadIdx.x)) >> (int64_t)4)) + (int64_t)28)] = y_sf;
    }
    xmax_fragment[0] = x_sf_inv;
    ymax_fragment[0] = y_sf_inv;
    #pragma unroll
    for (int i_1 = 0; i_1 < 2; ++i_1) {
      fp8_e4_4_t __3;
      float4 __4;
        float4 v__6 = *(float4*)(x_grad_fragment_reshaped + (i_1 * 4));
        float4 v__7 = make_float4(xmax_fragment[0], xmax_fragment[0], xmax_fragment[0], xmax_fragment[0]);
        *(float2*)(&(__4.x)) = tl::mul2(*(float2*)(&(v__6.x)), *(float2*)(&(v__7.x)));
        *(float2*)(&(__4.z)) = tl::mul2(*(float2*)(&(v__6.z)), *(float2*)(&(v__7.z)));
      (reinterpret_cast<__nv_fp8x2_storage_t*>(&__3))[0] = __nv_cvt_float2_to_fp8x2(((float2*)(&__4))[0], __NV_SATFINITE, __NV_E4M3);
      (reinterpret_cast<__nv_fp8x2_storage_t*>(&__3))[1] = __nv_cvt_float2_to_fp8x2(((float2*)(&__4))[1], __NV_SATFINITE, __NV_E4M3);
      *(fp8_e4_4_t*)(x_grad_fp8_fragment + (i_1 * 4)) = __3;
      fp8_e4_4_t __5;
      float4 __6;
        float4 v__8 = *(float4*)(y_grad_fragment_reshaped + (i_1 * 4));
        float4 v__9 = make_float4(ymax_fragment[0], ymax_fragment[0], ymax_fragment[0], ymax_fragment[0]);
        *(float2*)(&(__6.x)) = tl::mul2(*(float2*)(&(v__8.x)), *(float2*)(&(v__9.x)));
        *(float2*)(&(__6.z)) = tl::mul2(*(float2*)(&(v__8.z)), *(float2*)(&(v__9.z)));
      (reinterpret_cast<__nv_fp8x2_storage_t*>(&__5))[0] = __nv_cvt_float2_to_fp8x2(((float2*)(&__6))[0], __NV_SATFINITE, __NV_E4M3);
      (reinterpret_cast<__nv_fp8x2_storage_t*>(&__5))[1] = __nv_cvt_float2_to_fp8x2(((float2*)(&__6))[1], __NV_SATFINITE, __NV_E4M3);
      *(fp8_e4_4_t*)(y_grad_pt_fragment + (i_1 * 4)) = __5;
    }
    if (((int)blockIdx.x) < num_expand_tokens) {
      *(fp8_e4_8_t*)(x_grad_fp8 + (((((int64_t)((int)blockIdx.x)) * (int64_t)7168) + (((int64_t)k) * (int64_t)512)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8))) = *(fp8_e4_8_t*)(x_grad_fp8_fragment + 0);
      *(fp8_e4_8_t*)(x_grad_fp8 + ((((((int64_t)((int)blockIdx.x)) * (int64_t)7168) + (((int64_t)k) * (int64_t)512)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8)) + (int64_t)3584)) = *(fp8_e4_8_t*)(y_grad_pt_fragment + 0);
    }
  }
  acc[0] = tl::AllReduce<tl::SumOp, 64, 1, 0, tl::NamedBarrier<64>>::run(acc[0], (&(workspace[0])));
  if (0 <= index) {
    if (((int)threadIdx.x) == 0) {
      weight_grad[((int64_t)index)] = acc[0];
    }
  }
}

