// TileKernels CUDA dump (generated by scripts/dump_cuda_sources.py)
// Source Python: tile_kernels/quant/swiglu_forward_and_per_token_cast_kernel.py
// JIT factory: get_swiglu_forward_and_per_token_cast_kernel
// prim_func: swiglu_forward_and_per_token_cast_kernel
// Compile args: {"args": [3584, false, false, false, false, "bfloat16", {"custom_clamp_min_value": null, "round_sf": true, "sf_block": [1, 128], "torch_dtype": "torch.float8_e4m3fn", "use_packed_ue8m0": false, "use_tma_aligned_col_major_sf": false}, null], "kwargs": {}}
// Public API: tile_kernels.quant.swiglu_forward_and_per_token_cast
#include <tl_templates/cuda/cuda_fp8.h>
#include <tl_templates/cuda/gemm.h>
#include <tl_templates/cuda/copy.h>
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#include <tl_templates/cuda/debug.h>
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void swiglu_forward_and_per_token_cast_kernel_kernel(fp8_e4_t* __restrict__ out, float* __restrict__ out_sf, const bfloat16_t* __restrict__ x, int num_expanded_tokens, int sf_stride);
extern "C" __global__ void __launch_bounds__(256, 1) swiglu_forward_and_per_token_cast_kernel_kernel(fp8_e4_t* __restrict__ out, float* __restrict__ out_sf, const bfloat16_t* __restrict__ x, int num_expanded_tokens, int sf_stride) {
  int64_t count_silu[1];
  int64_t count_upper[1];
  int64_t count_lower[1];
  bfloat16_t xl_fragment[14];
  bfloat16_t xr_fragment[14];
  float x_fragment_reshaped[14];
  float val_l = 0x0p+0f/*0.000000e+00*/;
  float val_r = 0x0p+0f/*0.000000e+00*/;
  float sf_inv_fragment[7];
  extern __shared__ __align__(1024) float workspace[];
  float sf = 0x0p+0f/*0.000000e+00*/;
  fp8_e4_t out_fragment[14];
  count_silu[0] = (int64_t)0;
  count_upper[0] = (int64_t)0;
  count_lower[0] = (int64_t)0;
  #pragma unroll
  for (int i = 0; i < 7; ++i) {
    *(uint1*)(xl_fragment + (i * 2)) = *(uint1*)(x + (((((int64_t)((int)blockIdx.x)) * (int64_t)7168) + (((int64_t)i) * (int64_t)512)) + (((int64_t)((int)threadIdx.x)) * (int64_t)2)));
    *(uint1*)(xr_fragment + (i * 2)) = *(uint1*)(x + ((((((int64_t)((int)blockIdx.x)) * (int64_t)7168) + (((int64_t)i) * (int64_t)512)) + (((int64_t)((int)threadIdx.x)) * (int64_t)2)) + (int64_t)3584));
  }
  #pragma unroll
  for (int i_1 = 0; i_1 < 14; ++i_1) {
    val_l = ((float)xl_fragment[i_1]);
    val_r = ((float)xr_fragment[i_1]);
    float val = ((val_l / (0x1p+0f/*1.000000e+00*/ + expf((val_l * -0x1p+0f/*-1.000000e+00*/)))) * val_r);
    x_fragment_reshaped[i_1] = val;
  }
  __syncthreads();
  #pragma unroll
  for (int i_2 = 0; i_2 < 7; ++i_2) {
    sf_inv_fragment[i_2] = 0x0p+0f/*0.000000e+00*/;
    #pragma unroll
    for (int rv = 0; rv < 2; ++rv) {
      sf_inv_fragment[i_2] = max(sf_inv_fragment[i_2], fabsf(x_fragment_reshaped[((i_2 * 2) + rv)]));
    }
    sf_inv_fragment[i_2] = tl::AllReduce<tl::MaxOp, 64, 1, 0, tl::NamedBarrier<256>>::run(sf_inv_fragment[i_2], (&(workspace[0])));
  }
  #pragma unroll
  for (int i_3 = 0; i_3 < 7; ++i_3) {
    float amax = sf_inv_fragment[i_3];
    float clamped_amax = max(amax, 0x1.a36e2eb1c432dp-14f/*1.000000e-04*/);
    sf = (clamped_amax / 0x1.cp+8f/*4.480000e+02*/);
    float _reinterpret_tmp = sf;
    uint bits = (*(uint *)(&(_reinterpret_tmp)));
    uint exp_sf = ((((bits - (uint)1) >> (uint)23) + (uint)1) - (uint)127);
    uint v_ = ((uint)127 - exp_sf) << (uint)23;
    float sf_inv = (*(float *)(&(v_)));
    uint v__1 = ((uint)127 + exp_sf) << (uint)23;
    float sf_1 = (*(float *)(&(v__1)));
    out_sf[(((((int64_t)i_3) * (int64_t)4) + (((int64_t)((int)threadIdx.x)) >> (int64_t)6)) + (((int64_t)((int)blockIdx.x)) * ((int64_t)sf_stride)))] = sf_1;
    sf_inv_fragment[i_3] = sf_inv;
  }
  #pragma unroll
  for (int i_4 = 0; i_4 < 7; ++i_4) {
    fp8_e4_2_t __1;
    float2 __2;
      float2 v__2 = *(float2*)(x_fragment_reshaped + (i_4 * 2));
      float2 v__3 = make_float2(sf_inv_fragment[i_4], sf_inv_fragment[i_4]);
      *(float2*)(&(__2.x)) = tl::mul2(*(float2*)(&(v__2.x)), *(float2*)(&(v__3.x)));
    (reinterpret_cast<__nv_fp8x2_storage_t*>(&__1))[0] = __nv_cvt_float2_to_fp8x2(((float2*)(&__2))[0], __NV_SATFINITE, __NV_E4M3);
    *(fp8_e4_2_t*)(out_fragment + (i_4 * 2)) = __1;
  }
  #pragma unroll
  for (int i_5 = 0; i_5 < 7; ++i_5) {
    *(fp8_e4_2_t*)(out + (((((int64_t)((int)blockIdx.x)) * (int64_t)3584) + (((int64_t)i_5) * (int64_t)512)) + (((int64_t)((int)threadIdx.x)) * (int64_t)2))) = *(fp8_e4_2_t*)(out_fragment + (i_5 * 2));
  }
}

