// TileKernels CUDA dump (generated by scripts/dump_cuda_sources.py)
// Source Python: tile_kernels/moe/aux_fi_kernel.py
// JIT factory: get_aux_fi_kernel
// prim_func: aux_fi_kernel
// Compile args: {"args": [6, 72, 188], "kwargs": {}}
// Public API: tile_kernels.moe.aux_fi
#include <tl_templates/cuda/gemm.h>
#include <tl_templates/cuda/copy.h>
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#include <tl_templates/cuda/debug.h>
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void aux_fi_kernel_kernel(float* __restrict__ out, const int64_t* __restrict__ topk_idx, int num_aux_topk, int num_tokens);
extern "C" __global__ void __launch_bounds__(128, 1) aux_fi_kernel_kernel(float* __restrict__ out, const int64_t* __restrict__ topk_idx, int num_aux_topk, int num_tokens) {
  extern __shared__ __align__(1024) int out_shared[];
  out_shared[((int)threadIdx.x)] = 0;
  __syncthreads();
  for (int _tmp = 0; _tmp < ((((num_tokens + 48127) - ((int)threadIdx.x)) - (((int)blockIdx.x) * 128)) / 48128); ++_tmp) {
    #pragma unroll
    for (int j = 0; j < 6; ++j) {
      int expert_idx = ((int)topk_idx[((((((int64_t)_tmp) * (int64_t)288768) + (((int64_t)((int)blockIdx.x)) * (int64_t)768)) + (((int64_t)((int)threadIdx.x)) * (int64_t)6)) + ((int64_t)j))]);
      bool condition = ((-1 <= expert_idx) && (expert_idx < 72));
      device_assert_with_msg(condition, "\n  at aux_fi_kernel.py:37 in aux_fi_kernel\n");
      if (0 <= expert_idx) {
        AtomicAdd((&(out_shared[expert_idx])), 1);
      }
    }
  }
  __syncthreads();
  for (int _tmp_1 = 0; _tmp_1 < ((199 - ((int)threadIdx.x)) >> 7); ++_tmp_1) {
    if (0 < out_shared[((_tmp_1 * 128) + ((int)threadIdx.x))]) {
      AtomicAdd((&(out[((_tmp_1 * 128) + ((int)threadIdx.x))])), (((float)(out_shared[((_tmp_1 * 128) + ((int)threadIdx.x))] * 72)) / ((float)(num_tokens * num_aux_topk))));
    }
  }
}

