// TileKernels CUDA dump (generated by scripts/dump_cuda_sources.py)
// Source Python: tile_kernels/moe/expand_to_fused_kernel.py
// JIT factory: get_expand_to_fused_kernel
// prim_func: expand_to_fused_kernel
// Compile args: {"args": [7168, 6, 128, false, false, "float8_e4m3", "float32"], "kwargs": {}}
// Public API: tile_kernels.moe.expand_to_fused_with_sf
#include <tl_templates/cuda/cuda_fp8.h>
#include <tl_templates/cuda/gemm.h>
#include <tl_templates/cuda/copy.h>
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#include <tl_templates/cuda/debug.h>
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void expand_to_fused_kernel_kernel(fp8_e4_t* __restrict__ expanded_x, float* __restrict__ expanded_x_sf, const int* __restrict__ pos_to_expert, const int* __restrict__ token_topk_to_pos, const fp8_e4_t* __restrict__ x, const float* __restrict__ x_sf, int num_expanded_tokens, int num_tokens, int sf_stride);
extern "C" __global__ void __launch_bounds__(64, 1) expand_to_fused_kernel_kernel(fp8_e4_t* __restrict__ expanded_x, float* __restrict__ expanded_x_sf, const int* __restrict__ pos_to_expert, const int* __restrict__ token_topk_to_pos, const fp8_e4_t* __restrict__ x, const float* __restrict__ x_sf, int num_expanded_tokens, int num_tokens, int sf_stride) {
  int pos_local[6];
  fp8_e4_t x_fragment[112];
  float x_sf_fragment[1];
  if (((int)blockIdx.x) < num_expanded_tokens) {
    if (pos_to_expert[((int64_t)((int)blockIdx.x))] < 0) {
      #pragma unroll
      for (int i = 0; i < 7; ++i) {
        fp8_e4_t broadcast_var = fp8_e4_t(0x0p+0f/*0.000000e+00*/);
        *(fp8_e4_16_t*)(expanded_x + (((((int64_t)((int)blockIdx.x)) * (int64_t)7168) + (((int64_t)i) * (int64_t)1024)) + (((int64_t)((int)threadIdx.x)) * (int64_t)16))) = make_fp8_e4_16_t(broadcast_var, broadcast_var, broadcast_var, broadcast_var, broadcast_var, broadcast_var, broadcast_var, broadcast_var, broadcast_var, broadcast_var, broadcast_var, broadcast_var, broadcast_var, broadcast_var, broadcast_var, broadcast_var);
      }
      if (((int)threadIdx.x) < 56) {
        expanded_x_sf[((((int64_t)((int)blockIdx.x)) * ((int64_t)sf_stride)) + ((int64_t)((int)threadIdx.x)))] = 0x0p+0f/*0.000000e+00*/;
      }
    }
  }
  if (num_tokens <= ((int)blockIdx.x)) {
    return;
  }
  for (int i_1 = 0; i_1 < 3; ++i_1) {
    *(int2*)(pos_local + (i_1 * 2)) = *(int2*)(token_topk_to_pos + ((((int64_t)((int)blockIdx.x)) * (int64_t)6) + (((int64_t)i_1) * (int64_t)2)));
  }
  #pragma unroll
  for (int i_2 = 0; i_2 < 7; ++i_2) {
    *(fp8_e4_16_t*)(x_fragment + (i_2 * 16)) = *(fp8_e4_16_t*)(x + (((((int64_t)((int)blockIdx.x)) * (int64_t)7168) + (((int64_t)i_2) * (int64_t)1024)) + (((int64_t)((int)threadIdx.x)) * (int64_t)16)));
  }
  if (((int)threadIdx.x) < 56) {
    x_sf_fragment[0] = x_sf[((((int64_t)((int)blockIdx.x)) * (int64_t)56) + ((int64_t)((int)threadIdx.x)))];
  }
  for (int k = 0; k < 6; ++k) {
    if (0 <= pos_local[k]) {
      #pragma unroll
      for (int i_3 = 0; i_3 < 7; ++i_3) {
        *(fp8_e4_16_t*)(expanded_x + (((((int64_t)pos_local[((int64_t)k)]) * (int64_t)7168) + (((int64_t)i_3) * (int64_t)1024)) + (((int64_t)((int)threadIdx.x)) * (int64_t)16))) = *(fp8_e4_16_t*)(x_fragment + (i_3 * 16));
      }
      if (((int)threadIdx.x) < 56) {
        expanded_x_sf[((((int64_t)pos_local[((int64_t)k)]) * ((int64_t)sf_stride)) + ((int64_t)((int)threadIdx.x)))] = x_sf_fragment[0];
      }
    }
  }
}

