// TileKernels CUDA dump (generated by scripts/dump_cuda_sources.py)
// Source Python: tile_kernels/moe/get_fused_mapping_kernel.py
// JIT factory: get_get_fused_mapping_kernel
// prim_func: get_fused_mapping_kernel
// Compile args: {"args": [72, 6, 128, 188], "kwargs": {}}
// Public API: tile_kernels.moe.get_fused_mapping
#include <cooperative_groups.h>
#include <tl_templates/cuda/gemm.h>
#include <tl_templates/cuda/copy.h>
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#include <tl_templates/cuda/debug.h>
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void get_fused_mapping_kernel_kernel(int* __restrict__ expert_end, int* __restrict__ expert_start, int* __restrict__ num_experts_per_sm, int* __restrict__ num_tokens_per_expert, int* __restrict__ pos_to_expert, int* __restrict__ pos_to_token, int* __restrict__ pos_to_token_topk, int* __restrict__ token_topk_to_pos_1d, const int64_t* __restrict__ topk_idx_1d, int num_expanded_tokens, int num_tokens);
extern "C" __global__ void __launch_bounds__(256, 1) get_fused_mapping_kernel_kernel(int* __restrict__ expert_end, int* __restrict__ expert_start, int* __restrict__ num_experts_per_sm, int* __restrict__ num_tokens_per_expert, int* __restrict__ pos_to_expert, int* __restrict__ pos_to_token, int* __restrict__ pos_to_token_topk, int* __restrict__ token_topk_to_pos_1d, const int64_t* __restrict__ topk_idx_1d, int num_expanded_tokens, int num_tokens) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  int start = 0;
  int end = 0;
  int expert_num_elements = 0;
  int prefix_expert_num_elements = 0;
  int expert_num_elements_aligned = 0;
  if (((int)threadIdx.x) < 72) {
    ((int*)buf_dyn_shmem)[(((int)threadIdx.x) + 256)] = 0;
    ((int*)buf_dyn_shmem)[(((int)threadIdx.x) + 256)] = 0;
  }
  for (int _tmp = 0; _tmp < ((103 - (((int)threadIdx.x) & 31)) >> 5); ++_tmp) {
    ((int*)buf_dyn_shmem)[(((((((int)threadIdx.x) >> 5) * 72) + (_tmp * 32)) + (((int)threadIdx.x) & 31)) + 328)] = 0;
  }
  __syncwarp();
  for (int _tmp_1 = 0; _tmp_1 < ((((num_expanded_tokens + 48127) - ((int)threadIdx.x)) - (((int)blockIdx.x) * 256)) / 48128); ++_tmp_1) {
    pos_to_token[(((((int64_t)_tmp_1) * (int64_t)48128) + (((int64_t)((int)blockIdx.x)) * (int64_t)256)) + ((int64_t)((int)threadIdx.x)))] = -1;
    pos_to_token_topk[(((((int64_t)_tmp_1) * (int64_t)48128) + (((int64_t)((int)blockIdx.x)) * (int64_t)256)) + ((int64_t)((int)threadIdx.x)))] = -1;
    pos_to_expert[(((((int64_t)_tmp_1) * (int64_t)48128) + (((int64_t)((int)blockIdx.x)) * (int64_t)256)) + ((int64_t)((int)threadIdx.x)))] = -1;
  }
  for (int _tmp_2 = 0; _tmp_2 < (((((num_tokens * 6) + 48127) - ((int)threadIdx.x)) - (((int)blockIdx.x) * 256)) / 48128); ++_tmp_2) {
    token_topk_to_pos_1d[(((((int64_t)_tmp_2) * (int64_t)48128) + (((int64_t)((int)blockIdx.x)) * (int64_t)256)) + ((int64_t)((int)threadIdx.x)))] = -1;
  }
  start = ((((((int)blockIdx.x) * 8) + (((int)threadIdx.x) >> 5)) * (((num_tokens * 3) + 24063) / 24064)) * 32);
  end = min((((((num_tokens * 3) + 24063) / 24064) * 32) + start), (num_tokens * 6));
  for (int _tmp_3 = 0; _tmp_3 < ((((end + 31) - start) - (((int)threadIdx.x) & 31)) >> 5); ++_tmp_3) {
    int i = (((_tmp_3 * 32) + start) + (((int)threadIdx.x) & 31));
    int64_t expert_idx = topk_idx_1d[((int64_t)i)];
    if (expert_idx != (int64_t)-1) {
      AtomicAdd((&(((int*)buf_dyn_shmem)[((((((int64_t)((int)threadIdx.x)) >> (int64_t)5) * (int64_t)72) + expert_idx) + (int64_t)328)])), 1);
    }
  }
  __syncthreads();
  if (((int)threadIdx.x) < 72) {
    #pragma unroll
    for (int i_1 = 0; i_1 < 7; ++i_1) {
      ((int*)buf_dyn_shmem)[(((i_1 * 72) + ((int)threadIdx.x)) + 400)] = (((int*)buf_dyn_shmem)[(((i_1 * 72) + ((int)threadIdx.x)) + 400)] + ((int*)buf_dyn_shmem)[(((i_1 * 72) + ((int)threadIdx.x)) + 328)]);
    }
    num_experts_per_sm[((((int)blockIdx.x) * 72) + ((int)threadIdx.x))] = ((int*)buf_dyn_shmem)[(((int)threadIdx.x) + 832)];
  }
  cooperative_groups::this_grid().sync();
  if (((int)threadIdx.x) < 72) {
    for (int i_2 = 0; i_2 < 188; ++i_2) {
      int num = num_experts_per_sm[((i_2 * 72) + ((int)threadIdx.x))];
      expert_num_elements = (expert_num_elements + num);
      if (i_2 < ((int)blockIdx.x)) {
        prefix_expert_num_elements = (prefix_expert_num_elements + num);
      }
    }
    expert_num_elements_aligned = (((expert_num_elements + 127) >> 7) * 128);
    ((int*)buf_dyn_shmem)[((int)threadIdx.x)] = expert_num_elements_aligned;
  }
  __syncthreads();
  tl::CumSum1D<256, false>::run((&(((int*)buf_dyn_shmem)[0])), (&(((int*)buf_dyn_shmem)[0])), 256);
  __syncthreads();
  int exclusive_prefix = (((int*)buf_dyn_shmem)[((int)threadIdx.x)] - expert_num_elements_aligned);
  if (((int)threadIdx.x) < 72) {
    #pragma unroll
    for (int i_3 = 0; i_3 < 8; ++i_3) {
      ((int*)buf_dyn_shmem)[(((i_3 * 72) + ((int)threadIdx.x)) + 328)] = ((((int*)buf_dyn_shmem)[(((i_3 * 72) + ((int)threadIdx.x)) + 328)] + prefix_expert_num_elements) + exclusive_prefix);
    }
    if (((int)blockIdx.x) == 0) {
      num_tokens_per_expert[((int)threadIdx.x)] = expert_num_elements_aligned;
      expert_start[((int)threadIdx.x)] = exclusive_prefix;
      expert_end[((int)threadIdx.x)] = (exclusive_prefix + expert_num_elements_aligned);
    }
  }
  __syncthreads();
  start = ((((((int)blockIdx.x) * 8) + (((int)threadIdx.x) >> 5)) * (((num_tokens * 3) + 24063) / 24064)) * 32);
  end = min((((((num_tokens * 3) + 24063) / 24064) * 32) + start), (num_tokens * 6));
  int aligned_end = (((end + 31) >> 5) * 32);
  uint lane_mask = ((((uint)(1 << (((int)threadIdx.x) & 31))) + ((uint)(1 << (((int)threadIdx.x) & 31)))) - (uint)1);
  uint lane_mask_rev = (~lane_mask);
  for (int _tmp_4 = 0; _tmp_4 < ((((aligned_end + 31) - start) - (((int)threadIdx.x) & 31)) >> 5); ++_tmp_4) {
    int i_4 = (((_tmp_4 * 32) + start) + (((int)threadIdx.x) & 31));
    int expert_idx_1 = ((i_4 < (num_tokens * 6)) ? ((int)topk_idx_1d[((int64_t)i_4)]) : -1);
    uint mask = __match_any_sync((int64_t)4294967295, expert_idx_1);
    uint count = __popc((mask & lane_mask));
    if ((i_4 < (num_tokens * 6)) && (0 <= expert_idx_1)) {
      int prefix_count = ((int*)buf_dyn_shmem)[((((((int)threadIdx.x) >> 5) * 72) + expert_idx_1) + 328)];
      uint pos = (((uint)prefix_count) - count);
      if ((mask & lane_mask_rev) == (uint)0) {
        ((int*)buf_dyn_shmem)[((((((int)threadIdx.x) >> 5) * 72) + expert_idx_1) + 328)] = ((int)pos);
      }
      token_topk_to_pos_1d[((int64_t)i_4)] = ((int)pos);
      pos_to_expert[pos] = expert_idx_1;
      pos_to_token[pos] = (i_4 / 6);
      pos_to_token_topk[pos] = i_4;
    }
    __syncwarp();
  }
}

