// TileKernels CUDA dump (generated by scripts/dump_cuda_sources.py)
// Source Python: tile_kernels/moe/inplace_unique_group_indices_kernel.py
// JIT factory: get_inplace_unique_group_indices_kernel
// prim_func: inplace_unique_group_indices_kernel
// Compile args: {"args": [6, 64, 188], "kwargs": {}}
// Public API: tile_kernels.moe.inplace_unique_group_indices
#include <tl_templates/cuda/gemm.h>
#include <tl_templates/cuda/copy.h>
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#include <tl_templates/cuda/debug.h>
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void inplace_unique_group_indices_kernel_kernel(int64_t* __restrict__ group_indices, int num_tokens);
extern "C" __global__ void __launch_bounds__(128, 1) inplace_unique_group_indices_kernel_kernel(int64_t* __restrict__ group_indices, int num_tokens) {
  uint64_t group_sel[2];
  for (int _tmp = 0; _tmp < ((((num_tokens + 48127) - ((int)threadIdx.x)) - (((int)blockIdx.x) * 128)) / 48128); ++_tmp) {
    group_sel[0] = (uint64_t)0;
    #pragma unroll
    for (int j = 0; j < 6; ++j) {
      int64_t group_idx = group_indices[((((((int64_t)_tmp) * (int64_t)288768) + (((int64_t)((int)blockIdx.x)) * (int64_t)768)) + (((int64_t)((int)threadIdx.x)) * (int64_t)6)) + ((int64_t)j))];
      bool condition = (group_idx < (int64_t)64);
      device_assert_with_msg(condition, "\n  at inplace_unique_group_indices_kernel.py:37 in inplace_unique_group_indices_kernel\n");
      uint64_t mask = (((int64_t)0 <= group_idx) ? ((uint64_t)1 << ((uint64_t)group_idx)) : (uint64_t)0);
      uint64_t found = ((mask & group_sel[0]) | ((uint64_t)0 & group_sel[1]));
      group_sel[0] = (group_sel[0] | mask);
      group_sel[1] = (group_sel[1] | (uint64_t)0);
      int64_t v_ = (int64_t)-1;
      tl::store_global_64_conditional((&(group_indices[((((((int64_t)_tmp) * (int64_t)288768) + (((int64_t)((int)blockIdx.x)) * (int64_t)768)) + (((int64_t)((int)threadIdx.x)) * (int64_t)6)) + ((int64_t)j))])), (*(uint2 *)(&(v_))), found);
    }
  }
}

