// TileKernels CUDA dump (generated by scripts/dump_cuda_sources.py)
// Source Python: tile_kernels/moe/mask_indices_by_tp_kernel.py
// JIT factory: get_mask_indices_by_tp_kernel
// prim_func: mask_indices_by_tp_kernel
// Compile args: {"args": [6, "int64"], "kwargs": {}}
// Public API: tile_kernels.moe.mask_indices_by_tp
#include <tl_templates/cuda/gemm.h>
#include <tl_templates/cuda/copy.h>
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#include <tl_templates/cuda/debug.h>
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void mask_indices_by_tp_kernel_kernel(const int64_t* __restrict__ indices_1d, int64_t* __restrict__ masked_indices_1d, int num_tokens, int num_tp_ranks, int per_dp, int per_gpu, int tp_rank);
extern "C" __global__ void __launch_bounds__(128, 1) mask_indices_by_tp_kernel_kernel(const int64_t* __restrict__ indices_1d, int64_t* __restrict__ masked_indices_1d, int num_tokens, int num_tp_ranks, int per_dp, int per_gpu, int tp_rank) {
  int64_t value = (int64_t)0;
  if (((((int)blockIdx.x) * 128) + ((int)threadIdx.x)) < (num_tokens * 6)) {
    value = indices_1d[((((int64_t)((int)blockIdx.x)) * (int64_t)128) + ((int64_t)((int)threadIdx.x)))];
    if ((value < (int64_t)0) || (((value / ((int64_t)per_gpu)) % ((int64_t)num_tp_ranks)) != ((int64_t)tp_rank))) {
      masked_indices_1d[((((int64_t)((int)blockIdx.x)) * (int64_t)128) + ((int64_t)((int)threadIdx.x)))] = (int64_t)-1;
    } else {
      value = (value - ((int64_t)(tp_rank * per_gpu)));
      int64_t dp_rank = (value / ((int64_t)per_dp));
      value = (value - (dp_rank * (((int64_t)per_dp) - ((int64_t)per_gpu))));
      masked_indices_1d[((((int64_t)((int)blockIdx.x)) * (int64_t)128) + ((int64_t)((int)threadIdx.x)))] = ((value < (int64_t)0) ? (int64_t)-1 : value);
    }
  }
}

