// TileKernels CUDA dump (generated by scripts/dump_cuda_sources.py)
// Source Python: tile_kernels/moe/normalize_weight_kernel.py
// JIT factory: get_normalize_weight_kernel
// prim_func: normalize_weight_kernel
// Compile args: {"args": [6], "kwargs": {}}
// Public API: tile_kernels.moe.normalize_weight
#include <tl_templates/cuda/gemm.h>
#include <tl_templates/cuda/copy.h>
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#include <tl_templates/cuda/debug.h>
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void normalize_weight_kernel_kernel(float* __restrict__ denominator, float* __restrict__ normalized_weights, const float* __restrict__ topk_weights, int num_tokens);
extern "C" __global__ void __launch_bounds__(128, 1) normalize_weight_kernel_kernel(float* __restrict__ denominator, float* __restrict__ normalized_weights, const float* __restrict__ topk_weights, int num_tokens) {
  float weights_local[6];
  float sum = 0x1.79ca10c924223p-67f/*1.000000e-20*/;
  if (((((int)blockIdx.x) * 128) + ((int)threadIdx.x)) < num_tokens) {
    for (int i = 0; i < 3; ++i) {
      *(float2*)(weights_local + (i * 2)) = *(float2*)(topk_weights + (((((int64_t)((int)blockIdx.x)) * (int64_t)768) + (((int64_t)((int)threadIdx.x)) * (int64_t)6)) + (((int64_t)i) * (int64_t)2)));
    }
    #pragma unroll
    for (int i_1 = 0; i_1 < 6; ++i_1) {
      sum = (sum + weights_local[i_1]);
    }
    denominator[((((int64_t)((int)blockIdx.x)) * (int64_t)128) + ((int64_t)((int)threadIdx.x)))] = sum;
    for (int i_2 = 0; i_2 < 3; ++i_2) {
      float2 __1;
        float2 v_ = *(float2*)(weights_local + (i_2 * 2));
        float2 v__1 = make_float2(sum, sum);
        __1.x = (v_.x/v__1.x);
        __1.y = (v_.y/v__1.y);
      *(float2*)(normalized_weights + (((((int64_t)((int)blockIdx.x)) * (int64_t)768) + (((int64_t)((int)threadIdx.x)) * (int64_t)6)) + (((int64_t)i_2) * (int64_t)2))) = __1;
    }
  }
}

