// TileKernels CUDA dump (generated by scripts/dump_cuda_sources.py)
// Source Python: tile_kernels/moe/reduce_fused_kernel.py
// JIT factory: get_reduce_fused_kernel
// prim_func: reduce_fused_kernel
// Compile args: {"args": [7168, 6, "bfloat16", "bfloat16", false, true, false], "kwargs": {}}
// Public API: tile_kernels.moe.reduce_fused
#include <tl_templates/cuda/gemm.h>
#include <tl_templates/cuda/copy.h>
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#include <tl_templates/cuda/debug.h>
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void reduce_fused_kernel_kernel(bfloat16_t* __restrict__ out, const int* __restrict__ token_topk_to_pos, const float* __restrict__ topk_weights, const bfloat16_t* __restrict__ x, int num_expanded_tokens, int num_tokens);
extern "C" __global__ void __launch_bounds__(128, 1) reduce_fused_kernel_kernel(bfloat16_t* __restrict__ out, const int* __restrict__ token_topk_to_pos, const float* __restrict__ topk_weights, const bfloat16_t* __restrict__ x, int num_expanded_tokens, int num_tokens) {
  float reduced_fragment[56];
  float topk_weights_local[6];
  int topk_to_pos_local[6];
  float s = 0x0p+0f/*0.000000e+00*/;
  bfloat16_t x_local_cast[8];
  bfloat16_t out_local_cast_1[8];
  #pragma unroll
  for (int i = 0; i < 14; ++i) {
    float broadcast_var = 0x0p+0f/*0.000000e+00*/;
    *(float4*)(reduced_fragment + (i * 4)) = make_float4(broadcast_var, broadcast_var, broadcast_var, broadcast_var);
  }
  #pragma unroll
  for (int i_1 = 0; i_1 < 3; ++i_1) {
    *(float2*)(topk_weights_local + (i_1 * 2)) = *(float2*)(topk_weights + ((((int64_t)((int)blockIdx.x)) * (int64_t)6) + (((int64_t)i_1) * (int64_t)2)));
  }
  #pragma unroll
  for (int i_2 = 0; i_2 < 3; ++i_2) {
    *(int2*)(topk_to_pos_local + (i_2 * 2)) = *(int2*)(token_topk_to_pos + ((((int64_t)((int)blockIdx.x)) * (int64_t)6) + (((int64_t)i_2) * (int64_t)2)));
  }
  #pragma unroll
  for (int k = 0; k < 6; ++k) {
    int pos = topk_to_pos_local[k];
    if (0 <= pos) {
      s = 0x1p+0f/*1.000000e+00*/;
      s = topk_weights_local[k];
      #pragma unroll
      for (int i_3 = 0; i_3 < 7; ++i_3) {
        *(uint4*)(x_local_cast + 0) = *(uint4*)(x + (((((int64_t)pos) * (int64_t)7168) + (((int64_t)i_3) * (int64_t)1024)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8)));
        for (int vec = 0; vec < 2; ++vec) {
          float4 __1;
            float4 __2;
            uint2 v_ = *(uint2*)(x_local_cast + (vec * 4));
            ((float2*)(&__2))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[0]);
            ((float2*)(&__2))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[1]);
            float4 v__1 = make_float4(s, s, s, s);
            float4 v__2 = *(float4*)(reduced_fragment + ((i_3 * 8) + (vec * 4)));
            *(float2*)(&(__1.x)) = tl::fma2(*(float2*)(&(__2.x)), *(float2*)(&(v__1.x)), *(float2*)(&(v__2.x)));
            *(float2*)(&(__1.z)) = tl::fma2(*(float2*)(&(__2.z)), *(float2*)(&(v__1.z)), *(float2*)(&(v__2.z)));
          *(float4*)(reduced_fragment + ((i_3 * 8) + (vec * 4))) = __1;
        }
      }
    }
  }
  #pragma unroll
  for (int i_4 = 0; i_4 < 7; ++i_4) {
    for (int vec_1 = 0; vec_1 < 2; ++vec_1) {
      uint2 __3;
      float4 v__3 = *(float4*)(reduced_fragment + ((i_4 * 8) + (vec_1 * 4)));
      (reinterpret_cast<__nv_bfloat162*>(&__3))[0] = __float22bfloat162_rn(((float2*)(&v__3))[0]);
      (reinterpret_cast<__nv_bfloat162*>(&__3))[1] = __float22bfloat162_rn(((float2*)(&v__3))[1]);
      *(uint2*)(out_local_cast_1 + (vec_1 * 4)) = __3;
    }
    *(uint4*)(out + (((((int64_t)((int)blockIdx.x)) * (int64_t)7168) + (((int64_t)i_4) * (int64_t)1024)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8))) = *(uint4*)(out_local_cast_1 + 0);
  }
}

