// TileKernels CUDA dump (generated by scripts/dump_cuda_sources.py)
// Source Python: tile_kernels/moe/top2_sum_gate_kernel.py
// JIT factory: get_top2_sum_gate_kernel
// prim_func: top2_sum_gate_kernel
// Compile args: {"args": [0, 6, 8, 8, 256, false, false, false, false], "kwargs": {}}
// Public API: tile_kernels.moe.top2_sum_gate
#include <math_constants.h>
#include <tl_templates/cuda/gemm.h>
#include <tl_templates/cuda/copy.h>
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#include <tl_templates/cuda/debug.h>
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void top2_sum_gate_kernel_kernel(const float* __restrict__ bias, const float* __restrict__ logits, int64_t* __restrict__ topk_idx, float* __restrict__ topk_weights, int num_ep_ranks, int num_extra_experts, int num_physical_topk, int num_tokens, int num_tp_ranks, float routed_scaling_factor, int tp_rank);
extern "C" __global__ void __launch_bounds__(32, 1) top2_sum_gate_kernel_kernel(const float* __restrict__ bias, const float* __restrict__ logits, int64_t* __restrict__ topk_idx, float* __restrict__ topk_weights, int num_ep_ranks, int num_extra_experts, int num_physical_topk, int num_tokens, int num_tp_ranks, float routed_scaling_factor, int tp_rank) {
  float logit_max_var = 0x0p+0f/*0.000000e+00*/;
  float logit_sum_var = 0x0p+0f/*0.000000e+00*/;
  int idx_local[8];
  float scores_local[8];
  float bias_local[8];
  extern __shared__ __align__(1024) float scores_wo_bias_shared[];
  int topk_idx_local[6];
  float topk_scores_local[6];
  int other_idx = 0;
  float topk_score_var = 0x0p+0f/*0.000000e+00*/;
  int64_t topk_idx_var = (int64_t)0;
  float topk_sum_var = 0x0p+0f/*0.000000e+00*/;
  logit_max_var = -CUDART_INF_F;
  logit_sum_var = 0x0p+0f/*0.000000e+00*/;
  #pragma unroll
  for (int i = 0; i < 2; ++i) {
    int broadcast_var = -1;
    *(int4*)(idx_local + (i * 4)) = make_int4(broadcast_var, broadcast_var, broadcast_var, broadcast_var);
  }
  #pragma unroll
  for (int i_1 = 0; i_1 < 2; ++i_1) {
    float broadcast_var_1 = -CUDART_INF_F;
    *(float4*)(scores_local + (i_1 * 4)) = make_float4(broadcast_var_1, broadcast_var_1, broadcast_var_1, broadcast_var_1);
  }
  #pragma unroll
  for (int i_2 = 0; i_2 < 2; ++i_2) {
    float broadcast_var_2 = 0x0p+0f/*0.000000e+00*/;
    *(float4*)(bias_local + (i_2 * 4)) = make_float4(broadcast_var_2, broadcast_var_2, broadcast_var_2, broadcast_var_2);
  }
  #pragma unroll
  for (int i_3 = 0; i_3 < 2; ++i_3) {
    *(float4*)(scores_local + (i_3 * 4)) = *(float4*)(logits + (((((int64_t)((int)blockIdx.x)) * (int64_t)256) + (((int64_t)i_3) * (int64_t)128)) + (((int64_t)((int)threadIdx.x)) * (int64_t)4)));
    *(float4*)(bias_local + (i_3 * 4)) = *(float4*)(bias + ((i_3 * 128) + (((int)threadIdx.x) * 4)));
    #pragma unroll
    for (int j = 0; j < 4; ++j) {
      bool condition = isfinite(scores_local[((i_3 * 4) + j)]);
      device_assert_with_msg(condition, "top2_sum_gate input contains nan or inf!\n  at top2_sum_gate_kernel.py:153 in top2_sum_gate_kernel\n");
    }
  }
  #pragma unroll
  for (int i_4 = 0; i_4 < 2; ++i_4) {
    float broadcast_var_3 = 0x1p+0f/*1.000000e+00*/;
    float broadcast_var_4 = 0x1p+0f/*1.000000e+00*/;
    float broadcast_var_5 = 0x0p+0f/*0.000000e+00*/;
    float4 __1;
      float4 v_ = make_float4(broadcast_var_3, broadcast_var_3, broadcast_var_3, broadcast_var_3);
      float4 __2;
        float4 v__1 = make_float4(broadcast_var_4, broadcast_var_4, broadcast_var_4, broadcast_var_4);
        float4 __3;
        float4 __4;
          float4 v__2 = make_float4(broadcast_var_5, broadcast_var_5, broadcast_var_5, broadcast_var_5);
          float4 v__3 = *(float4*)(scores_local + (i_4 * 4));
          *(float2*)(&(__4.x)) = tl::sub2(*(float2*)(&(v__2.x)), *(float2*)(&(v__3.x)));
          *(float2*)(&(__4.z)) = tl::sub2(*(float2*)(&(v__2.z)), *(float2*)(&(v__3.z)));
        __3.x = expf(__4.x);
        __3.y = expf(__4.y);
        __3.z = expf(__4.z);
        __3.w = expf(__4.w);
        *(float2*)(&(__2.x)) = tl::add2(*(float2*)(&(v__1.x)), *(float2*)(&(__3.x)));
        *(float2*)(&(__2.z)) = tl::add2(*(float2*)(&(v__1.z)), *(float2*)(&(__3.z)));
      __1.x = (v_.x/__2.x);
      __1.y = (v_.y/__2.y);
      __1.z = (v_.z/__2.z);
      __1.w = (v_.w/__2.w);
    *(float4*)(scores_local + (i_4 * 4)) = __1;
    *(float4*)(scores_wo_bias_shared + ((i_4 * 128) + (((int)threadIdx.x) * 4))) = *(float4*)(scores_local + (i_4 * 4));
    float4 __5;
      float4 v__4 = *(float4*)(scores_local + (i_4 * 4));
      float4 v__5 = *(float4*)(bias_local + (i_4 * 4));
      *(float2*)(&(__5.x)) = tl::add2(*(float2*)(&(v__4.x)), *(float2*)(&(v__5.x)));
      *(float2*)(&(__5.z)) = tl::add2(*(float2*)(&(v__4.z)), *(float2*)(&(v__5.z)));
    *(float4*)(scores_local + (i_4 * 4)) = __5;
    *(int4*)(idx_local + (i_4 * 4)) = (make_int4((((i_4 * 128) + (((int)threadIdx.x) * 4)))+(1*0), (((i_4 * 128) + (((int)threadIdx.x) * 4)))+(1*1), (((i_4 * 128) + (((int)threadIdx.x) * 4)))+(1*2), (((i_4 * 128) + (((int)threadIdx.x) * 4)))+(1*3)));
  }
  __syncwarp();
  #pragma unroll
  for (int k = 0; k < 6; ++k) {
    topk_scores_local[k] = -CUDART_INF_F;
    #pragma unroll
    for (int i_5 = 0; i_5 < 8; ++i_5) {
      int condval;
      if ((1 <= k)) {
        condval = topk_idx_local[(k - 1)];
      } else {
        condval = 0;
      }
      if ((0 < k) && (condval == idx_local[i_5])) {
        scores_local[i_5] = -CUDART_INF_F;
      } else {
        if (topk_scores_local[k] < scores_local[i_5]) {
          topk_scores_local[k] = scores_local[i_5];
          topk_idx_local[k] = idx_local[i_5];
        }
      }
    }
    #pragma unroll
    for (int i_6 = 0; i_6 < 5; ++i_6) {
      float other_score = __shfl_xor_sync((uint)4294967295, topk_scores_local[k], (1 << i_6), 32);
      other_idx = __shfl_xor_sync((uint)4294967295, topk_idx_local[k], (1 << i_6), 32);
      if ((topk_scores_local[k] < other_score) || ((other_score == topk_scores_local[k]) && (other_idx < topk_idx_local[k]))) {
        topk_scores_local[k] = other_score;
        topk_idx_local[k] = other_idx;
      }
    }
  }
  topk_score_var = 0x0p+0f/*0.000000e+00*/;
  if (((int)threadIdx.x) < 6) {
    topk_idx_var = ((int64_t)topk_idx_local[((int)threadIdx.x)]);
    float condval_1;
    if ((((int64_t)0 <= topk_idx_var) && (topk_idx_var < (int64_t)256))) {
      condval_1 = scores_wo_bias_shared[topk_idx_var];
    } else {
      condval_1 = 0x0p+0f/*0.000000e+00*/;
    }
    topk_score_var = condval_1;
  }
  topk_sum_var = 0x1.79ca10c924223p-67f/*1.000000e-20*/;
  #pragma unroll
  for (int i_7 = 0; i_7 < 6; ++i_7) {
    topk_sum_var = (topk_sum_var + __shfl_sync((uint)4294967295, topk_score_var, i_7, 32));
  }
  bool condition_1 = (num_physical_topk <= 32);
  device_assert_with_msg(condition_1, "\n  at top2_sum_gate_kernel.py:268 in top2_sum_gate_kernel\n");
  if (((int)threadIdx.x) < 6) {
    bool condition_2 = ((int64_t)0 <= topk_idx_var);
    device_assert_with_msg(condition_2, "\n  at top2_sum_gate_kernel.py:273 in top2_sum_gate_kernel\n");
    topk_score_var = ((topk_score_var / topk_sum_var) * routed_scaling_factor);
  } else {
    if (((int)threadIdx.x) < num_physical_topk) {
      topk_score_var = 0x1p+0f/*1.000000e+00*/;
      topk_idx_var = (((int64_t)((int)threadIdx.x)) + (int64_t)250);
    }
  }
  if (((int)threadIdx.x) < num_physical_topk) {
    int rmod = ((num_extra_experts + 256) % num_ep_ranks);
    int rdiv = ((num_extra_experts + 256) / num_ep_ranks);
    int64_t rmod_1 = (topk_idx_var % ((int64_t)((((0 <= num_ep_ranks) && (0 <= rmod)) || ((num_ep_ranks < 0) && (rmod <= 0))) ? rdiv : (rdiv - 1))));
    int rmod_2 = ((num_extra_experts + 256) % num_ep_ranks);
    int rdiv_1 = ((num_extra_experts + 256) / num_ep_ranks);
    int64_t rdiv_2 = (topk_idx_var / ((int64_t)((((0 <= num_ep_ranks) && (0 <= rmod_2)) || ((num_ep_ranks < 0) && (rmod_2 <= 0))) ? rdiv_1 : (rdiv_1 - 1))));
    int rmod_3 = ((num_extra_experts + 256) % num_ep_ranks);
    int rdiv_3 = ((num_extra_experts + 256) / num_ep_ranks);
    int rmod_4 = ((num_extra_experts + 256) % num_ep_ranks);
    int rdiv_4 = ((num_extra_experts + 256) / num_ep_ranks);
    int64_t dst_ep_rank = (((((int64_t)0 <= ((int64_t)((((0 <= num_ep_ranks) && (0 <= rmod_3)) || ((num_ep_ranks < 0) && (rmod_3 <= 0))) ? rdiv_3 : (rdiv_3 - 1)))) && ((int64_t)0 <= rmod_1)) || ((((int64_t)((((0 <= num_ep_ranks) && (0 <= rmod_4)) || ((num_ep_ranks < 0) && (rmod_4 <= 0))) ? rdiv_4 : (rdiv_4 - 1))) < (int64_t)0) && (rmod_1 <= (int64_t)0))) ? rdiv_2 : (rdiv_2 - (int64_t)1));
    int64_t rmod_5 = (dst_ep_rank % ((int64_t)num_tp_ranks));
    if ((((((int64_t)0 <= ((int64_t)num_tp_ranks)) && ((int64_t)0 <= rmod_5)) || ((((int64_t)num_tp_ranks) < (int64_t)0) && (rmod_5 <= (int64_t)0))) ? rmod_5 : (rmod_5 + ((int64_t)num_tp_ranks))) != ((int64_t)tp_rank)) {
      topk_idx_var = (int64_t)-1;
    } else {
      int rmod_6 = ((num_extra_experts + 256) % num_ep_ranks);
      int rdiv_5 = ((num_extra_experts + 256) / num_ep_ranks);
      topk_idx_var = (topk_idx_var - ((int64_t)(tp_rank * ((((0 <= num_ep_ranks) && (0 <= rmod_6)) || ((num_ep_ranks < 0) && (rmod_6 <= 0))) ? rdiv_5 : (rdiv_5 - 1)))));
      int rmod_7 = ((num_extra_experts + 256) % num_ep_ranks);
      int rdiv_6 = ((num_extra_experts + 256) / num_ep_ranks);
      int64_t rmod_8 = (topk_idx_var % ((int64_t)(((((0 <= num_ep_ranks) && (0 <= rmod_7)) || ((num_ep_ranks < 0) && (rmod_7 <= 0))) ? rdiv_6 : (rdiv_6 - 1)) * num_tp_ranks)));
      int rmod_9 = ((num_extra_experts + 256) % num_ep_ranks);
      int rdiv_7 = ((num_extra_experts + 256) / num_ep_ranks);
      int64_t rdiv_8 = (topk_idx_var / ((int64_t)(((((0 <= num_ep_ranks) && (0 <= rmod_9)) || ((num_ep_ranks < 0) && (rmod_9 <= 0))) ? rdiv_7 : (rdiv_7 - 1)) * num_tp_ranks)));
      int rmod_10 = ((num_extra_experts + 256) % num_ep_ranks);
      int rdiv_9 = ((num_extra_experts + 256) / num_ep_ranks);
      int rmod_11 = ((num_extra_experts + 256) % num_ep_ranks);
      int rdiv_10 = ((num_extra_experts + 256) / num_ep_ranks);
      int64_t dst_dp_rank = (((((int64_t)0 <= ((int64_t)(((((0 <= num_ep_ranks) && (0 <= rmod_10)) || ((num_ep_ranks < 0) && (rmod_10 <= 0))) ? rdiv_9 : (rdiv_9 - 1)) * num_tp_ranks))) && ((int64_t)0 <= rmod_8)) || ((((int64_t)(((((0 <= num_ep_ranks) && (0 <= rmod_11)) || ((num_ep_ranks < 0) && (rmod_11 <= 0))) ? rdiv_10 : (rdiv_10 - 1)) * num_tp_ranks)) < (int64_t)0) && (rmod_8 <= (int64_t)0))) ? rdiv_8 : (rdiv_8 - (int64_t)1));
      int rmod_12 = ((num_extra_experts + 256) % num_ep_ranks);
      int rdiv_11 = ((num_extra_experts + 256) / num_ep_ranks);
      int rmod_13 = ((num_extra_experts + 256) % num_ep_ranks);
      int rdiv_12 = ((num_extra_experts + 256) / num_ep_ranks);
      topk_idx_var = ((topk_idx_var + (dst_dp_rank * ((int64_t)((((0 <= num_ep_ranks) && (0 <= rmod_12)) || ((num_ep_ranks < 0) && (rmod_12 <= 0))) ? rdiv_11 : (rdiv_11 - 1))))) - (dst_dp_rank * ((int64_t)(((((0 <= num_ep_ranks) && (0 <= rmod_13)) || ((num_ep_ranks < 0) && (rmod_13 <= 0))) ? rdiv_12 : (rdiv_12 - 1)) * num_tp_ranks))));
      int64_t condval_2;
      if ((topk_idx_var < (int64_t)0)) {
        condval_2 = (int64_t)-1;
      } else {
        condval_2 = topk_idx_var;
      }
      topk_idx_var = condval_2;
    }
    topk_idx[((((int64_t)((int)blockIdx.x)) * ((int64_t)num_physical_topk)) + ((int64_t)((int)threadIdx.x)))] = topk_idx_var;
    topk_weights[((((int64_t)((int)blockIdx.x)) * ((int64_t)num_physical_topk)) + ((int64_t)((int)threadIdx.x)))] = topk_score_var;
  }
}

