// TileKernels CUDA dump (generated by scripts/dump_cuda_sources.py)
// Source Python: tile_kernels/moe/topk_sum_and_topk_group_idx_kernel.py
// JIT factory: get_topk_sum_and_topk_group_idx_kernel
// prim_func: topk_sum_and_topk_group_idx_kernel
// Compile args: {"args": [8, 32, 8, 2], "kwargs": {}}
// Public API: tile_kernels.moe.topk_sum_and_topk_group_idx
#include <math_constants.h>
#include <tl_templates/cuda/gemm.h>
#include <tl_templates/cuda/copy.h>
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#include <tl_templates/cuda/debug.h>
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void topk_sum_and_topk_group_idx_kernel_kernel(int64_t* __restrict__ group_topk_idx, const float* __restrict__ scores, int num_tokens);
extern "C" __global__ void __launch_bounds__(32, 1) topk_sum_and_topk_group_idx_kernel_kernel(int64_t* __restrict__ group_topk_idx, const float* __restrict__ scores, int num_tokens) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  float top1_var = 0x0p+0f/*0.000000e+00*/;
  float top2_var = 0x0p+0f/*0.000000e+00*/;
  float topk_sum_var = 0x0p+0f/*0.000000e+00*/;
  float scores_vec_local[4];
  int count_var = 0;
  #pragma unroll
  for (int i = 0; i < 2; ++i) {
    *(float4*)(((float*)buf_dyn_shmem) + ((i * 128) + (((int)threadIdx.x) * 4))) = *(float4*)(scores + (((((int64_t)((int)blockIdx.x)) * (int64_t)256) + (((int64_t)i) * (int64_t)128)) + (((int64_t)((int)threadIdx.x)) * (int64_t)4)));
  }
  __syncwarp();
  top1_var = -CUDART_INF_F;
  top2_var = -CUDART_INF_F;
  topk_sum_var = -CUDART_INF_F;
  if (((int)threadIdx.x) < 8) {
    #pragma unroll
    for (int i_1 = 0; i_1 < 8; ++i_1) {
      for (int j = 0; j < 4; ++j) {
        scores_vec_local[j] = ((float*)buf_dyn_shmem)[(((((int)threadIdx.x) * 32) + (((i_1 + ((int)threadIdx.x)) & 7) * 4)) + j)];
        if (top1_var < scores_vec_local[j]) {
          top2_var = top1_var;
          top1_var = scores_vec_local[j];
        } else {
          if (top2_var < scores_vec_local[j]) {
            top2_var = scores_vec_local[j];
          }
        }
      }
    }
    topk_sum_var = (top1_var + top2_var);
  }
  #pragma unroll
  for (int i_2 = 0; i_2 < 8; ++i_2) {
    float other_top2_sum = __shfl_sync((uint)4294967295, topk_sum_var, i_2, 32);
    if ((topk_sum_var < other_top2_sum) || ((other_top2_sum == topk_sum_var) && (i_2 < ((int)threadIdx.x)))) {
      count_var = (count_var + 1);
    }
  }
  if (count_var < 8) {
    if (0 <= count_var) {
      if (count_var < 8) {
        ((int*)buf_dyn_shmem)[count_var] = ((int)threadIdx.x);
      }
    }
  }
  __syncwarp();
  if (((int)threadIdx.x) < 8) {
    group_topk_idx[((((int64_t)((int)blockIdx.x)) * (int64_t)8) + ((int64_t)((int)threadIdx.x)))] = ((int64_t)((int*)buf_dyn_shmem)[((int)threadIdx.x)]);
  }
}

