// TileKernels CUDA dump (generated by scripts/dump_cuda_sources.py)
// Source Python: tile_kernels/moe/topk_gate_kernel.py
// JIT factory: get_topk_gate_kernel
// prim_func: topk_gate_kernel
// Compile args: {"args": [72, 6], "kwargs": {}}
// Public API: tile_kernels.moe.topk_gate
#include <math_constants.h>
#include <tl_templates/cuda/gemm.h>
#include <tl_templates/cuda/copy.h>
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#include <tl_templates/cuda/debug.h>
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void topk_gate_kernel_kernel(const float* __restrict__ scores, int64_t* __restrict__ topk_idx, int num_tokens);
extern "C" __global__ void __launch_bounds__(32, 1) topk_gate_kernel_kernel(const float* __restrict__ scores, int64_t* __restrict__ topk_idx, int num_tokens) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  float scores_fragment[3];
  int idx_fragment[3];
  float amax_fragment[1];
  int idx_reducer[1];
  #pragma unroll
  for (int i = 0; i < 3; ++i) {
    if (((i * 4) + (((int)threadIdx.x) >> 3)) < 9) {
      scores_fragment[i] = scores[(((((int64_t)((int)blockIdx.x)) * (int64_t)72) + (((int64_t)i) * (int64_t)32)) + ((int64_t)((int)threadIdx.x)))];
    } else {
      scores_fragment[i] = -CUDART_INF_F;
    }
  }
  #pragma unroll
  for (int i_1 = 0; i_1 < 3; ++i_1) {
    idx_fragment[i_1] = ((i_1 * 32) + ((int)threadIdx.x));
  }
  __syncthreads();
  #pragma unroll
  for (int k = 0; k < 6; ++k) {
    amax_fragment[0] = -CUDART_INF_F;
    #pragma unroll
    for (int rv = 0; rv < 3; ++rv) {
      amax_fragment[0] = max(amax_fragment[0], scores_fragment[rv]);
    }
    amax_fragment[0] = tl::AllReduce<tl::MaxOp, 32, 1, 0, tl::NamedBarrier<32>>::run(amax_fragment[0]);
    idx_reducer[0] = 2147483647;
    #pragma unroll
    for (int i_2 = 0; i_2 < 3; ++i_2) {
      if (scores_fragment[i_2] == amax_fragment[0]) {
        idx_reducer[0] = min(idx_reducer[0], idx_fragment[i_2]);
      }
    }
    idx_reducer[0] = tl::AllReduce<tl::MinOp, 32, 1, 0, tl::NamedBarrier<32>>::run(idx_reducer[0], (&(((int*)buf_dyn_shmem)[0])));
    __syncthreads();
    if (((int)threadIdx.x) == 0) {
      ((int*)buf_dyn_shmem)[(k + 32)] = idx_reducer[0];
    }
    #pragma unroll
    for (int i_3 = 0; i_3 < 3; ++i_3) {
      if (idx_fragment[i_3] == idx_reducer[0]) {
        scores_fragment[i_3] = -CUDART_INF_F;
      }
    }
  }
  __syncthreads();
  if (((int)threadIdx.x) < 6) {
    topk_idx[((((int64_t)((int)blockIdx.x)) * (int64_t)6) + ((int64_t)((int)threadIdx.x)))] = ((int64_t)((int*)buf_dyn_shmem)[(((int)threadIdx.x) + 32)]);
  }
}

