// TileKernels CUDA dump (generated by scripts/dump_cuda_sources.py)
// Source Python: tile_kernels/transpose/batched_transpose_kernel.py
// JIT factory: get_batched_transpose_kernel
// prim_func: batched_transpose_kernel
// Compile args: {"args": [0, 0, "bfloat16"], "kwargs": {}}
// Public API: tile_kernels.transpose.transpose
#include <tl_templates/cuda/gemm.h>
#include <tl_templates/cuda/copy.h>
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#include <tl_templates/cuda/debug.h>
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void batched_transpose_kernel_kernel(bfloat16_t* __restrict__ out, const bfloat16_t* __restrict__ x, int num_batches, int shape_x, int shape_y, int stride_x);
extern "C" __global__ void __launch_bounds__(256, 1) batched_transpose_kernel_kernel(bfloat16_t* __restrict__ out, const bfloat16_t* __restrict__ x, int num_batches, int shape_x, int shape_y, int stride_x) {
  extern __shared__ __align__(1024) bfloat16_t out_shared[];
  bfloat16_t tmp[16];
  bfloat16_t tmp_row[4];
  #pragma unroll
  for (int i_ = 0; i_ < 4; ++i_) {
    #pragma unroll
    for (int j = 0; j < 4; ++j) {
      *(uint2*)(tmp_row + 0) = *(uint2*)(x + (((((int64_t)((int)blockIdx.x)) * (int64_t)128) + ((((int64_t)((int)threadIdx.x)) & (int64_t)31) * (int64_t)4)) + ((((((((int64_t)((int)blockIdx.y)) * (int64_t)128) + (((int64_t)i_) * (int64_t)32)) + ((((int64_t)((int)threadIdx.x)) >> (int64_t)5) * (int64_t)4)) + (((int64_t)((int)blockIdx.z)) * ((int64_t)shape_x))) + ((int64_t)j)) * ((int64_t)stride_x))));
      #pragma unroll
      for (int k = 0; k < 4; ++k) {
        tmp[((k * 4) + j)] = tmp_row[k];
      }
    }
    #pragma unroll
    for (int j_1 = 0; j_1 < 4; ++j_1) {
      *(uint2*)(out_shared + (((((((int)threadIdx.x) & 31) * 528) + ((((((int)threadIdx.x) >> 2) + j_1) & 3) * 132)) + (i_ * 32)) + ((((int)threadIdx.x) >> 5) * 4))) = *(uint2*)(tmp + ((((((int)threadIdx.x) >> 2) + j_1) & 3) * 4));
    }
  }
  __syncthreads();
  #pragma unroll
  for (int i = 0; i < 16; ++i) {
    *(uint2*)(out + ((((((int64_t)((int)blockIdx.y)) * (int64_t)128) + ((((int64_t)((int)threadIdx.x)) & (int64_t)31) * (int64_t)4)) + ((((int64_t)((int)blockIdx.z)) * ((int64_t)shape_x)) * ((int64_t)shape_y))) + ((((((int64_t)((int)blockIdx.x)) * (int64_t)128) + (((int64_t)i) * (int64_t)8)) + (((int64_t)((int)threadIdx.x)) >> (int64_t)5)) * ((int64_t)shape_x)))) = *(uint2*)(out_shared + (((i * 1056) + ((((int)threadIdx.x) >> 5) * 132)) + ((((int)threadIdx.x) & 31) * 4)));
  }
}

