// TileKernels CUDA dump (generated by scripts/dump_cuda_sources.py)
// Source Python: tile_kernels/engram/engram_fused_weight_kernel.py
// JIT factory: get_engram_fused_weight_kernel
// prim_func: engram_fused_weight_kernel
// Compile args: {"args": [7168, 4], "kwargs": {}}
// Public API: tile_kernels.engram.fused_weight
#include <tl_templates/cuda/gemm.h>
#include <tl_templates/cuda/copy.h>
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#include <tl_templates/cuda/debug.h>
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void engram_fused_weight_kernel_kernel(const bfloat16_t* __restrict__ weight_embed, float* __restrict__ weight_fused, const bfloat16_t* __restrict__ weight_hidden);
extern "C" __global__ void __launch_bounds__(32, 1) engram_fused_weight_kernel_kernel(const bfloat16_t* __restrict__ weight_embed, float* __restrict__ weight_fused, const bfloat16_t* __restrict__ weight_hidden) {
  float a_local[8];
  float b_local[8];
  ulonglong4 __1;
  uint4 v_ = *(uint4*)(weight_hidden + (((((int)blockIdx.x) * 7168) + (((int)blockIdx.y) * 256)) + (((int)threadIdx.x) * 8)));
  ((float2*)(&__1))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[0]);
  ((float2*)(&__1))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[1]);
  ((float2*)(&__1))[2] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[2]);
  ((float2*)(&__1))[3] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[3]);
  *(ulonglong4*)(a_local + 0) = __1;
  ulonglong4 __2;
  uint4 v__1 = *(uint4*)(weight_embed + (((((int)blockIdx.x) * 7168) + (((int)blockIdx.y) * 256)) + (((int)threadIdx.x) * 8)));
  ((float2*)(&__2))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__1))[0]);
  ((float2*)(&__2))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__1))[1]);
  ((float2*)(&__2))[2] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__1))[2]);
  ((float2*)(&__2))[3] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__1))[3]);
  *(ulonglong4*)(b_local + 0) = __2;
  ulonglong4 __3;
    ulonglong4 v__2 = *(ulonglong4*)(a_local + 0);
    ulonglong4 v__3 = *(ulonglong4*)(b_local + 0);
    *(float2*)(&(__3.x)) = tl::mul2(*(float2*)(&(v__2.x)), *(float2*)(&(v__3.x)));
    *(float2*)(&(__3.y)) = tl::mul2(*(float2*)(&(v__2.y)), *(float2*)(&(v__3.y)));
    *(float2*)(&(__3.z)) = tl::mul2(*(float2*)(&(v__2.z)), *(float2*)(&(v__3.z)));
    *(float2*)(&(__3.w)) = tl::mul2(*(float2*)(&(v__2.w)), *(float2*)(&(v__3.w)));
  tl::store_global_256(&(*(ulonglong4*)(weight_fused + (((((int)blockIdx.x) * 7168) + (((int)blockIdx.y) * 256)) + (((int)threadIdx.x) * 8)))), __3);
}

