// TileKernels CUDA dump (generated by scripts/dump_cuda_sources.py)
// Source Python: tile_kernels/engram/engram_grad_w_reduce_kernel.py
// JIT factory: get_engram_grad_w_reduce_kernel
// prim_func: engram_grad_w_reduce_kernel
// Compile args: {"args": [7168, 188, 4], "kwargs": {}}
// Public API: tile_kernels.engram.grad_w_reduce
#include <tl_templates/cuda/gemm.h>
#include <tl_templates/cuda/copy.h>
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#include <tl_templates/cuda/debug.h>
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void engram_grad_w_reduce_kernel_kernel(const float* __restrict__ grad_w_partial, float* __restrict__ grad_weight_embed, float* __restrict__ grad_weight_hidden, const bfloat16_t* __restrict__ weight_embed, const bfloat16_t* __restrict__ weight_hidden);
extern "C" __global__ void __launch_bounds__(128, 1) engram_grad_w_reduce_kernel_kernel(const float* __restrict__ grad_w_partial, float* __restrict__ grad_weight_embed, float* __restrict__ grad_weight_hidden, const bfloat16_t* __restrict__ weight_embed, const bfloat16_t* __restrict__ weight_hidden) {
  float grad_w_fragment[4];
  bfloat16_t weight_hidden_local_cast[4];
  float wh_fragment[4];
  bfloat16_t weight_embed_local_cast_1[4];
  float we_fragment[4];
  float grad_wh_fragment[4];
  float grad_we_fragment[4];
  extern __shared__ __align__(1024) float grad_w_shared[];
  float broadcast_var = 0x0p+0f/*0.000000e+00*/;
  *(float4*)(grad_w_fragment + 0) = make_float4(broadcast_var, broadcast_var, broadcast_var, broadcast_var);
  *(uint2*)(weight_hidden_local_cast + 0) = *(uint2*)(weight_hidden + (((((int)blockIdx.x) * 7168) + (((int)blockIdx.y) * 512)) + (((int)threadIdx.x) * 4)));
  float4 __1;
  uint2 v_ = *(uint2*)(weight_hidden_local_cast + 0);
  ((float2*)(&__1))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[0]);
  ((float2*)(&__1))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[1]);
  *(float4*)(wh_fragment + 0) = __1;
  *(uint2*)(weight_embed_local_cast_1 + 0) = *(uint2*)(weight_embed + (((((int)blockIdx.x) * 7168) + (((int)blockIdx.y) * 512)) + (((int)threadIdx.x) * 4)));
  float4 __2;
  uint2 v__1 = *(uint2*)(weight_embed_local_cast_1 + 0);
  ((float2*)(&__2))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__1))[0]);
  ((float2*)(&__2))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__1))[1]);
  *(float4*)(we_fragment + 0) = __2;
  *(float4*)(grad_wh_fragment + 0) = *(float4*)(grad_weight_hidden + (((((int)blockIdx.x) * 7168) + (((int)blockIdx.y) * 512)) + (((int)threadIdx.x) * 4)));
  *(float4*)(grad_we_fragment + 0) = *(float4*)(grad_weight_embed + (((((int)blockIdx.x) * 7168) + (((int)blockIdx.y) * 512)) + (((int)threadIdx.x) * 4)));
  #pragma unroll
  for (int i = 0; i < 47; ++i) {
    tl::cp_async_gs<16>((&(grad_w_shared[((i * 512) + (((int)threadIdx.x) * 4))])), (&(grad_w_partial[((((i * 28672) + (((int)blockIdx.x) * 7168)) + (((int)blockIdx.y) * 512)) + (((int)threadIdx.x) * 4))])));
  }
  tl::cp_async_commit();
  for (int i_r = 0; i_r < 3; ++i_r) {
    #pragma unroll
    for (int i_1 = 0; i_1 < 47; ++i_1) {
      tl::cp_async_gs<16>((&(grad_w_shared[(((((i_r + 1) & 1) * 24064) + (i_1 * 512)) + (((int)threadIdx.x) * 4))])), (&(grad_w_partial[((((((i_r * 1347584) + (i_1 * 28672)) + (((int)blockIdx.x) * 7168)) + (((int)blockIdx.y) * 512)) + (((int)threadIdx.x) * 4)) + 1347584)])));
    }
    tl::cp_async_commit();
    tl::cp_async_wait<1>();
    for (int i_2 = 0; i_2 < 47; ++i_2) {
      float4 __3;
        float4 v__2 = *(float4*)(grad_w_fragment + 0);
        float4 v__3 = *(float4*)(grad_w_shared + ((((i_r & 1) * 24064) + (i_2 * 512)) + (((int)threadIdx.x) * 4)));
        *(float2*)(&(__3.x)) = tl::add2(*(float2*)(&(v__2.x)), *(float2*)(&(v__3.x)));
        *(float2*)(&(__3.z)) = tl::add2(*(float2*)(&(v__2.z)), *(float2*)(&(v__3.z)));
      *(float4*)(grad_w_fragment + 0) = __3;
    }
  }
  tl::cp_async_wait<0>();
  for (int i_3 = 0; i_3 < 47; ++i_3) {
    float4 __4;
      float4 v__4 = *(float4*)(grad_w_fragment + 0);
      float4 v__5 = *(float4*)(grad_w_shared + (((i_3 * 512) + (((int)threadIdx.x) * 4)) + 24064));
      *(float2*)(&(__4.x)) = tl::add2(*(float2*)(&(v__4.x)), *(float2*)(&(v__5.x)));
      *(float2*)(&(__4.z)) = tl::add2(*(float2*)(&(v__4.z)), *(float2*)(&(v__5.z)));
    *(float4*)(grad_w_fragment + 0) = __4;
  }
  #pragma unroll
  for (int i_4 = 0; i_4 < 4; ++i_4) {
    grad_wh_fragment[i_4] = (grad_wh_fragment[i_4] + (grad_w_fragment[i_4] * we_fragment[i_4]));
    grad_we_fragment[i_4] = (grad_we_fragment[i_4] + (grad_w_fragment[i_4] * wh_fragment[i_4]));
  }
  *(float4*)(grad_weight_embed + (((((int)blockIdx.x) * 7168) + (((int)blockIdx.y) * 512)) + (((int)threadIdx.x) * 4))) = *(float4*)(grad_we_fragment + 0);
  *(float4*)(grad_weight_hidden + (((((int)blockIdx.x) * 7168) + (((int)blockIdx.y) * 512)) + (((int)threadIdx.x) * 4))) = *(float4*)(grad_wh_fragment + 0);
}

