// TileKernels CUDA dump (generated by scripts/dump_cuda_sources.py)
// Source Python: tile_kernels/engram/engram_gate_kernel.py
// JIT factory: get_engram_gate_fwd_kernel
// prim_func: engram_gate_fwd_kernel
// Compile args: {"args": [7168, 1e-20, 0.011811389781538352, 28672, 7168, 7168, 188], "kwargs": {"clamp_value": 1e-06, "hc_mult": 4, "save_for_backward": true}}
// Public API: tile_kernels.engram.engram_gate_fwd
#include <math_constants.h>
#include <tl_templates/cuda/gemm.h>
#include <tl_templates/cuda/copy.h>
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#include <tl_templates/cuda/debug.h>
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void engram_gate_fwd_kernel_kernel(float* __restrict__ dot_out, float* __restrict__ gate_score, const bfloat16_t* __restrict__ hidden_states, const bfloat16_t* __restrict__ k, bfloat16_t* __restrict__ output, float* __restrict__ rstd_k, float* __restrict__ rstd_x, const bfloat16_t* __restrict__ v, const float* __restrict__ weight_fused, int num_tokens);
extern "C" __global__ void __launch_bounds__(32, 1) engram_gate_fwd_kernel_kernel(float* __restrict__ dot_out, float* __restrict__ gate_score, const bfloat16_t* __restrict__ hidden_states, const bfloat16_t* __restrict__ k, bfloat16_t* __restrict__ output, float* __restrict__ rstd_k, float* __restrict__ rstd_x, const bfloat16_t* __restrict__ v, const float* __restrict__ weight_fused, int num_tokens) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  float rstd_k_local[1];
  float rstd_x_local[1];
  float gate_score_local[1];
  float x_local[8];
  float k_local[8];
  float w_local[8];
  float rstd_k_reducer[1];
  float rstd_x_reducer[1];
  float gate_score_reducer[1];
  float v_local[8];
  bfloat16_t output_local_cast[8];
  for (int i_s = min((((num_tokens + 234) / 235) * ((int)blockIdx.y)), num_tokens); i_s < min((((num_tokens + 234) / 235) * (((int)blockIdx.y) + 1)), num_tokens); ++i_s) {
    if (i_s == min((((num_tokens + 234) / 235) * ((int)blockIdx.y)), num_tokens)) {
      #pragma unroll
      for (int i = 0; i < 4; ++i) {
        tl::cp_async_gs<16>((&(((bfloat16_t*)buf_dyn_shmem)[((i * 256) + (((int)threadIdx.x) * 8))])), (&(hidden_states[((((((int64_t)i_s) * (int64_t)28672) + (((int64_t)((int)blockIdx.x)) * (int64_t)7168)) + (((int64_t)i) * (int64_t)256)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8))])));
      }
      tl::cp_async_commit();
      #pragma unroll
      for (int i_1 = 0; i_1 < 4; ++i_1) {
        tl::cp_async_gs<16>((&(((bfloat16_t*)buf_dyn_shmem)[(((i_1 * 256) + (((int)threadIdx.x) * 8)) + 7168)])), (&(k[((((((int64_t)i_s) * (int64_t)28672) + (((int64_t)((int)blockIdx.x)) * (int64_t)7168)) + (((int64_t)i_1) * (int64_t)256)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8))])));
      }
      tl::cp_async_commit();
    }
    rstd_k_local[0] = 0x0p+0f/*0.000000e+00*/;
    rstd_x_local[0] = 0x0p+0f/*0.000000e+00*/;
    gate_score_local[0] = 0x0p+0f/*0.000000e+00*/;
    for (int i_b = 1; i_b < 7; ++i_b) {
      #pragma unroll
      for (int i_2 = 0; i_2 < 4; ++i_2) {
        tl::cp_async_gs<16>((&(((bfloat16_t*)buf_dyn_shmem)[(((i_b * 1024) + (i_2 * 256)) + (((int)threadIdx.x) * 8))])), (&(hidden_states[(((((((int64_t)i_s) * (int64_t)28672) + (((int64_t)((int)blockIdx.x)) * (int64_t)7168)) + (((int64_t)i_b) * (int64_t)1024)) + (((int64_t)i_2) * (int64_t)256)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8))])));
      }
      tl::cp_async_commit();
      #pragma unroll
      for (int i_3 = 0; i_3 < 4; ++i_3) {
        tl::cp_async_gs<16>((&(((bfloat16_t*)buf_dyn_shmem)[(((((i_b & 1) * 1024) + (i_3 * 256)) + (((int)threadIdx.x) * 8)) + 7168)])), (&(k[(((((((int64_t)i_s) * (int64_t)28672) + (((int64_t)((int)blockIdx.x)) * (int64_t)7168)) + (((int64_t)i_b) * (int64_t)1024)) + (((int64_t)i_3) * (int64_t)256)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8))])));
      }
      tl::cp_async_commit();
      tl::cp_async_wait<2>();
      for (int i_sub = 0; i_sub < 4; ++i_sub) {
        for (int i_k = 0; i_k < 2; ++i_k) {
          float4 __1;
          uint2 v_ = *(uint2*)(((bfloat16_t*)buf_dyn_shmem) + (((((i_b * 1024) + (i_sub * 256)) + (((int)threadIdx.x) * 8)) + (i_k * 4)) - 1024));
          ((float2*)(&__1))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[0]);
          ((float2*)(&__1))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[1]);
          *(float4*)(x_local + (i_k * 4)) = __1;
          float4 __2;
          uint2 v__1 = *(uint2*)(((bfloat16_t*)buf_dyn_shmem) + (((((((i_b + 1) & 1) * 1024) + (i_sub * 256)) + (((int)threadIdx.x) * 8)) + (i_k * 4)) + 7168));
          ((float2*)(&__2))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__1))[0]);
          ((float2*)(&__2))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__1))[1]);
          *(float4*)(k_local + (i_k * 4)) = __2;
        }
        *(ulonglong4*)(w_local + 0) = tl::load_global_256(&(*(ulonglong4*)(weight_fused + (((((((int)blockIdx.x) * 7168) + (i_b * 1024)) + (i_sub * 256)) + (((int)threadIdx.x) * 8)) - 1024))));
        for (int i_k_1 = 0; i_k_1 < 8; ++i_k_1) {
          rstd_x_local[0] = (rstd_x_local[0] + (x_local[i_k_1] * x_local[i_k_1]));
          rstd_k_local[0] = (rstd_k_local[0] + (k_local[i_k_1] * k_local[i_k_1]));
          gate_score_local[0] = (gate_score_local[0] + ((x_local[i_k_1] * w_local[i_k_1]) * k_local[i_k_1]));
        }
      }
    }
    tl::cp_async_wait<0>();
    #pragma unroll
    for (int i_4 = 0; i_4 < 4; ++i_4) {
      tl::cp_async_gs<16>((&(((bfloat16_t*)buf_dyn_shmem)[(((i_4 * 256) + (((int)threadIdx.x) * 8)) + 8192)])), (&(v[(((((int64_t)i_s) * (int64_t)7168) + (((int64_t)i_4) * (int64_t)256)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8))])));
    }
    tl::cp_async_commit();
    for (int i_sub_1 = 0; i_sub_1 < 4; ++i_sub_1) {
      for (int i_k_2 = 0; i_k_2 < 2; ++i_k_2) {
        float4 __3;
        uint2 v__2 = *(uint2*)(((bfloat16_t*)buf_dyn_shmem) + ((((i_sub_1 * 256) + (((int)threadIdx.x) * 8)) + (i_k_2 * 4)) + 6144));
        ((float2*)(&__3))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__2))[0]);
        ((float2*)(&__3))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__2))[1]);
        *(float4*)(x_local + (i_k_2 * 4)) = __3;
        float4 __4;
        uint2 v__3 = *(uint2*)(((bfloat16_t*)buf_dyn_shmem) + ((((i_sub_1 * 256) + (((int)threadIdx.x) * 8)) + (i_k_2 * 4)) + 7168));
        ((float2*)(&__4))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__3))[0]);
        ((float2*)(&__4))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__3))[1]);
        *(float4*)(k_local + (i_k_2 * 4)) = __4;
      }
      *(ulonglong4*)(w_local + 0) = tl::load_global_256(&(*(ulonglong4*)(weight_fused + ((((((int)blockIdx.x) * 7168) + (i_sub_1 * 256)) + (((int)threadIdx.x) * 8)) + 6144))));
      for (int i_k_3 = 0; i_k_3 < 8; ++i_k_3) {
        rstd_x_local[0] = (rstd_x_local[0] + (x_local[i_k_3] * x_local[i_k_3]));
        rstd_k_local[0] = (rstd_k_local[0] + (k_local[i_k_3] * k_local[i_k_3]));
        gate_score_local[0] = (gate_score_local[0] + ((x_local[i_k_3] * w_local[i_k_3]) * k_local[i_k_3]));
      }
    }
    #pragma unroll
    for (int i_5 = 0; i_5 < 4; ++i_5) {
      tl::cp_async_gs<16>((&(((bfloat16_t*)buf_dyn_shmem)[(((i_5 * 256) + (((int)threadIdx.x) * 8)) + 7168)])), (&(v[((((((int64_t)i_s) * (int64_t)7168) + (((int64_t)i_5) * (int64_t)256)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8)) + (int64_t)1024)])));
    }
    tl::cp_async_commit();
    rstd_k_reducer[0] = tl::warp_reduce_sum(rstd_k_local[0]);
    rstd_x_reducer[0] = tl::warp_reduce_sum(rstd_x_local[0]);
    gate_score_reducer[0] = tl::warp_reduce_sum(gate_score_local[0]);
    rstd_x_reducer[0] = rsqrtf(((rstd_x_reducer[0] / 0x1.cp+12f/*7.168000e+03*/) + 0x1.79ca10c924223p-67f/*1.000000e-20*/));
    rstd_k_reducer[0] = rsqrtf(((rstd_k_reducer[0] / 0x1.cp+12f/*7.168000e+03*/) + 0x1.79ca10c924223p-67f/*1.000000e-20*/));
    if (((int)threadIdx.x) == 0) {
      dot_out[((((int64_t)i_s) * (int64_t)4) + ((int64_t)((int)blockIdx.x)))] = gate_score_reducer[0];
      rstd_x[((((int64_t)i_s) * (int64_t)4) + ((int64_t)((int)blockIdx.x)))] = rstd_x_reducer[0];
      rstd_k[((((int64_t)i_s) * (int64_t)4) + ((int64_t)((int)blockIdx.x)))] = rstd_k_reducer[0];
    }
    gate_score_reducer[0] = (((gate_score_reducer[0] * rstd_x_reducer[0]) * rstd_k_reducer[0]) * 0x1.83091e6a7f7e7p-7f/*1.181139e-02*/);
    gate_score_reducer[0] = (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - copysignf(sqrtf(min(max(fabsf(gate_score_reducer[0]), 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/), CUDART_INF_F)), gate_score_reducer[0])))));
    if (((int)threadIdx.x) == 0) {
      gate_score[((((int64_t)i_s) * (int64_t)4) + ((int64_t)((int)blockIdx.x)))] = gate_score_reducer[0];
    }
    for (int i_b_1 = 0; i_b_1 < 7; ++i_b_1) {
      if (i_b_1 < 6) {
        tl::cp_async_wait<1>();
      } else {
        tl::cp_async_wait<0>();
        if (((i_s + 1) < (((num_tokens + 234) / 235) * (((int)blockIdx.y) + 1))) && ((i_s + 1) < num_tokens)) {
          #pragma unroll
          for (int i_6 = 0; i_6 < 4; ++i_6) {
            tl::cp_async_gs<16>((&(((bfloat16_t*)buf_dyn_shmem)[(((i_6 * 256) + (((int)threadIdx.x) * 8)) + 7168)])), (&(k[(((((((int64_t)i_s) * (int64_t)28672) + (((int64_t)((int)blockIdx.x)) * (int64_t)7168)) + (((int64_t)i_6) * (int64_t)256)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8)) + (int64_t)28672)])));
          }
          tl::cp_async_commit();
          #pragma unroll
          for (int i_7 = 0; i_7 < 4; ++i_7) {
            tl::cp_async_gs<16>((&(((bfloat16_t*)buf_dyn_shmem)[((i_7 * 256) + (((int)threadIdx.x) * 8))])), (&(hidden_states[(((((((int64_t)i_s) * (int64_t)28672) + (((int64_t)((int)blockIdx.x)) * (int64_t)7168)) + (((int64_t)i_7) * (int64_t)256)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8)) + (int64_t)28672)])));
          }
          tl::cp_async_commit();
        }
      }
      for (int i_sub_2 = 0; i_sub_2 < 4; ++i_sub_2) {
        for (int i_k_4 = 0; i_k_4 < 2; ++i_k_4) {
          float4 __5;
          uint2 v__4 = *(uint2*)(((bfloat16_t*)buf_dyn_shmem) + ((((i_b_1 * 1024) + (i_sub_2 * 256)) + (((int)threadIdx.x) * 8)) + (i_k_4 * 4)));
          ((float2*)(&__5))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__4))[0]);
          ((float2*)(&__5))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__4))[1]);
          *(float4*)(x_local + (i_k_4 * 4)) = __5;
          float4 __6;
          uint2 v__5 = *(uint2*)(((bfloat16_t*)buf_dyn_shmem) + (((((((i_b_1 + 1) & 1) * 1024) + (i_sub_2 * 256)) + (((int)threadIdx.x) * 8)) + (i_k_4 * 4)) + 7168));
          ((float2*)(&__6))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__5))[0]);
          ((float2*)(&__6))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__5))[1]);
          *(float4*)(v_local + (i_k_4 * 4)) = __6;
        }
        for (int i_k_5 = 0; i_k_5 < 2; ++i_k_5) {
          uint2 __7;
          float4 __8;
            float4 v__6 = make_float4(gate_score_reducer[0], gate_score_reducer[0], gate_score_reducer[0], gate_score_reducer[0]);
            float4 v__7 = *(float4*)(v_local + (i_k_5 * 4));
            float4 v__8 = *(float4*)(x_local + (i_k_5 * 4));
            *(float2*)(&(__8.x)) = tl::fma2(*(float2*)(&(v__6.x)), *(float2*)(&(v__7.x)), *(float2*)(&(v__8.x)));
            *(float2*)(&(__8.z)) = tl::fma2(*(float2*)(&(v__6.z)), *(float2*)(&(v__7.z)), *(float2*)(&(v__8.z)));
          (reinterpret_cast<__nv_bfloat162*>(&__7))[0] = __float22bfloat162_rn(((float2*)(&__8))[0]);
          (reinterpret_cast<__nv_bfloat162*>(&__7))[1] = __float22bfloat162_rn(((float2*)(&__8))[1]);
          *(uint2*)(output_local_cast + (i_k_5 * 4)) = __7;
        }
        *(uint4*)(output + (((((((int64_t)i_s) * (int64_t)28672) + (((int64_t)((int)blockIdx.x)) * (int64_t)7168)) + (((int64_t)i_b_1) * (int64_t)1024)) + (((int64_t)i_sub_2) * (int64_t)256)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8))) = *(uint4*)(output_local_cast + 0);
      }
      if (i_b_1 < 5) {
        #pragma unroll
        for (int i_8 = 0; i_8 < 4; ++i_8) {
          tl::cp_async_gs<16>((&(((bfloat16_t*)buf_dyn_shmem)[((((((i_b_1 + 1) & 1) * 1024) + (i_8 * 256)) + (((int)threadIdx.x) * 8)) + 7168)])), (&(v[(((((((int64_t)i_s) * (int64_t)7168) + (((int64_t)i_b_1) * (int64_t)1024)) + (((int64_t)i_8) * (int64_t)256)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8)) + (int64_t)2048)])));
        }
        tl::cp_async_commit();
      }
    }
  }
}

