// TileKernels CUDA dump (generated by scripts/dump_cuda_sources.py)
// Source Python: tile_kernels/engram/engram_gate_kernel.py
// JIT factory: get_engram_gate_bwd_kernel
// prim_func: engram_gate_bwd_kernel
// Compile args: {"args": [7168, 0.011811389781538352, 28672, 7168, 7168, 188], "kwargs": {"clamp_value": 1e-06, "hc_mult": 4}}
// Public API: tile_kernels.engram.engram_gate_bwd
#include <tl_templates/cuda/gemm.h>
#include <tl_templates/cuda/copy.h>
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#include <tl_templates/cuda/debug.h>
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void engram_gate_bwd_kernel_kernel(const float* __restrict__ dot_in, const float* __restrict__ gate_in, bfloat16_t* __restrict__ grad_k, const bfloat16_t* __restrict__ grad_out, bfloat16_t* __restrict__ grad_v, float* __restrict__ grad_w_partial, bfloat16_t* __restrict__ grad_x, const bfloat16_t* __restrict__ hidden_states, const bfloat16_t* __restrict__ k, const float* __restrict__ rstd_k_in, const float* __restrict__ rstd_x_in, const bfloat16_t* __restrict__ v, const float* __restrict__ weight_fused, int num_tokens);
extern "C" __global__ void __launch_bounds__(256, 1) engram_gate_bwd_kernel_kernel(const float* __restrict__ dot_in, const float* __restrict__ gate_in, bfloat16_t* __restrict__ grad_k, const bfloat16_t* __restrict__ grad_out, bfloat16_t* __restrict__ grad_v, float* __restrict__ grad_w_partial, bfloat16_t* __restrict__ grad_x, const bfloat16_t* __restrict__ hidden_states, const bfloat16_t* __restrict__ k, const float* __restrict__ rstd_k_in, const float* __restrict__ rstd_x_in, const bfloat16_t* __restrict__ v, const float* __restrict__ weight_fused, int num_tokens) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  float grad_w_local[112];
  float gate_local[4];
  float gate_local_hc = 0x0p+0f/*0.000000e+00*/;
  float rstd_x_local = 0x0p+0f/*0.000000e+00*/;
  float rstd_k_local = 0x0p+0f/*0.000000e+00*/;
  float dot_in_local = 0x0p+0f/*0.000000e+00*/;
  float dldg_local[1];
  float go_local[8];
  float v_local[8];
  float dldg_r[1];
  float grad_v_partial[4];
  bfloat16_t go_smem_local_cast[4];
  float go_v_local[4];
  bfloat16_t grad_v_local_cast_1[4];
  float dot_x_local = 0x0p+0f/*0.000000e+00*/;
  float dot_k_local = 0x0p+0f/*0.000000e+00*/;
  float go_x_local[4];
  float x_local[4];
  float k_local[4];
  float w_fused_local[4];
  #pragma unroll
  for (int i = 0; i < 28; ++i) {
    float broadcast_var = 0x0p+0f/*0.000000e+00*/;
    *(float4*)(grad_w_local + (i * 4)) = make_float4(broadcast_var, broadcast_var, broadcast_var, broadcast_var);
  }
  for (int i_s = min((((num_tokens + 187) / 188) * ((int)blockIdx.x)), num_tokens); i_s < min((((num_tokens + 187) / 188) * (((int)blockIdx.x) + 1)), num_tokens); ++i_s) {
    if (i_s == min((((num_tokens + 187) / 188) * ((int)blockIdx.x)), num_tokens)) {
      #pragma unroll
      for (int i_1 = 0; i_1 < 7; ++i_1) {
        tl::cp_async_gs<8>((&(((bfloat16_t*)buf_dyn_shmem)[(((i_1 * 1024) + (((int)threadIdx.x) * 4)) + 28672)])), (&(v[(((((int64_t)i_s) * (int64_t)7168) + (((int64_t)i_1) * (int64_t)1024)) + (((int64_t)((int)threadIdx.x)) * (int64_t)4))])));
      }
      tl::cp_async_commit();
      #pragma unroll
      for (int i_2 = 0; i_2 < 7; ++i_2) {
        tl::cp_async_gs<16>((&(((bfloat16_t*)buf_dyn_shmem)[((((((int)threadIdx.x) >> 6) * 7168) + (i_2 * 512)) + ((((int)threadIdx.x) & 63) * 8))])), (&(grad_out[((((((int64_t)i_s) * (int64_t)28672) + ((((int64_t)((int)threadIdx.x)) >> (int64_t)6) * (int64_t)7168)) + (((int64_t)i_2) * (int64_t)512)) + ((((int64_t)((int)threadIdx.x)) & (int64_t)63) * (int64_t)8))])));
      }
      tl::cp_async_commit();
      tl::cp_async_wait<1>();
      __syncthreads();
    }
    *(float4*)(gate_local + 0) = *(float4*)(gate_in + (((int64_t)i_s) * (int64_t)4));
    gate_local_hc = gate_in[((((int64_t)i_s) * (int64_t)4) + (((int64_t)tl::get_warp_idx()) >> (int64_t)1))];
    rstd_x_local = rstd_x_in[((((int64_t)i_s) * (int64_t)4) + (((int64_t)tl::get_warp_idx()) >> (int64_t)1))];
    rstd_k_local = rstd_k_in[((((int64_t)i_s) * (int64_t)4) + (((int64_t)tl::get_warp_idx()) >> (int64_t)1))];
    dot_in_local = dot_in[((((int64_t)i_s) * (int64_t)4) + (((int64_t)tl::get_warp_idx()) >> (int64_t)1))];
    dldg_local[0] = 0x0p+0f/*0.000000e+00*/;
    #pragma unroll
    for (int i_3 = 0; i_3 < 7; ++i_3) {
      tl::cp_async_gs<16>((&(((bfloat16_t*)buf_dyn_shmem)[(((((((int)threadIdx.x) >> 6) * 7168) + (i_3 * 512)) + ((((int)threadIdx.x) & 63) * 8)) + 3584)])), (&(grad_out[(((((((int64_t)i_s) * (int64_t)28672) + ((((int64_t)((int)threadIdx.x)) >> (int64_t)6) * (int64_t)7168)) + (((int64_t)i_3) * (int64_t)512)) + ((((int64_t)((int)threadIdx.x)) & (int64_t)63) * (int64_t)8)) + (int64_t)3584)])));
    }
    tl::cp_async_commit();
    tl::cp_async_wait<1>();
    for (int i_sub = 0; i_sub < 7; ++i_sub) {
      for (int i_k = 0; i_k < 2; ++i_k) {
        bfloat16_t broadcast_var_1 = bfloat16_t(0x0p+0f/*0.000000e+00*/);
        float4 __1;
        uint2 condval;
        if (((0 <= (((i_sub * 64) + ((tl::get_warp_idx() & 1) * 32)) + tl::get_lane_idx())) && (((((tl::get_lane_idx() >> 5) + (tl::get_warp_idx() & 1)) >> 1) + i_sub) < 14))) {
          condval = *(uint2*)(((bfloat16_t*)buf_dyn_shmem) + ((((((((int64_t)tl::get_warp_idx()) >> (int64_t)1) * (int64_t)7168) + (((int64_t)i_sub) * (int64_t)512)) + ((((int64_t)tl::get_warp_idx()) & (int64_t)1) * (int64_t)256)) + (((int64_t)tl::get_lane_idx()) * (int64_t)8)) + (((int64_t)i_k) * (int64_t)4)));
        } else {
          condval = make_uint2(__pack_nv_bfloat162(broadcast_var_1, broadcast_var_1), __pack_nv_bfloat162(broadcast_var_1, broadcast_var_1));
        }
        ((float2*)(&__1))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&condval))[0]);
        ((float2*)(&__1))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&condval))[1]);
        *(float4*)(go_local + (i_k * 4)) = __1;
        bfloat16_t broadcast_var_2 = bfloat16_t(0x0p+0f/*0.000000e+00*/);
        float4 __2;
        uint2 condval_1;
        if (((0 <= (((i_sub * 64) + ((tl::get_warp_idx() & 1) * 32)) + tl::get_lane_idx())) && (((((tl::get_lane_idx() >> 5) + (tl::get_warp_idx() & 1)) >> 1) + i_sub) < 14))) {
          condval_1 = *(uint2*)(((bfloat16_t*)buf_dyn_shmem) + (((((((int64_t)i_sub) * (int64_t)512) + ((((int64_t)tl::get_warp_idx()) & (int64_t)1) * (int64_t)256)) + (((int64_t)tl::get_lane_idx()) * (int64_t)8)) + (((int64_t)i_k) * (int64_t)4)) + (int64_t)28672));
        } else {
          condval_1 = make_uint2(__pack_nv_bfloat162(broadcast_var_2, broadcast_var_2), __pack_nv_bfloat162(broadcast_var_2, broadcast_var_2));
        }
        ((float2*)(&__2))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&condval_1))[0]);
        ((float2*)(&__2))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&condval_1))[1]);
        *(float4*)(v_local + (i_k * 4)) = __2;
      }
      for (int i_k_1 = 0; i_k_1 < 8; ++i_k_1) {
        dldg_local[0] = (dldg_local[0] + (go_local[i_k_1] * v_local[i_k_1]));
      }
    }
    tl::cp_async_wait<0>();
    for (int i_sub_1 = 0; i_sub_1 < 7; ++i_sub_1) {
      for (int i_k_2 = 0; i_k_2 < 2; ++i_k_2) {
        bfloat16_t broadcast_var_3 = bfloat16_t(0x0p+0f/*0.000000e+00*/);
        float4 __3;
        uint2 condval_2;
        if (((-448 <= (((i_sub_1 * 64) + ((tl::get_warp_idx() & 1) * 32)) + tl::get_lane_idx())) && (((((tl::get_lane_idx() >> 5) + (tl::get_warp_idx() & 1)) >> 1) + i_sub_1) < 7))) {
          condval_2 = *(uint2*)(((bfloat16_t*)buf_dyn_shmem) + (((((((((int64_t)tl::get_warp_idx()) >> (int64_t)1) * (int64_t)7168) + (((int64_t)i_sub_1) * (int64_t)512)) + ((((int64_t)tl::get_warp_idx()) & (int64_t)1) * (int64_t)256)) + (((int64_t)tl::get_lane_idx()) * (int64_t)8)) + (((int64_t)i_k_2) * (int64_t)4)) + (int64_t)3584));
        } else {
          condval_2 = make_uint2(__pack_nv_bfloat162(broadcast_var_3, broadcast_var_3), __pack_nv_bfloat162(broadcast_var_3, broadcast_var_3));
        }
        ((float2*)(&__3))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&condval_2))[0]);
        ((float2*)(&__3))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&condval_2))[1]);
        *(float4*)(go_local + (i_k_2 * 4)) = __3;
        bfloat16_t broadcast_var_4 = bfloat16_t(0x0p+0f/*0.000000e+00*/);
        float4 __4;
        uint2 condval_3;
        if (((-448 <= (((i_sub_1 * 64) + ((tl::get_warp_idx() & 1) * 32)) + tl::get_lane_idx())) && (((((tl::get_lane_idx() >> 5) + (tl::get_warp_idx() & 1)) >> 1) + i_sub_1) < 7))) {
          condval_3 = *(uint2*)(((bfloat16_t*)buf_dyn_shmem) + (((((((int64_t)i_sub_1) * (int64_t)512) + ((((int64_t)tl::get_warp_idx()) & (int64_t)1) * (int64_t)256)) + (((int64_t)tl::get_lane_idx()) * (int64_t)8)) + (((int64_t)i_k_2) * (int64_t)4)) + (int64_t)32256));
        } else {
          condval_3 = make_uint2(__pack_nv_bfloat162(broadcast_var_4, broadcast_var_4), __pack_nv_bfloat162(broadcast_var_4, broadcast_var_4));
        }
        ((float2*)(&__4))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&condval_3))[0]);
        ((float2*)(&__4))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&condval_3))[1]);
        *(float4*)(v_local + (i_k_2 * 4)) = __4;
      }
      for (int i_k_3 = 0; i_k_3 < 8; ++i_k_3) {
        dldg_local[0] = (dldg_local[0] + (go_local[i_k_3] * v_local[i_k_3]));
      }
    }
    dldg_local[0] = tl::warp_reduce_sum(dldg_local[0]);
    if (tl::get_lane_idx() == 0) {
      ((float*)buf_dyn_shmem)[(tl::get_warp_idx() + 22016)] = dldg_local[0];
    }
    __syncthreads();
    if (((i_s + 1) < (((num_tokens + 187) / 188) * (((int)blockIdx.x) + 1))) && ((i_s + 1) < num_tokens)) {
      #pragma unroll
      for (int i_4 = 0; i_4 < 7; ++i_4) {
        tl::cp_async_gs<8>((&(((bfloat16_t*)buf_dyn_shmem)[(((i_4 * 1024) + (((int)threadIdx.x) * 4)) + 28672)])), (&(v[((((((int64_t)i_s) * (int64_t)7168) + (((int64_t)i_4) * (int64_t)1024)) + (((int64_t)((int)threadIdx.x)) * (int64_t)4)) + (int64_t)7168)])));
      }
      tl::cp_async_commit();
    }
    tl::cp_async_gs<8>((&(((bfloat16_t*)buf_dyn_shmem)[((((int)threadIdx.x) * 4) + 41984)])), (&(hidden_states[(((((int64_t)i_s) * (int64_t)28672) + ((((int64_t)((int)threadIdx.x)) >> (int64_t)6) * (int64_t)7168)) + ((((int64_t)((int)threadIdx.x)) & (int64_t)63) * (int64_t)4))])));
    tl::cp_async_commit();
    tl::cp_async_gs<8>((&(((bfloat16_t*)buf_dyn_shmem)[((((int)threadIdx.x) * 4) + 39936)])), (&(k[(((((int64_t)i_s) * (int64_t)28672) + ((((int64_t)((int)threadIdx.x)) >> (int64_t)6) * (int64_t)7168)) + ((((int64_t)((int)threadIdx.x)) & (int64_t)63) * (int64_t)4))])));
    tl::cp_async_commit();
    tl::cp_async_gs<16>((&(((float*)buf_dyn_shmem)[((((int)threadIdx.x) * 4) + 17920)])), (&(weight_fused[(((((int)threadIdx.x) >> 6) * 7168) + ((((int)threadIdx.x) & 63) * 4))])));
    tl::cp_async_commit();
    dldg_r[0] = (((float*)buf_dyn_shmem)[(((tl::get_warp_idx() >> 1) * 2) + 22016)] + ((float*)buf_dyn_shmem)[(((((int64_t)tl::get_warp_idx()) >> (int64_t)1) * (int64_t)2) + (int64_t)22017)]);
    dldg_r[0] = (((((fabsf(dot_in_local) * 0x1.83091e6a7f7e7p-7f/*1.181139e-02*/) * rstd_x_local) * rstd_k_local) < 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/) ? 0x0p+0f/*0.000000e+00*/ : ((((dldg_r[0] * gate_local_hc) * (0x1p+0f/*1.000000e+00*/ - gate_local_hc)) * 0x1p-1f/*5.000000e-01*/) * sqrtf((((0x1.83091e6a7f7e7p-7f/*1.181139e-02*/ * rstd_x_local) * rstd_k_local) / fabsf(dot_in_local)))));
    for (int i_5 = 0; i_5 < 7; ++i_5) {
      float broadcast_var_5 = 0x0p+0f/*0.000000e+00*/;
      *(float4*)(grad_v_partial + 0) = make_float4(broadcast_var_5, broadcast_var_5, broadcast_var_5, broadcast_var_5);
      #pragma unroll
      for (int i_h = 0; i_h < 4; ++i_h) {
        *(uint2*)(go_smem_local_cast + 0) = *(uint2*)(((bfloat16_t*)buf_dyn_shmem) + (((i_h * 7168) + (i_5 * 1024)) + (((int)threadIdx.x) * 4)));
        float4 __5;
        uint2 v_ = *(uint2*)(go_smem_local_cast + 0);
        ((float2*)(&__5))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[0]);
        ((float2*)(&__5))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[1]);
        *(float4*)(go_v_local + 0) = __5;
        float4 __6;
          float4 v__1 = *(float4*)(go_v_local + 0);
          float4 v__2 = make_float4(gate_local[i_h], gate_local[i_h], gate_local[i_h], gate_local[i_h]);
          float4 v__3 = *(float4*)(grad_v_partial + 0);
          *(float2*)(&(__6.x)) = tl::fma2(*(float2*)(&(v__1.x)), *(float2*)(&(v__2.x)), *(float2*)(&(v__3.x)));
          *(float2*)(&(__6.z)) = tl::fma2(*(float2*)(&(v__1.z)), *(float2*)(&(v__2.z)), *(float2*)(&(v__3.z)));
        *(float4*)(grad_v_partial + 0) = __6;
      }
      uint2 __7;
      float4 v__4 = *(float4*)(grad_v_partial + 0);
      (reinterpret_cast<__nv_bfloat162*>(&__7))[0] = __float22bfloat162_rn(((float2*)(&v__4))[0]);
      (reinterpret_cast<__nv_bfloat162*>(&__7))[1] = __float22bfloat162_rn(((float2*)(&v__4))[1]);
      *(uint2*)(grad_v_local_cast_1 + 0) = __7;
      *(uint2*)(grad_v + (((((int64_t)i_s) * (int64_t)7168) + (((int64_t)i_5) * (int64_t)1024)) + (((int64_t)((int)threadIdx.x)) * (int64_t)4))) = *(uint2*)(grad_v_local_cast_1 + 0);
    }
    dot_x_local = (((dot_in_local * rstd_x_local) * rstd_x_local) / 0x1.cp+12f/*7.168000e+03*/);
    dot_k_local = (((dot_in_local * rstd_k_local) * rstd_k_local) / 0x1.cp+12f/*7.168000e+03*/);
    #pragma unroll
    for (int i_b = 1; i_b < 28; ++i_b) {
      tl::cp_async_gs<8>((&(((bfloat16_t*)buf_dyn_shmem)[((((i_b & 1) * 1024) + (((int)threadIdx.x) * 4)) + 41984)])), (&(hidden_states[((((((int64_t)i_s) * (int64_t)28672) + ((((int64_t)((int)threadIdx.x)) >> (int64_t)6) * (int64_t)7168)) + (((int64_t)i_b) * (int64_t)256)) + ((((int64_t)((int)threadIdx.x)) & (int64_t)63) * (int64_t)4))])));
      tl::cp_async_commit();
      tl::cp_async_gs<8>((&(((bfloat16_t*)buf_dyn_shmem)[((((i_b & 1) * 1024) + (((int)threadIdx.x) * 4)) + 39936)])), (&(k[((((((int64_t)i_s) * (int64_t)28672) + ((((int64_t)((int)threadIdx.x)) >> (int64_t)6) * (int64_t)7168)) + (((int64_t)i_b) * (int64_t)256)) + ((((int64_t)((int)threadIdx.x)) & (int64_t)63) * (int64_t)4))])));
      tl::cp_async_commit();
      tl::cp_async_gs<16>((&(((float*)buf_dyn_shmem)[((((i_b & 1) * 1024) + (((int)threadIdx.x) * 4)) + 17920)])), (&(weight_fused[((((((int)threadIdx.x) >> 6) * 7168) + (i_b * 256)) + ((((int)threadIdx.x) & 63) * 4))])));
      tl::cp_async_commit();
      tl::cp_async_wait<3>();
      bfloat16_t broadcast_var_6 = bfloat16_t(0x0p+0f/*0.000000e+00*/);
      float4 __8;
      uint2 condval_4;
      if (((1 <= ((((tl::get_lane_idx() >> 5) + (tl::get_warp_idx() & 1)) >> 1) + i_b)) && (((((tl::get_lane_idx() >> 5) + (tl::get_warp_idx() & 1)) >> 1) + i_b) < 29))) {
        condval_4 = *(uint2*)(((bfloat16_t*)buf_dyn_shmem) + ((((((((int64_t)tl::get_warp_idx()) >> (int64_t)1) * (int64_t)7168) + (((int64_t)i_b) * (int64_t)256)) + ((((int64_t)tl::get_warp_idx()) & (int64_t)1) * (int64_t)128)) + (((int64_t)tl::get_lane_idx()) * (int64_t)4)) - (int64_t)256));
      } else {
        condval_4 = make_uint2(__pack_nv_bfloat162(broadcast_var_6, broadcast_var_6), __pack_nv_bfloat162(broadcast_var_6, broadcast_var_6));
      }
      ((float2*)(&__8))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&condval_4))[0]);
      ((float2*)(&__8))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&condval_4))[1]);
      *(float4*)(go_x_local + 0) = __8;
      bfloat16_t broadcast_var_7 = bfloat16_t(0x0p+0f/*0.000000e+00*/);
      float4 __9;
      uint2 condval_5;
      if (((0 <= (((tl::get_warp_idx() & 1) * 32) + tl::get_lane_idx())) && (((tl::get_lane_idx() >> 5) + (tl::get_warp_idx() & 1)) < 2))) {
        condval_5 = *(uint2*)(((bfloat16_t*)buf_dyn_shmem) + ((((((((int64_t)i_b) + (int64_t)1) & (int64_t)1) * (int64_t)1024) + (((int64_t)tl::get_warp_idx()) * (int64_t)128)) + (((int64_t)tl::get_lane_idx()) * (int64_t)4)) + (int64_t)41984));
      } else {
        condval_5 = make_uint2(__pack_nv_bfloat162(broadcast_var_7, broadcast_var_7), __pack_nv_bfloat162(broadcast_var_7, broadcast_var_7));
      }
      ((float2*)(&__9))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&condval_5))[0]);
      ((float2*)(&__9))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&condval_5))[1]);
      *(float4*)(x_local + 0) = __9;
      bfloat16_t broadcast_var_8 = bfloat16_t(0x0p+0f/*0.000000e+00*/);
      float4 __10;
      uint2 condval_6;
      if (((0 <= (((tl::get_warp_idx() & 1) * 32) + tl::get_lane_idx())) && (((tl::get_lane_idx() >> 5) + (tl::get_warp_idx() & 1)) < 2))) {
        condval_6 = *(uint2*)(((bfloat16_t*)buf_dyn_shmem) + ((((((((int64_t)i_b) + (int64_t)1) & (int64_t)1) * (int64_t)1024) + (((int64_t)tl::get_warp_idx()) * (int64_t)128)) + (((int64_t)tl::get_lane_idx()) * (int64_t)4)) + (int64_t)39936));
      } else {
        condval_6 = make_uint2(__pack_nv_bfloat162(broadcast_var_8, broadcast_var_8), __pack_nv_bfloat162(broadcast_var_8, broadcast_var_8));
      }
      ((float2*)(&__10))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&condval_6))[0]);
      ((float2*)(&__10))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&condval_6))[1]);
      *(float4*)(k_local + 0) = __10;
      float broadcast_var_9 = 0x0p+0f/*0.000000e+00*/;
      float4 condval_7;
      if (((0 <= (((tl::get_warp_idx() & 1) * 32) + tl::get_lane_idx())) && (((tl::get_lane_idx() >> 5) + (tl::get_warp_idx() & 1)) < 2))) {
        condval_7 = *(float4*)(((float*)buf_dyn_shmem) + ((((((((int64_t)i_b) + (int64_t)1) & (int64_t)1) * (int64_t)1024) + (((int64_t)tl::get_warp_idx()) * (int64_t)128)) + (((int64_t)tl::get_lane_idx()) * (int64_t)4)) + (int64_t)17920));
      } else {
        condval_7 = make_float4(broadcast_var_9, broadcast_var_9, broadcast_var_9, broadcast_var_9);
      }
      *(float4*)(w_fused_local + 0) = condval_7;
      if (1 <= ((((tl::get_lane_idx() >> 5) + (tl::get_warp_idx() & 1)) >> 1) + i_b)) {
        if (((((tl::get_lane_idx() >> 5) + (tl::get_warp_idx() & 1)) >> 1) + i_b) < 29) {
          uint2 __11;
          float4 __12;
            float4 v__5 = make_float4(dldg_r[0], dldg_r[0], dldg_r[0], dldg_r[0]);
            float4 __13;
              float4 __14;
                float4 v__6 = *(float4*)(k_local + 0);
                float4 v__7 = *(float4*)(w_fused_local + 0);
                *(float2*)(&(__14.x)) = tl::mul2(*(float2*)(&(v__6.x)), *(float2*)(&(v__7.x)));
                *(float2*)(&(__14.z)) = tl::mul2(*(float2*)(&(v__6.z)), *(float2*)(&(v__7.z)));
              float4 __15;
                float4 v__8 = *(float4*)(x_local + 0);
                float4 v__9 = make_float4(dot_x_local, dot_x_local, dot_x_local, dot_x_local);
                *(float2*)(&(__15.x)) = tl::mul2(*(float2*)(&(v__8.x)), *(float2*)(&(v__9.x)));
                *(float2*)(&(__15.z)) = tl::mul2(*(float2*)(&(v__8.z)), *(float2*)(&(v__9.z)));
              *(float2*)(&(__13.x)) = tl::sub2(*(float2*)(&(__14.x)), *(float2*)(&(__15.x)));
              *(float2*)(&(__13.z)) = tl::sub2(*(float2*)(&(__14.z)), *(float2*)(&(__15.z)));
            float4 v__10 = *(float4*)(go_x_local + 0);
            *(float2*)(&(__12.x)) = tl::fma2(*(float2*)(&(v__5.x)), *(float2*)(&(__13.x)), *(float2*)(&(v__10.x)));
            *(float2*)(&(__12.z)) = tl::fma2(*(float2*)(&(v__5.z)), *(float2*)(&(__13.z)), *(float2*)(&(v__10.z)));
          (reinterpret_cast<__nv_bfloat162*>(&__11))[0] = __float22bfloat162_rn(((float2*)(&__12))[0]);
          (reinterpret_cast<__nv_bfloat162*>(&__11))[1] = __float22bfloat162_rn(((float2*)(&__12))[1]);
          *(uint2*)(grad_x + ((((((((int64_t)i_s) * (int64_t)28672) + ((((int64_t)tl::get_warp_idx()) >> (int64_t)1) * (int64_t)7168)) + (((int64_t)i_b) * (int64_t)256)) + ((((int64_t)tl::get_warp_idx()) & (int64_t)1) * (int64_t)128)) + (((int64_t)tl::get_lane_idx()) * (int64_t)4)) - (int64_t)256)) = __11;
          uint2 __16;
          float4 __17;
            float4 v__11 = make_float4(dldg_r[0], dldg_r[0], dldg_r[0], dldg_r[0]);
            float4 __18;
              float4 __19;
                float4 v__12 = *(float4*)(x_local + 0);
                float4 v__13 = *(float4*)(w_fused_local + 0);
                *(float2*)(&(__19.x)) = tl::mul2(*(float2*)(&(v__12.x)), *(float2*)(&(v__13.x)));
                *(float2*)(&(__19.z)) = tl::mul2(*(float2*)(&(v__12.z)), *(float2*)(&(v__13.z)));
              float4 __20;
                float4 v__14 = *(float4*)(k_local + 0);
                float4 v__15 = make_float4(dot_k_local, dot_k_local, dot_k_local, dot_k_local);
                *(float2*)(&(__20.x)) = tl::mul2(*(float2*)(&(v__14.x)), *(float2*)(&(v__15.x)));
                *(float2*)(&(__20.z)) = tl::mul2(*(float2*)(&(v__14.z)), *(float2*)(&(v__15.z)));
              *(float2*)(&(__18.x)) = tl::sub2(*(float2*)(&(__19.x)), *(float2*)(&(__20.x)));
              *(float2*)(&(__18.z)) = tl::sub2(*(float2*)(&(__19.z)), *(float2*)(&(__20.z)));
            *(float2*)(&(__17.x)) = tl::mul2(*(float2*)(&(v__11.x)), *(float2*)(&(__18.x)));
            *(float2*)(&(__17.z)) = tl::mul2(*(float2*)(&(v__11.z)), *(float2*)(&(__18.z)));
          (reinterpret_cast<__nv_bfloat162*>(&__16))[0] = __float22bfloat162_rn(((float2*)(&__17))[0]);
          (reinterpret_cast<__nv_bfloat162*>(&__16))[1] = __float22bfloat162_rn(((float2*)(&__17))[1]);
          *(uint2*)(grad_k + ((((((((int64_t)i_s) * (int64_t)28672) + ((((int64_t)tl::get_warp_idx()) >> (int64_t)1) * (int64_t)7168)) + (((int64_t)i_b) * (int64_t)256)) + ((((int64_t)tl::get_warp_idx()) & (int64_t)1) * (int64_t)128)) + (((int64_t)tl::get_lane_idx()) * (int64_t)4)) - (int64_t)256)) = __16;
        }
      }
      for (int i_k_4 = 0; i_k_4 < 4; ++i_k_4) {
        grad_w_local[(((i_b * 4) + i_k_4) - 4)] = (grad_w_local[(((i_b * 4) + i_k_4) - 4)] + ((dldg_r[0] * x_local[i_k_4]) * k_local[i_k_4]));
      }
    }
    tl::cp_async_wait<0>();
    __syncthreads();
    if (((i_s + 1) < (((num_tokens + 187) / 188) * (((int)blockIdx.x) + 1))) && ((i_s + 1) < num_tokens)) {
      #pragma unroll
      for (int i_6 = 0; i_6 < 7; ++i_6) {
        tl::cp_async_gs<16>((&(((bfloat16_t*)buf_dyn_shmem)[((((((int)threadIdx.x) >> 6) * 7168) + (i_6 * 512)) + ((((int)threadIdx.x) & 63) * 8))])), (&(grad_out[(((((((int64_t)i_s) * (int64_t)28672) + ((((int64_t)((int)threadIdx.x)) >> (int64_t)6) * (int64_t)7168)) + (((int64_t)i_6) * (int64_t)512)) + ((((int64_t)((int)threadIdx.x)) & (int64_t)63) * (int64_t)8)) + (int64_t)28672)])));
      }
      tl::cp_async_commit();
    }
    bfloat16_t broadcast_var_10 = bfloat16_t(0x0p+0f/*0.000000e+00*/);
    float4 __21;
    uint2 condval_8;
    if (((-1728 <= (((tl::get_warp_idx() & 1) * 32) + tl::get_lane_idx())) && (((tl::get_lane_idx() >> 5) + (tl::get_warp_idx() & 1)) < 2))) {
      condval_8 = *(uint2*)(((bfloat16_t*)buf_dyn_shmem) + (((((((int64_t)tl::get_warp_idx()) >> (int64_t)1) * (int64_t)7168) + ((((int64_t)tl::get_warp_idx()) & (int64_t)1) * (int64_t)128)) + (((int64_t)tl::get_lane_idx()) * (int64_t)4)) + (int64_t)6912));
    } else {
      condval_8 = make_uint2(__pack_nv_bfloat162(broadcast_var_10, broadcast_var_10), __pack_nv_bfloat162(broadcast_var_10, broadcast_var_10));
    }
    ((float2*)(&__21))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&condval_8))[0]);
    ((float2*)(&__21))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&condval_8))[1]);
    *(float4*)(go_x_local + 0) = __21;
    bfloat16_t broadcast_var_11 = bfloat16_t(0x0p+0f/*0.000000e+00*/);
    float4 __22;
    uint2 condval_9;
    if (((0 <= (((tl::get_warp_idx() & 1) * 32) + tl::get_lane_idx())) && (((tl::get_lane_idx() >> 5) + (tl::get_warp_idx() & 1)) < 2))) {
      condval_9 = *(uint2*)(((bfloat16_t*)buf_dyn_shmem) + (((((int64_t)tl::get_warp_idx()) * (int64_t)128) + (((int64_t)tl::get_lane_idx()) * (int64_t)4)) + (int64_t)43008));
    } else {
      condval_9 = make_uint2(__pack_nv_bfloat162(broadcast_var_11, broadcast_var_11), __pack_nv_bfloat162(broadcast_var_11, broadcast_var_11));
    }
    ((float2*)(&__22))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&condval_9))[0]);
    ((float2*)(&__22))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&condval_9))[1]);
    *(float4*)(x_local + 0) = __22;
    bfloat16_t broadcast_var_12 = bfloat16_t(0x0p+0f/*0.000000e+00*/);
    float4 __23;
    uint2 condval_10;
    if (((0 <= (((tl::get_warp_idx() & 1) * 32) + tl::get_lane_idx())) && (((tl::get_lane_idx() >> 5) + (tl::get_warp_idx() & 1)) < 2))) {
      condval_10 = *(uint2*)(((bfloat16_t*)buf_dyn_shmem) + (((((int64_t)tl::get_warp_idx()) * (int64_t)128) + (((int64_t)tl::get_lane_idx()) * (int64_t)4)) + (int64_t)40960));
    } else {
      condval_10 = make_uint2(__pack_nv_bfloat162(broadcast_var_12, broadcast_var_12), __pack_nv_bfloat162(broadcast_var_12, broadcast_var_12));
    }
    ((float2*)(&__23))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&condval_10))[0]);
    ((float2*)(&__23))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&condval_10))[1]);
    *(float4*)(k_local + 0) = __23;
    float broadcast_var_13 = 0x0p+0f/*0.000000e+00*/;
    float4 condval_11;
    if (((0 <= (((tl::get_warp_idx() & 1) * 32) + tl::get_lane_idx())) && (((tl::get_lane_idx() >> 5) + (tl::get_warp_idx() & 1)) < 2))) {
      condval_11 = *(float4*)(((float*)buf_dyn_shmem) + (((((int64_t)tl::get_warp_idx()) * (int64_t)128) + (((int64_t)tl::get_lane_idx()) * (int64_t)4)) + (int64_t)18944));
    } else {
      condval_11 = make_float4(broadcast_var_13, broadcast_var_13, broadcast_var_13, broadcast_var_13);
    }
    *(float4*)(w_fused_local + 0) = condval_11;
    if (-1728 <= (((tl::get_warp_idx() & 1) * 32) + tl::get_lane_idx())) {
      if (((tl::get_lane_idx() >> 5) + (tl::get_warp_idx() & 1)) < 2) {
        uint2 __24;
        float4 __25;
          float4 v__16 = make_float4(dldg_r[0], dldg_r[0], dldg_r[0], dldg_r[0]);
          float4 __26;
            float4 __27;
              float4 v__17 = *(float4*)(k_local + 0);
              float4 v__18 = *(float4*)(w_fused_local + 0);
              *(float2*)(&(__27.x)) = tl::mul2(*(float2*)(&(v__17.x)), *(float2*)(&(v__18.x)));
              *(float2*)(&(__27.z)) = tl::mul2(*(float2*)(&(v__17.z)), *(float2*)(&(v__18.z)));
            float4 __28;
              float4 v__19 = *(float4*)(x_local + 0);
              float4 v__20 = make_float4(dot_x_local, dot_x_local, dot_x_local, dot_x_local);
              *(float2*)(&(__28.x)) = tl::mul2(*(float2*)(&(v__19.x)), *(float2*)(&(v__20.x)));
              *(float2*)(&(__28.z)) = tl::mul2(*(float2*)(&(v__19.z)), *(float2*)(&(v__20.z)));
            *(float2*)(&(__26.x)) = tl::sub2(*(float2*)(&(__27.x)), *(float2*)(&(__28.x)));
            *(float2*)(&(__26.z)) = tl::sub2(*(float2*)(&(__27.z)), *(float2*)(&(__28.z)));
          float4 v__21 = *(float4*)(go_x_local + 0);
          *(float2*)(&(__25.x)) = tl::fma2(*(float2*)(&(v__16.x)), *(float2*)(&(__26.x)), *(float2*)(&(v__21.x)));
          *(float2*)(&(__25.z)) = tl::fma2(*(float2*)(&(v__16.z)), *(float2*)(&(__26.z)), *(float2*)(&(v__21.z)));
        (reinterpret_cast<__nv_bfloat162*>(&__24))[0] = __float22bfloat162_rn(((float2*)(&__25))[0]);
        (reinterpret_cast<__nv_bfloat162*>(&__24))[1] = __float22bfloat162_rn(((float2*)(&__25))[1]);
        *(uint2*)(grad_x + (((((((int64_t)i_s) * (int64_t)28672) + ((((int64_t)tl::get_warp_idx()) >> (int64_t)1) * (int64_t)7168)) + ((((int64_t)tl::get_warp_idx()) & (int64_t)1) * (int64_t)128)) + (((int64_t)tl::get_lane_idx()) * (int64_t)4)) + (int64_t)6912)) = __24;
        uint2 __29;
        float4 __30;
          float4 v__22 = make_float4(dldg_r[0], dldg_r[0], dldg_r[0], dldg_r[0]);
          float4 __31;
            float4 __32;
              float4 v__23 = *(float4*)(x_local + 0);
              float4 v__24 = *(float4*)(w_fused_local + 0);
              *(float2*)(&(__32.x)) = tl::mul2(*(float2*)(&(v__23.x)), *(float2*)(&(v__24.x)));
              *(float2*)(&(__32.z)) = tl::mul2(*(float2*)(&(v__23.z)), *(float2*)(&(v__24.z)));
            float4 __33;
              float4 v__25 = *(float4*)(k_local + 0);
              float4 v__26 = make_float4(dot_k_local, dot_k_local, dot_k_local, dot_k_local);
              *(float2*)(&(__33.x)) = tl::mul2(*(float2*)(&(v__25.x)), *(float2*)(&(v__26.x)));
              *(float2*)(&(__33.z)) = tl::mul2(*(float2*)(&(v__25.z)), *(float2*)(&(v__26.z)));
            *(float2*)(&(__31.x)) = tl::sub2(*(float2*)(&(__32.x)), *(float2*)(&(__33.x)));
            *(float2*)(&(__31.z)) = tl::sub2(*(float2*)(&(__32.z)), *(float2*)(&(__33.z)));
          *(float2*)(&(__30.x)) = tl::mul2(*(float2*)(&(v__22.x)), *(float2*)(&(__31.x)));
          *(float2*)(&(__30.z)) = tl::mul2(*(float2*)(&(v__22.z)), *(float2*)(&(__31.z)));
        (reinterpret_cast<__nv_bfloat162*>(&__29))[0] = __float22bfloat162_rn(((float2*)(&__30))[0]);
        (reinterpret_cast<__nv_bfloat162*>(&__29))[1] = __float22bfloat162_rn(((float2*)(&__30))[1]);
        *(uint2*)(grad_k + (((((((int64_t)i_s) * (int64_t)28672) + ((((int64_t)tl::get_warp_idx()) >> (int64_t)1) * (int64_t)7168)) + ((((int64_t)tl::get_warp_idx()) & (int64_t)1) * (int64_t)128)) + (((int64_t)tl::get_lane_idx()) * (int64_t)4)) + (int64_t)6912)) = __29;
      }
    }
    for (int i_k_5 = 0; i_k_5 < 4; ++i_k_5) {
      grad_w_local[(i_k_5 + 108)] = (grad_w_local[(i_k_5 + 108)] + ((dldg_r[0] * x_local[i_k_5]) * k_local[i_k_5]));
    }
  }
  #pragma unroll
  for (int i_reg = 0; i_reg < 28; ++i_reg) {
    if (0 <= (((i_reg * 64) + ((tl::get_warp_idx() & 1) * 32)) + tl::get_lane_idx())) {
      if (((((tl::get_lane_idx() >> 5) + (tl::get_warp_idx() & 1)) >> 1) + i_reg) < 28) {
        *(float4*)(grad_w_partial + (((((((int64_t)((int)blockIdx.x)) * (int64_t)28672) + ((((int64_t)tl::get_warp_idx()) >> (int64_t)1) * (int64_t)7168)) + (((int64_t)i_reg) * (int64_t)256)) + ((((int64_t)tl::get_warp_idx()) & (int64_t)1) * (int64_t)128)) + (((int64_t)tl::get_lane_idx()) * (int64_t)4))) = *(float4*)(grad_w_local + (i_reg * 4));
      }
    }
  }
}

