// TileKernels CUDA dump (generated by scripts/dump_cuda_sources.py)
// Source Python: tile_kernels/engram/engram_hash_kernel.py
// JIT factory: get_engram_hash_kernel
// prim_func: engram_hash_kernel
// Compile args: {"args": [], "kwargs": {"max_ngram_size": 3, "num_embed_table_per_ngram": 8, "num_ngram_layers": 2}}
// Public API: tile_kernels.engram.engram_hash
#include <tl_templates/cuda/gemm.h>
#include <tl_templates/cuda/copy.h>
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#include <tl_templates/cuda/debug.h>
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void engram_hash_kernel_kernel(const int64_t* __restrict__ multipliers, const int* __restrict__ ngram_token_ids, const int* __restrict__ offsets, int* __restrict__ output, const int* __restrict__ vocab_sizes, int num_tokens);
extern "C" __global__ void __launch_bounds__(32, 1) engram_hash_kernel_kernel(const int64_t* __restrict__ multipliers, const int* __restrict__ ngram_token_ids, const int* __restrict__ offsets, int* __restrict__ output, const int* __restrict__ vocab_sizes, int num_tokens) {
  int64_t multipliers_local[3];
  int vocab_sizes_local[16];
  int offsets_local[16];
  int x_local[3];
  int64_t hash_local = (int64_t)0;
  int output_local[16];
  if (num_tokens <= ((((int)blockIdx.y) * 32) + ((int)threadIdx.x))) {
    return;
  }
  for (int i = 0; i < 3; ++i) {
    multipliers_local[i] = multipliers[((((int)blockIdx.x) * 3) + i)];
  }
  for (int i_j_fused = 0; i_j_fused < 4; ++i_j_fused) {
    *(int4*)(vocab_sizes_local + (i_j_fused * 4)) = *(int4*)(vocab_sizes + ((((int)blockIdx.x) * 16) + (i_j_fused * 4)));
  }
  for (int i_1 = 0; i_1 < 4; ++i_1) {
    *(int4*)(offsets_local + (i_1 * 4)) = *(int4*)(offsets + ((((int)blockIdx.x) * 16) + (i_1 * 4)));
  }
  for (int i_2 = 0; i_2 < 3; ++i_2) {
    int condval;
    if ((((((int)blockIdx.y) * 32) + ((int)threadIdx.x)) < num_tokens)) {
      condval = ngram_token_ids[(((((int64_t)((int)blockIdx.y)) * (int64_t)96) + (((int64_t)((int)threadIdx.x)) * (int64_t)3)) + ((int64_t)i_2))];
    } else {
      condval = 0;
    }
    x_local[i_2] = condval;
  }
  hash_local = (int64_t)0;
  #pragma unroll
  for (int ngram_idx = 0; ngram_idx < 3; ++ngram_idx) {
    hash_local = (hash_local ^ (((int64_t)x_local[ngram_idx]) * multipliers_local[ngram_idx]));
    if (0 < ngram_idx) {
      #pragma unroll
      for (int j = 0; j < 8; ++j) {
        int64_t rmod = (hash_local % ((int64_t)vocab_sizes_local[(((ngram_idx * 8) + j) - 8)]));
        output_local[(((ngram_idx * 8) + j) - 8)] = ((int)((((((int64_t)0 <= ((int64_t)vocab_sizes_local[(((ngram_idx * 8) + j) - 8)])) && ((int64_t)0 <= rmod)) || ((((int64_t)vocab_sizes_local[(((ngram_idx * 8) + j) - 8)]) < (int64_t)0) && (rmod <= (int64_t)0))) ? rmod : (rmod + ((int64_t)vocab_sizes_local[(((ngram_idx * 8) + j) - 8)]))) + ((int64_t)offsets_local[(((ngram_idx * 8) + j) - 8)])));
      }
    }
  }
  if (((((int)blockIdx.y) * 32) + ((int)threadIdx.x)) < num_tokens) {
    for (int i_3 = 0; i_3 < 4; ++i_3) {
      *(int4*)(output + ((((((int64_t)((int)blockIdx.y)) * (int64_t)512) + (((int64_t)((int)threadIdx.x)) * (int64_t)16)) + ((((int64_t)((int)blockIdx.x)) * ((int64_t)num_tokens)) * (int64_t)16)) + (((int64_t)i_3) * (int64_t)4))) = *(int4*)(output_local + (i_3 * 4));
    }
  }
}

