// TileKernels CUDA dump (generated by scripts/dump_cuda_sources.py)
// Source Python: tile_kernels/mhc/expand_kernel.py
// JIT factory: expand_to_mhc_fwd_tl
// prim_func: expand_to_mhc_fwd_kernel
// Compile args: {"args": [7168, 4], "kwargs": {}}
// Public API: tile_kernels.modeling.mhc.ops.expand.expand_to_mhc
#include <tl_templates/cuda/gemm.h>
#include <tl_templates/cuda/copy.h>
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#include <tl_templates/cuda/debug.h>
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void expand_to_mhc_fwd_kernel_kernel(bfloat16_t* __restrict__ o, const bfloat16_t* __restrict__ x, int num_tokens);
extern "C" __global__ void __launch_bounds__(128, 1) expand_to_mhc_fwd_kernel_kernel(bfloat16_t* __restrict__ o, const bfloat16_t* __restrict__ x, int num_tokens) {
  bfloat16_t xl[32];
  #pragma unroll
  for (int i = 0; i < 2; ++i) {
    bfloat16_t broadcast_var = bfloat16_t(0x0p+0f/*0.000000e+00*/);
    ulonglong4 condval;
    if (((((((int)blockIdx.x) * 32) + (i * 16)) + (((int)threadIdx.x) >> 3)) < num_tokens)) {
      condval = tl::load_global_256(&(*(ulonglong4*)(x + (((((((int64_t)((int)blockIdx.x)) * (int64_t)229376) + (((int64_t)i) * (int64_t)114688)) + ((((int64_t)((int)threadIdx.x)) >> (int64_t)3) * (int64_t)7168)) + (((int64_t)((int)blockIdx.y)) * (int64_t)128)) + ((((int64_t)((int)threadIdx.x)) & (int64_t)7) * (int64_t)16)))));
    } else {
      condval = make_ulonglong4(tl::pack_bfloat16x4(broadcast_var, broadcast_var, broadcast_var, broadcast_var), tl::pack_bfloat16x4(broadcast_var, broadcast_var, broadcast_var, broadcast_var), tl::pack_bfloat16x4(broadcast_var, broadcast_var, broadcast_var, broadcast_var), tl::pack_bfloat16x4(broadcast_var, broadcast_var, broadcast_var, broadcast_var));
    }
    *(ulonglong4*)(xl + (i * 16)) = condval;
  }
  for (int m = 0; m < 4; ++m) {
    #pragma unroll
    for (int i_1 = 0; i_1 < 2; ++i_1) {
      if ((((((int)blockIdx.x) * 32) + (i_1 * 16)) + (((int)threadIdx.x) >> 3)) < num_tokens) {
        tl::store_global_256(&(*(ulonglong4*)(o + ((((((((int64_t)((int)blockIdx.x)) * (int64_t)917504) + (((int64_t)i_1) * (int64_t)458752)) + ((((int64_t)((int)threadIdx.x)) >> (int64_t)3) * (int64_t)28672)) + (((int64_t)m) * (int64_t)7168)) + (((int64_t)((int)blockIdx.y)) * (int64_t)128)) + ((((int64_t)((int)threadIdx.x)) & (int64_t)7) * (int64_t)16)))), *(ulonglong4*)(xl + (i_1 * 16)));
      }
    }
  }
}

