// TileKernels CUDA dump (generated by scripts/dump_cuda_sources.py)
// Source Python: tile_kernels/mhc/expand_kernel.py
// JIT factory: expand_to_mhc_bwd_tl
// prim_func: expand_to_mhc_bwd_kernel
// Compile args: {"args": [7168, 4], "kwargs": {}}
// Public API: tile_kernels.modeling.mhc.ops.expand.expand_to_mhc
#include <tl_templates/cuda/gemm.h>
#include <tl_templates/cuda/copy.h>
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#include <tl_templates/cuda/debug.h>
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void expand_to_mhc_bwd_kernel_kernel(const bfloat16_t* __restrict__ o_grad, bfloat16_t* __restrict__ x_grad, int num_tokens);
extern "C" __global__ void __launch_bounds__(128, 1) expand_to_mhc_bwd_kernel_kernel(const bfloat16_t* __restrict__ o_grad, bfloat16_t* __restrict__ x_grad, int num_tokens) {
  float xgl[32];
  bfloat16_t o_grad_local_cast[16];
  bfloat16_t x_grad_local_cast_1[16];
  #pragma unroll
  for (int i = 0; i < 8; ++i) {
    float broadcast_var = 0x0p+0f/*0.000000e+00*/;
    *(float4*)(xgl + (i * 4)) = make_float4(broadcast_var, broadcast_var, broadcast_var, broadcast_var);
  }
  for (int m = 0; m < 4; ++m) {
    #pragma unroll
    for (int i_1 = 0; i_1 < 2; ++i_1) {
      if ((((((int)blockIdx.x) * 32) + (i_1 * 16)) + (((int)threadIdx.x) >> 3)) < num_tokens) {
        *(ulonglong4*)(o_grad_local_cast + 0) = tl::load_global_256(&(*(ulonglong4*)(o_grad + ((((((((int64_t)((int)blockIdx.x)) * (int64_t)917504) + (((int64_t)i_1) * (int64_t)458752)) + ((((int64_t)((int)threadIdx.x)) >> (int64_t)3) * (int64_t)28672)) + (((int64_t)m) * (int64_t)7168)) + (((int64_t)((int)blockIdx.y)) * (int64_t)128)) + ((((int64_t)((int)threadIdx.x)) & (int64_t)7) * (int64_t)16)))));
        for (int vec = 0; vec < 4; ++vec) {
          float4 __1;
            float4 v_ = *(float4*)(xgl + ((i_1 * 16) + (vec * 4)));
            float4 __2;
            uint2 v__1 = *(uint2*)(o_grad_local_cast + (vec * 4));
            ((float2*)(&__2))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__1))[0]);
            ((float2*)(&__2))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__1))[1]);
            *(float2*)(&(__1.x)) = tl::add2(*(float2*)(&(v_.x)), *(float2*)(&(__2.x)));
            *(float2*)(&(__1.z)) = tl::add2(*(float2*)(&(v_.z)), *(float2*)(&(__2.z)));
          *(float4*)(xgl + ((i_1 * 16) + (vec * 4))) = __1;
        }
      }
    }
  }
  #pragma unroll
  for (int i_2 = 0; i_2 < 2; ++i_2) {
    if ((((((int)blockIdx.x) * 32) + (i_2 * 16)) + (((int)threadIdx.x) >> 3)) < num_tokens) {
      for (int vec_1 = 0; vec_1 < 4; ++vec_1) {
        uint2 __3;
        float4 v__2 = *(float4*)(xgl + ((i_2 * 16) + (vec_1 * 4)));
        (reinterpret_cast<__nv_bfloat162*>(&__3))[0] = __float22bfloat162_rn(((float2*)(&v__2))[0]);
        (reinterpret_cast<__nv_bfloat162*>(&__3))[1] = __float22bfloat162_rn(((float2*)(&v__2))[1]);
        *(uint2*)(x_grad_local_cast_1 + (vec_1 * 4)) = __3;
      }
      tl::store_global_256(&(*(ulonglong4*)(x_grad + (((((((int64_t)((int)blockIdx.x)) * (int64_t)229376) + (((int64_t)i_2) * (int64_t)114688)) + ((((int64_t)((int)threadIdx.x)) >> (int64_t)3) * (int64_t)7168)) + (((int64_t)((int)blockIdx.y)) * (int64_t)128)) + ((((int64_t)((int)threadIdx.x)) & (int64_t)7) * (int64_t)16)))), *(ulonglong4*)(x_grad_local_cast_1 + 0));
    }
  }
}

