// TileKernels CUDA dump (generated by scripts/dump_cuda_sources.py)
// Source Python: tile_kernels/mhc/head_compute_mix_kernel.py
// JIT factory: _mhc_head_compute_mix_bwd
// prim_func: mhc_head_compute_mix_bwd_kernel
// Compile args: {"args": [4, 32, 188], "kwargs": {}}
// Public API: tile_kernels.modeling.mhc.ops.head_compute_mix.mhc_head_compute_mix
#include <tl_templates/cuda/gemm.h>
#include <tl_templates/cuda/copy.h>
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#include <tl_templates/cuda/debug.h>
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void mhc_head_compute_mix_bwd_kernel_kernel(const float* __restrict__ input_mix, float* __restrict__ input_mix_grad, const float* __restrict__ mhc_base, float* __restrict__ mhc_base_grad_partial, const float* __restrict__ mhc_scale, float* __restrict__ mhc_scale_grad_partial, const float* __restrict__ output_mix_grad, int num_tokens);
extern "C" __global__ void __launch_bounds__(128, 1) mhc_head_compute_mix_bwd_kernel_kernel(const float* __restrict__ input_mix, float* __restrict__ input_mix_grad, const float* __restrict__ mhc_base, float* __restrict__ mhc_base_grad_partial, const float* __restrict__ mhc_scale, float* __restrict__ mhc_scale_grad_partial, const float* __restrict__ output_mix_grad, int num_tokens) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  float mhc_scale_grad_reducer[1];
  float mhc_base_grad_reducer[4];
  float input_recompute_frag[1];
  float grad_frag[1];
  mhc_scale_grad_reducer[0] = 0x0p+0f/*0.000000e+00*/;
  float broadcast_var = 0x0p+0f/*0.000000e+00*/;
  *(float4*)(mhc_base_grad_reducer + 0) = make_float4(broadcast_var, broadcast_var, broadcast_var, broadcast_var);
  for (int w = 0; w < ((num_tokens + 6015) / 6016); ++w) {
    if ((((w * 6016) + (((int)blockIdx.x) * 32)) + (((int)threadIdx.x) >> 2)) < num_tokens) {
      input_recompute_frag[0] = (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - ((input_mix[(((((int64_t)w) * (int64_t)24064) + (((int64_t)((int)blockIdx.x)) * (int64_t)128)) + ((int64_t)((int)threadIdx.x)))] * mhc_scale[0]) + mhc_base[(((int)threadIdx.x) & 3)])))));
      grad_frag[0] = ((input_recompute_frag[0] * (0x1p+0f/*1.000000e+00*/ - input_recompute_frag[0])) * output_mix_grad[(((((int64_t)w) * (int64_t)24064) + (((int64_t)((int)blockIdx.x)) * (int64_t)128)) + ((int64_t)((int)threadIdx.x)))]);
      input_mix_grad[(((((int64_t)w) * (int64_t)24064) + (((int64_t)((int)blockIdx.x)) * (int64_t)128)) + ((int64_t)((int)threadIdx.x)))] = (grad_frag[0] * mhc_scale[0]);
      mhc_scale_grad_reducer[0] = (mhc_scale_grad_reducer[0] + (grad_frag[0] * input_mix[(((((int64_t)w) * (int64_t)24064) + (((int64_t)((int)blockIdx.x)) * (int64_t)128)) + ((int64_t)((int)threadIdx.x)))]));
      mhc_base_grad_reducer[(((int)threadIdx.x) & 3)] = (mhc_base_grad_reducer[(((int)threadIdx.x) & 3)] + grad_frag[0]);
    }
  }
  mhc_scale_grad_reducer[0] = tl::AllReduce<tl::SumOp, 128, 1, 0, tl::NamedBarrier<128>>::run(mhc_scale_grad_reducer[0], (&(((float*)buf_dyn_shmem)[0])));
  __syncthreads();
  for (int __finred_0 = 0; __finred_0 < 4; ++__finred_0) {
    mhc_base_grad_reducer[__finred_0] = tl::AllReduce<tl::SumOp, 128, 1, 0, tl::NamedBarrier<128>>::run(mhc_base_grad_reducer[__finred_0], (&(((float*)buf_dyn_shmem)[0])));
  }
  if (((int)threadIdx.x) == 0) {
    mhc_scale_grad_partial[((int)blockIdx.x)] = mhc_scale_grad_reducer[0];
  }
  if ((((int)threadIdx.x) >> 2) == 0) {
    mhc_base_grad_partial[((((int)blockIdx.x) * 4) + (((int)threadIdx.x) & 3))] = mhc_base_grad_reducer[(((int)threadIdx.x) & 3)];
  }
}

