// TileKernels CUDA dump (generated by scripts/dump_cuda_sources.py)
// Source Python: tile_kernels/mhc/head_compute_mix_kernel.py
// JIT factory: _mhc_head_compute_mix_fwd
// prim_func: mhc_head_compute_mix_fwd_kernel
// Compile args: {"args": [4, 1e-06, 32], "kwargs": {}}
// Public API: tile_kernels.modeling.mhc.ops.head_compute_mix.mhc_head_compute_mix
#include <tl_templates/cuda/gemm.h>
#include <tl_templates/cuda/copy.h>
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#include <tl_templates/cuda/debug.h>
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void mhc_head_compute_mix_fwd_kernel_kernel(const float* __restrict__ input_mix, const float* __restrict__ mhc_base, const float* __restrict__ mhc_scale, float* __restrict__ output_mix, int num_tokens);
extern "C" __global__ void __launch_bounds__(128, 1) mhc_head_compute_mix_fwd_kernel_kernel(const float* __restrict__ input_mix, const float* __restrict__ mhc_base, const float* __restrict__ mhc_scale, float* __restrict__ output_mix, int num_tokens) {
  if (((((int)blockIdx.x) * 32) + (((int)threadIdx.x) >> 2)) < num_tokens) {
    output_mix[((((int64_t)((int)blockIdx.x)) * (int64_t)128) + ((int64_t)((int)threadIdx.x)))] = ((0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - ((input_mix[((((int64_t)((int)blockIdx.x)) * (int64_t)128) + ((int64_t)((int)threadIdx.x)))] * mhc_scale[0]) + mhc_base[(((int)threadIdx.x) & 3)]))))) + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/);
  }
}

