// TileKernels CUDA dump (generated by scripts/dump_cuda_sources.py)
// Source Python: tile_kernels/mhc/multilayer_recompute_kernel.py
// JIT factory: _mhc_multilayer_recompute_kernel
// prim_func: kernel
// Compile args: {"args": [4, 7168, 10, 9], "kwargs": {}}
// Public API: tile_kernels.modeling.mhc.ops.multilayer_recompute.mhc_multilayer_recompute
#include <tl_templates/cuda/gemm.h>
#include <tl_templates/cuda/copy.h>
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#include <tl_templates/cuda/debug.h>
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void kernel_kernel(const int64_t* __restrict__ comb_mix_ptrs, const bfloat16_t* __restrict__ initial_residual, const int64_t* __restrict__ layer_input_ptrs, const int64_t* __restrict__ layer_output_ptrs, const int64_t* __restrict__ post_mix_ptrs, const int64_t* __restrict__ pre_mix_ptrs, const int64_t* __restrict__ residual_ptrs, int num_tokens);
extern "C" __global__ void __launch_bounds__(64, 1) kernel_kernel(const int64_t* __restrict__ comb_mix_ptrs, const bfloat16_t* __restrict__ initial_residual, const int64_t* __restrict__ layer_input_ptrs, const int64_t* __restrict__ layer_output_ptrs, const int64_t* __restrict__ post_mix_ptrs, const int64_t* __restrict__ pre_mix_ptrs, const int64_t* __restrict__ residual_ptrs, int num_tokens) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  float res_local[64];
  bfloat16_t initial_residual_local_cast[8];
  float pre_mix_local[4];
  float layer_input_local[16];
  float post_mix_local[4];
  float comb_mix_local[16];
  float layer_output_local[16];
  float new_res_local[64];
  bfloat16_t layer_input_tensor_local_cast_1[8];
  bfloat16_t layer_output_shared_local_cast_2[8];
  bfloat16_t output_residual_tensor_local_cast_3[8];
  bfloat16_t layer_input_tensor_last_local_cast_4[8];
  for (int i0_h = 0; i0_h < 7; ++i0_h) {
    #pragma unroll
    for (int i = 0; i < 8; ++i) {
      *(uint4*)(initial_residual_local_cast + 0) = *(uint4*)(initial_residual + (((((((int64_t)((int)blockIdx.x)) * (int64_t)28672) + ((((int64_t)i) >> (int64_t)1) * (int64_t)7168)) + (((int64_t)i0_h) * (int64_t)1024)) + ((((int64_t)i) & (int64_t)1) * (int64_t)512)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8)));
      for (int vec = 0; vec < 2; ++vec) {
        float4 __1;
        uint2 v_ = *(uint2*)(initial_residual_local_cast + (vec * 4));
        ((float2*)(&__1))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[0]);
        ((float2*)(&__1))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[1]);
        *(float4*)(res_local + ((i * 8) + (vec * 4))) = __1;
      }
    }
    int64_t v__1 = layer_output_ptrs[0];
    void* layer_output_tensor_0 = (*(void* *)(&(v__1)));
    int64_t v__2 = pre_mix_ptrs[0];
    void* pre_mix_tensor_0 = (*(void* *)(&(v__2)));
    int64_t v__3 = post_mix_ptrs[0];
    void* post_mix_tensor_0 = (*(void* *)(&(v__3)));
    int64_t v__4 = comb_mix_ptrs[0];
    void* comb_mix_tensor_0 = (*(void* *)(&(v__4)));
    __syncthreads();
    #pragma unroll
    for (int i_1 = 0; i_1 < 2; ++i_1) {
      tl::cp_async_gs<16>((&(((bfloat16_t*)buf_dyn_shmem)[((i_1 * 512) + (((int)threadIdx.x) * 8))])), (&(((bfloat16_t*)layer_output_tensor_0)[((((((int64_t)((int)blockIdx.x)) * (int64_t)7168) + (((int64_t)i0_h) * (int64_t)1024)) + (((int64_t)i_1) * (int64_t)512)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8))])));
    }
    tl::cp_async_commit();
    if (((int)threadIdx.x) < 4) {
      tl::cp_async_gs<4>((&(((float*)buf_dyn_shmem)[(((int)threadIdx.x) + 1064)])), (&(((float*)pre_mix_tensor_0)[((((int64_t)((int)blockIdx.x)) * (int64_t)4) + ((int64_t)((int)threadIdx.x)))])));
    }
    tl::cp_async_commit();
    if (((int)threadIdx.x) < 4) {
      tl::cp_async_gs<4>((&(((float*)buf_dyn_shmem)[(((int)threadIdx.x) + 1056)])), (&(((float*)post_mix_tensor_0)[((((int64_t)((int)blockIdx.x)) * (int64_t)4) + ((int64_t)((int)threadIdx.x)))])));
    }
    tl::cp_async_commit();
    if (((int)threadIdx.x) < 16) {
      tl::cp_async_gs<4>((&(((float*)buf_dyn_shmem)[(((int)threadIdx.x) + 1024)])), (&(((float*)comb_mix_tensor_0)[((((int64_t)((int)blockIdx.x)) * (int64_t)16) + ((int64_t)((int)threadIdx.x)))])));
    }
    tl::cp_async_commit();
    for (int i_layer = 0; i_layer < 9; ++i_layer) {
      int64_t v__5 = layer_input_ptrs[i_layer];
      void* layer_input_tensor = (*(void* *)(&(v__5)));
      int64_t v__6 = residual_ptrs[i_layer];
      void* output_residual_tensor = (*(void* *)(&(v__6)));
      __syncthreads();
      if (i_layer < 8) {
        int64_t v__7 = layer_output_ptrs[(i_layer + 1)];
        void* next_layer_output_tensor = (*(void* *)(&(v__7)));
        int64_t v__8 = pre_mix_ptrs[(i_layer + 1)];
        void* next_pre_mix_tensor = (*(void* *)(&(v__8)));
        int64_t v__9 = post_mix_ptrs[(i_layer + 1)];
        void* next_post_mix_tensor = (*(void* *)(&(v__9)));
        int64_t v__10 = comb_mix_ptrs[(i_layer + 1)];
        void* next_comb_mix_tensor = (*(void* *)(&(v__10)));
        #pragma unroll
        for (int i_2 = 0; i_2 < 2; ++i_2) {
          tl::cp_async_gs<16>((&(((bfloat16_t*)buf_dyn_shmem)[((((i_2 * 512) + (((int)threadIdx.x) * 8)) + 1024) - ((i_layer & 1) * 1024))])), (&(((bfloat16_t*)next_layer_output_tensor)[((((((int64_t)((int)blockIdx.x)) * (int64_t)7168) + (((int64_t)i0_h) * (int64_t)1024)) + (((int64_t)i_2) * (int64_t)512)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8))])));
        }
        tl::cp_async_commit();
        if (((int)threadIdx.x) < 4) {
          tl::cp_async_gs<4>((&(((float*)buf_dyn_shmem)[((((int)threadIdx.x) + 1068) - ((i_layer & 1) * 4))])), (&(((float*)next_pre_mix_tensor)[((((int64_t)((int)blockIdx.x)) * (int64_t)4) + ((int64_t)((int)threadIdx.x)))])));
        }
        tl::cp_async_commit();
        if (((int)threadIdx.x) < 4) {
          tl::cp_async_gs<4>((&(((float*)buf_dyn_shmem)[((((int)threadIdx.x) + 1060) - ((i_layer & 1) * 4))])), (&(((float*)next_post_mix_tensor)[((((int64_t)((int)blockIdx.x)) * (int64_t)4) + ((int64_t)((int)threadIdx.x)))])));
        }
        tl::cp_async_commit();
        if (((int)threadIdx.x) < 16) {
          tl::cp_async_gs<4>((&(((float*)buf_dyn_shmem)[((((int)threadIdx.x) + 1040) - ((i_layer & 1) * 16))])), (&(((float*)next_comb_mix_tensor)[((((int64_t)((int)blockIdx.x)) * (int64_t)16) + ((int64_t)((int)threadIdx.x)))])));
        }
        tl::cp_async_commit();
      }
      if (i_layer < 8) {
        tl::cp_async_wait<4>();
      } else {
        tl::cp_async_wait<0>();
      }
      __syncthreads();
      *(float4*)(pre_mix_local + 0) = *(float4*)(((float*)buf_dyn_shmem) + (((i_layer & 1) * 4) + 1064));
      #pragma unroll
      for (int i_3 = 0; i_3 < 4; ++i_3) {
        float broadcast_var = 0x0p+0f/*0.000000e+00*/;
        *(float4*)(layer_input_local + (i_3 * 4)) = make_float4(broadcast_var, broadcast_var, broadcast_var, broadcast_var);
      }
      for (int i_mhc = 0; i_mhc < 4; ++i_mhc) {
        #pragma unroll
        for (int i_4 = 0; i_4 < 16; ++i_4) {
          layer_input_local[i_4] = (layer_input_local[i_4] + (pre_mix_local[i_mhc] * res_local[((i_mhc * 16) + i_4)]));
        }
      }
      #pragma unroll
      for (int i_5 = 0; i_5 < 2; ++i_5) {
        for (int vec_1 = 0; vec_1 < 2; ++vec_1) {
          uint2 __2;
          float4 v__11 = *(float4*)(layer_input_local + ((i_5 * 8) + (vec_1 * 4)));
          (reinterpret_cast<__nv_bfloat162*>(&__2))[0] = __float22bfloat162_rn(((float2*)(&v__11))[0]);
          (reinterpret_cast<__nv_bfloat162*>(&__2))[1] = __float22bfloat162_rn(((float2*)(&v__11))[1]);
          *(uint2*)(layer_input_tensor_local_cast_1 + (vec_1 * 4)) = __2;
        }
        *(uint4*)(((bfloat16_t*)layer_input_tensor) + ((((((int64_t)((int)blockIdx.x)) * (int64_t)7168) + (((int64_t)i0_h) * (int64_t)1024)) + (((int64_t)i_5) * (int64_t)512)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8))) = *(uint4*)(layer_input_tensor_local_cast_1 + 0);
      }
      *(float4*)(post_mix_local + 0) = *(float4*)(((float*)buf_dyn_shmem) + (((i_layer & 1) * 4) + 1056));
      #pragma unroll
      for (int i_6 = 0; i_6 < 4; ++i_6) {
        *(float4*)(comb_mix_local + (i_6 * 4)) = *(float4*)(((float*)buf_dyn_shmem) + ((((i_layer & 1) * 16) + (i_6 * 4)) + 1024));
      }
      #pragma unroll
      for (int i_7 = 0; i_7 < 2; ++i_7) {
        *(uint4*)(layer_output_shared_local_cast_2 + 0) = *(uint4*)(((bfloat16_t*)buf_dyn_shmem) + ((((i_layer & 1) * 1024) + (i_7 * 512)) + (((int)threadIdx.x) * 8)));
        for (int vec_2 = 0; vec_2 < 2; ++vec_2) {
          float4 __3;
          uint2 v__12 = *(uint2*)(layer_output_shared_local_cast_2 + (vec_2 * 4));
          ((float2*)(&__3))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__12))[0]);
          ((float2*)(&__3))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__12))[1]);
          *(float4*)(layer_output_local + ((i_7 * 8) + (vec_2 * 4))) = __3;
        }
      }
      #pragma unroll
      for (int i_8 = 0; i_8 < 64; ++i_8) {
        new_res_local[i_8] = (post_mix_local[(i_8 >> 4)] * layer_output_local[(i_8 & 15)]);
        for (int i_mhci = 0; i_mhci < 4; ++i_mhci) {
          new_res_local[i_8] = (new_res_local[i_8] + (comb_mix_local[((i_mhci * 4) + (i_8 >> 4))] * res_local[((i_mhci * 16) + (i_8 & 15))]));
        }
      }
      #pragma unroll
      for (int i_9 = 0; i_9 < 8; ++i_9) {
        for (int vec_3 = 0; vec_3 < 2; ++vec_3) {
          uint2 __4;
          float4 v__13 = *(float4*)(new_res_local + ((i_9 * 8) + (vec_3 * 4)));
          (reinterpret_cast<__nv_bfloat162*>(&__4))[0] = __float22bfloat162_rn(((float2*)(&v__13))[0]);
          (reinterpret_cast<__nv_bfloat162*>(&__4))[1] = __float22bfloat162_rn(((float2*)(&v__13))[1]);
          *(uint2*)(output_residual_tensor_local_cast_3 + (vec_3 * 4)) = __4;
        }
        *(uint4*)(((bfloat16_t*)output_residual_tensor) + (((((((int64_t)((int)blockIdx.x)) * (int64_t)28672) + ((((int64_t)i_9) >> (int64_t)1) * (int64_t)7168)) + (((int64_t)i0_h) * (int64_t)1024)) + ((((int64_t)i_9) & (int64_t)1) * (int64_t)512)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8))) = *(uint4*)(output_residual_tensor_local_cast_3 + 0);
      }
      #pragma unroll
      for (int i_10 = 0; i_10 < 16; ++i_10) {
        float4 __5;
        uint2 __6;
        float4 v__14 = *(float4*)(new_res_local + (i_10 * 4));
        (reinterpret_cast<__nv_bfloat162*>(&__6))[0] = __float22bfloat162_rn(((float2*)(&v__14))[0]);
        (reinterpret_cast<__nv_bfloat162*>(&__6))[1] = __float22bfloat162_rn(((float2*)(&v__14))[1]);
        ((float2*)(&__5))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&__6))[0]);
        ((float2*)(&__5))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&__6))[1]);
        *(float4*)(res_local + (i_10 * 4)) = __5;
      }
    }
    int64_t v__15 = pre_mix_ptrs[9];
    void* pre_mix_tensor_last = (*(void* *)(&(v__15)));
    int64_t v__16 = layer_input_ptrs[9];
    void* layer_input_tensor_last = (*(void* *)(&(v__16)));
    *(float4*)(pre_mix_local + 0) = *(float4*)(((float*)pre_mix_tensor_last) + (((int64_t)((int)blockIdx.x)) * (int64_t)4));
    #pragma unroll
    for (int i_11 = 0; i_11 < 4; ++i_11) {
      float broadcast_var_1 = 0x0p+0f/*0.000000e+00*/;
      *(float4*)(layer_input_local + (i_11 * 4)) = make_float4(broadcast_var_1, broadcast_var_1, broadcast_var_1, broadcast_var_1);
    }
    for (int i_mhc_1 = 0; i_mhc_1 < 4; ++i_mhc_1) {
      #pragma unroll
      for (int i_12 = 0; i_12 < 16; ++i_12) {
        layer_input_local[i_12] = (layer_input_local[i_12] + (pre_mix_local[i_mhc_1] * res_local[((i_mhc_1 * 16) + i_12)]));
      }
    }
    #pragma unroll
    for (int i_13 = 0; i_13 < 2; ++i_13) {
      for (int vec_4 = 0; vec_4 < 2; ++vec_4) {
        uint2 __7;
        float4 v__17 = *(float4*)(layer_input_local + ((i_13 * 8) + (vec_4 * 4)));
        (reinterpret_cast<__nv_bfloat162*>(&__7))[0] = __float22bfloat162_rn(((float2*)(&v__17))[0]);
        (reinterpret_cast<__nv_bfloat162*>(&__7))[1] = __float22bfloat162_rn(((float2*)(&v__17))[1]);
        *(uint2*)(layer_input_tensor_last_local_cast_4 + (vec_4 * 4)) = __7;
      }
      *(uint4*)(((bfloat16_t*)layer_input_tensor_last) + ((((((int64_t)((int)blockIdx.x)) * (int64_t)7168) + (((int64_t)i0_h) * (int64_t)1024)) + (((int64_t)i_13) * (int64_t)512)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8))) = *(uint4*)(layer_input_tensor_last_local_cast_4 + 0);
    }
  }
}

