// TileKernels CUDA dump (generated by scripts/dump_cuda_sources.py)
// Source Python: tile_kernels/mhc/norm_fn_kernel.py
// JIT factory: _mhc_pre_norm_fn_bwd_norm
// prim_func: _mhc_pre_norm_fn_bwd_norm_kernel
// Compile args: {"args": [24, 1, 28672, 1e-06], "kwargs": {}}
// Public API: tile_kernels.modeling.mhc.ops.norm_fn.mhc_pre_norm_fn
#include <tl_templates/cuda/gemm.h>
#include <tl_templates/cuda/copy.h>
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#include <tl_templates/cuda/debug.h>
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void _mhc_pre_norm_fn_bwd_norm_kernel_kernel(const float* __restrict__ out_grad, const float* __restrict__ out_mul, float* __restrict__ out_mul_grad, const float* __restrict__ sqrsum, float* __restrict__ sqrsum_grad, int num_tokens);
extern "C" __global__ void __launch_bounds__(32, 1) _mhc_pre_norm_fn_bwd_norm_kernel_kernel(const float* __restrict__ out_grad, const float* __restrict__ out_mul, float* __restrict__ out_mul_grad, const float* __restrict__ sqrsum, float* __restrict__ sqrsum_grad, int num_tokens) {
  float sqrsum_frag[1];
  float rms_frag[1];
  float rms_grad_frag[1];
  extern __shared__ __align__(1024) float workspace[];
  sqrsum_frag[0] = sqrsum[((int64_t)((int)blockIdx.x))];
  rms_frag[0] = rsqrtf(((sqrsum_frag[0] / 0x1.cp+14f/*2.867200e+04*/) + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/));
  rms_grad_frag[0] = 0x0p+0f/*0.000000e+00*/;
  if (((int)threadIdx.x) < 24) {
    out_mul_grad[((((int64_t)((int)blockIdx.x)) * (int64_t)24) + ((int64_t)((int)threadIdx.x)))] = (out_grad[((((int64_t)((int)blockIdx.x)) * (int64_t)24) + ((int64_t)((int)threadIdx.x)))] * rms_frag[0]);
    rms_grad_frag[0] = (rms_grad_frag[0] + (out_grad[((((int64_t)((int)blockIdx.x)) * (int64_t)24) + ((int64_t)((int)threadIdx.x)))] * out_mul[((((int64_t)((int)blockIdx.x)) * (int64_t)24) + ((int64_t)((int)threadIdx.x)))]));
  }
  rms_grad_frag[0] = tl::AllReduce<tl::SumOp, 32, 1, 0, tl::NamedBarrier<32>>::run(rms_grad_frag[0], (&(workspace[0])));
  if (((int)threadIdx.x) == 0) {
    sqrsum_grad[((int64_t)((int)blockIdx.x))] = (((rms_grad_frag[0] * rms_frag[0]) / (sqrsum_frag[0] + 0x1.d5c31593e5fb7p-6f/*2.867200e-02*/)) / -0x1p+1f/*-2.000000e+00*/);
  }
}

