// TileKernels CUDA dump (generated by scripts/dump_cuda_sources.py)
// Source Python: tile_kernels/mhc/norm_fn_kernel.py
// JIT factory: _mhc_pre_norm_fn_bwd_mul
// prim_func: _mhc_pre_norm_fn_bwd_mul_kernel
// Compile args: {"args": [24, 1, 28672], "kwargs": {}}
// Public API: tile_kernels.modeling.mhc.ops.norm_fn.mhc_pre_norm_fn
#include <tl_templates/cuda/instruction/mma.h>
#include <tl_templates/cuda/gemm.h>
#include <tl_templates/cuda/copy.h>
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#include <tl_templates/cuda/debug.h>
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void _mhc_pre_norm_fn_bwd_mul_kernel_kernel(const float* __restrict__ fn, float* __restrict__ fn_grad, const float* __restrict__ out_mul_grad, const float* __restrict__ sqrsum_grad, const bfloat16_t* __restrict__ x, bfloat16_t* __restrict__ x_grad, int num_tokens);
extern "C" __global__ void __launch_bounds__(128, 1) _mhc_pre_norm_fn_bwd_mul_kernel_kernel(const float* __restrict__ fn, float* __restrict__ fn_grad, const float* __restrict__ out_mul_grad, const float* __restrict__ sqrsum_grad, const bfloat16_t* __restrict__ x, bfloat16_t* __restrict__ x_grad, int num_tokens) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  float fn_grad_frag[32];
  bfloat16_t x_local_cast_1[4];
  float x_smem_local_cast[4];
  float x_grad_frag[128];
  bfloat16_t x_grad_local_cast_2[2];
  float sqrsum_grad_frag[8];
  bfloat16_t x_grad_local_cast_3[2];
  #pragma unroll
  for (int i = 0; i < 8; ++i) {
    if (i < 6) {
      *(float4*)(((float*)buf_dyn_shmem) + ((((((((((int)threadIdx.x) & 31) >> 3) * 1024) + (i * 128)) + ((((int)threadIdx.x) >> 5) * 32)) + (((((((int)threadIdx.x) & 7) >> 2) + (i & 1)) & 1) * 16)) + ((((((int)threadIdx.x) >> 6) + ((((int)threadIdx.x) & 3) >> 1)) & 1) * 8)) + (((((((int)threadIdx.x) & 63) >> 5) + (((int)threadIdx.x) & 1)) & 1) * 4))) = *(float4*)(fn + ((((i * 114688) + ((((int)threadIdx.x) >> 5) * 28672)) + (((int)blockIdx.y) * 128)) + ((((int)threadIdx.x) & 31) * 4)));
    } else {
      float broadcast_var = 0x0p+0f/*0.000000e+00*/;
      *(float4*)(((float*)buf_dyn_shmem) + (((((((((((int)threadIdx.x) & 31) >> 3) * 1024) + ((i & 1) * 128)) + ((((int)threadIdx.x) >> 5) * 32)) + (((((((int)threadIdx.x) & 7) >> 2) + (i & 1)) & 1) * 16)) + ((((((int)threadIdx.x) >> 6) + ((((int)threadIdx.x) & 3) >> 1)) & 1) * 8)) + (((((((int)threadIdx.x) & 63) >> 5) + (((int)threadIdx.x) & 1)) & 1) * 4)) + 768)) = make_float4(broadcast_var, broadcast_var, broadcast_var, broadcast_var);
    }
  }
  #pragma unroll
  for (int i_1 = 0; i_1 < 8; ++i_1) {
    float broadcast_var_1 = 0x0p+0f/*0.000000e+00*/;
    *(float4*)(fn_grad_frag + (i_1 * 4)) = make_float4(broadcast_var_1, broadcast_var_1, broadcast_var_1, broadcast_var_1);
  }
  for (int px = 0; px < ((num_tokens + 127) >> 7); ++px) {
    __syncthreads();
    #pragma unroll
    for (int i_2 = 0; i_2 < 32; ++i_2) {
      bfloat16_t broadcast_var_2 = bfloat16_t(0x0p+0f/*0.000000e+00*/);
      uint2 condval;
      if (((((px * 128) + (i_2 * 4)) + (((int)threadIdx.x) >> 5)) < num_tokens)) {
        condval = *(uint2*)(x + (((((((int64_t)px) * (int64_t)3670016) + (((int64_t)i_2) * (int64_t)114688)) + ((((int64_t)((int)threadIdx.x)) >> (int64_t)5) * (int64_t)28672)) + (((int64_t)((int)blockIdx.y)) * (int64_t)128)) + ((((int64_t)((int)threadIdx.x)) & (int64_t)31) * (int64_t)4)));
      } else {
        condval = make_uint2(__pack_nv_bfloat162(broadcast_var_2, broadcast_var_2), __pack_nv_bfloat162(broadcast_var_2, broadcast_var_2));
      }
      *(uint2*)(x_local_cast_1 + 0) = condval;
      float broadcast_var_3 = 0x0p+0f/*0.000000e+00*/;
      float4 condval_1;
      if (((((px * 128) + (i_2 * 4)) + (((int)threadIdx.x) >> 5)) < num_tokens)) {
        float4 __1;
        uint2 v_ = *(uint2*)(x_local_cast_1 + 0);
        ((float2*)(&__1))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[0]);
        ((float2*)(&__1))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[1]);
        condval_1 = __1;
      } else {
        condval_1 = make_float4(broadcast_var_3, broadcast_var_3, broadcast_var_3, broadcast_var_3);
      }
      *(float4*)(x_smem_local_cast + 0) = condval_1;
      *(float4*)(((float*)buf_dyn_shmem) + (((((((((((int)threadIdx.x) & 31) >> 3) * 4096) + (i_2 * 128)) + ((((int)threadIdx.x) >> 5) * 32)) + (((((((int)threadIdx.x) & 7) >> 2) + (i_2 & 1)) & 1) * 16)) + ((((((int)threadIdx.x) >> 6) + ((((int)threadIdx.x) & 3) >> 1)) & 1) * 8)) + (((((((int)threadIdx.x) & 63) >> 5) + (((int)threadIdx.x) & 1)) & 1) * 4)) + 4096)) = *(float4*)(x_smem_local_cast + 0);
    }
    #pragma unroll
    for (int i_3 = 0; i_3 < 8; ++i_3) {
      if ((((int)threadIdx.x) & 7) < 6) {
        float broadcast_var_4 = 0x0p+0f/*0.000000e+00*/;
        float4 condval_2;
        if (((((px * 128) + (i_3 * 16)) + (((int)threadIdx.x) >> 3)) < num_tokens)) {
          condval_2 = *(float4*)(out_mul_grad + ((((((int64_t)px) * (int64_t)3072) + (((int64_t)i_3) * (int64_t)384)) + ((((int64_t)((int)threadIdx.x)) >> (int64_t)3) * (int64_t)24)) + ((((int64_t)((int)threadIdx.x)) & (int64_t)7) * (int64_t)4)));
        } else {
          condval_2 = make_float4(broadcast_var_4, broadcast_var_4, broadcast_var_4, broadcast_var_4);
        }
        *(float4*)(((float*)buf_dyn_shmem) + ((((((i_3 * 512) + ((((int)threadIdx.x) >> 3) * 32)) + (((((((int)threadIdx.x) & 63) >> 5) + ((((int)threadIdx.x) & 7) >> 2)) & 1) * 16)) + (((((((int)threadIdx.x) & 31) >> 4) + ((((int)threadIdx.x) & 3) >> 1)) & 1) * 8)) + (((((((int)threadIdx.x) & 15) >> 3) + (((int)threadIdx.x) & 1)) & 1) * 4)) + 20480)) = condval_2;
      } else {
        float broadcast_var_5 = 0x0p+0f/*0.000000e+00*/;
        *(float4*)(((float*)buf_dyn_shmem) + ((((((i_3 * 512) + ((((int)threadIdx.x) >> 3) * 32)) + (((((((int)threadIdx.x) & 63) >> 5) + ((((int)threadIdx.x) & 7) >> 2)) & 1) * 16)) + (((((((int)threadIdx.x) & 31) >> 4) + ((((int)threadIdx.x) & 3) >> 1)) & 1) * 8)) + (((((((int)threadIdx.x) & 15) >> 3) + (((int)threadIdx.x) & 1)) & 1) * 4)) + 20480)) = make_float4(broadcast_var_5, broadcast_var_5, broadcast_var_5, broadcast_var_5);
      }
    }
    #pragma unroll
    for (int i_4 = 0; i_4 < 64; ++i_4) {
      bfloat16_t broadcast_var_6 = bfloat16_t(0x0p+0f/*0.000000e+00*/);
      uint1 condval_3;
      if (((((((px * 128) + (((((int)threadIdx.x) & 63) >> 5) * 64)) + ((i_4 >> 4) * 16)) + ((i_4 & 1) * 8)) + ((((int)threadIdx.x) & 31) >> 2)) < num_tokens)) {
        condval_3 = *(uint1*)(x_grad + (((((((((((int64_t)px) * (int64_t)3670016) + (((((int64_t)((int)threadIdx.x)) & (int64_t)63) >> (int64_t)5) * (int64_t)1835008)) + ((((int64_t)i_4) >> (int64_t)4) * (int64_t)458752)) + ((((int64_t)i_4) & (int64_t)1) * (int64_t)229376)) + (((((int64_t)((int)threadIdx.x)) & (int64_t)31) >> (int64_t)2) * (int64_t)28672)) + (((int64_t)((int)blockIdx.y)) * (int64_t)128)) + ((((int64_t)((int)threadIdx.x)) >> (int64_t)6) * (int64_t)64)) + (((((int64_t)i_4) & (int64_t)15) >> (int64_t)1) * (int64_t)8)) + ((((int64_t)((int)threadIdx.x)) & (int64_t)3) * (int64_t)2)));
      } else {
        condval_3 = make_uint1(__pack_nv_bfloat162(broadcast_var_6, broadcast_var_6));
      }
      *(uint1*)(x_grad_local_cast_2 + 0) = condval_3;
      float broadcast_var_7 = 0x0p+0f/*0.000000e+00*/;
      float2 condval_4;
      if (((((((px * 128) + (((((int)threadIdx.x) & 63) >> 5) * 64)) + ((i_4 >> 4) * 16)) + ((i_4 & 1) * 8)) + ((((int)threadIdx.x) & 31) >> 2)) < num_tokens)) {
        float2 __2;
        uint1 v__1 = *(uint1*)(x_grad_local_cast_2 + 0);
        ((float2*)(&__2))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__1))[0]);
        condval_4 = __2;
      } else {
        condval_4 = make_float2(broadcast_var_7, broadcast_var_7);
      }
      *(float2*)(x_grad_frag + (i_4 * 2)) = condval_4;
    }
    {
      float A_local[4];
      float B_local[16];
      __syncthreads();
      for (int ki = 0; ki < 16; ++ki) {
        for (int j = 0; j < 4; ++j) {
          A_local[j] = ((float*)buf_dyn_shmem)[((((((((ki * 256) + ((j >> 1) * 128)) + ((((int)threadIdx.x) & 3) * 32)) + (((((((int)threadIdx.x) & 63) >> 5) + (j >> 1)) & 1) * 16)) + (((((((int)threadIdx.x) & 3) >> 1) + (j & 1)) & 1) * 8)) + (((((((int)threadIdx.x) & 31) >> 4) + (((int)threadIdx.x) & 1)) & 1) * 4)) + ((((int)threadIdx.x) & 15) >> 2)) + 20480)];
        }
        for (int i_5 = 0; i_5 < 4; ++i_5) {
          for (int j_1 = 0; j_1 < 4; ++j_1) {
            B_local[((i_5 * 4) + j_1)] = ((float*)buf_dyn_shmem)[(((((((((((((int)threadIdx.x) >> 6) * 8192) + ((i_5 >> 1) * 4096)) + (ki * 256)) + ((j_1 & 1) * 128)) + ((((int)threadIdx.x) & 3) * 32)) + ((((i_5 & 1) + (j_1 & 1)) & 1) * 16)) + ((((j_1 >> 1) + ((((int)threadIdx.x) & 3) >> 1)) & 1) * 8)) + (((((((int)threadIdx.x) & 31) >> 4) + (((int)threadIdx.x) & 1)) & 1) * 4)) + ((((int)threadIdx.x) & 15) >> 2)) + 4096)];
          }
        }
        for (int j_2 = 0; j_2 < 4; ++j_2) {
          tl::mma_sync<tl::DataType::kTensorFloat32, tl::DataType::kTensorFloat32, tl::DataType::kFloat32, 16, 8, 8, false, true>(reinterpret_cast<float*>(fn_grad_frag + (j_2 * 8)), reinterpret_cast<const uint32_t*>(A_local + 0), reinterpret_cast<const uint32_t*>(B_local + (j_2 * 4)));
          tl::mma_sync<tl::DataType::kTensorFloat32, tl::DataType::kTensorFloat32, tl::DataType::kFloat32, 16, 8, 8, false, true>(reinterpret_cast<float*>(fn_grad_frag + ((j_2 * 8) + 4)), reinterpret_cast<const uint32_t*>(A_local + 0), reinterpret_cast<const uint32_t*>(B_local + ((j_2 * 4) + 2)));
        }
      }
    }
    {
      float A_local_1[16];
      float B_local_1[16];
      for (int ki_1 = 0; ki_1 < 4; ++ki_1) {
        for (int i_6 = 0; i_6 < 4; ++i_6) {
          tl::ptx_ldmatrix_x4((&(((float*)buf_dyn_shmem)[(((((((((int)threadIdx.x) & 63) >> 5) * 2048) + (i_6 * 512)) + (((((int)threadIdx.x) & 15) >> 3) * 256)) + ((((((((int)threadIdx.x) & 15) * 32) + (((((((int)threadIdx.x) & 7) >> 2) + (ki_1 >> 1)) & 1) * 16)) + (((((((int)threadIdx.x) & 3) >> 1) + (ki_1 & 1)) & 1) * 8)) + (((((((int)threadIdx.x) & 31) >> 4) + (((int)threadIdx.x) & 1)) & 1) * 4)) & 255)) + 20480)])), (&(A_local_1[(i_6 * 4)])));
        }
        for (int i_7 = 0; i_7 < 4; ++i_7) {
          for (int j_3 = 0; j_3 < 4; ++j_3) {
            B_local_1[((i_7 * 4) + j_3)] = ((float*)buf_dyn_shmem)[((((((((((((int)threadIdx.x) >> 6) * 2048) + ((i_7 >> 1) * 1024)) + (ki_1 * 256)) + ((j_3 & 1) * 128)) + ((((int)threadIdx.x) & 3) * 32)) + ((((i_7 & 1) + (j_3 & 1)) & 1) * 16)) + ((((j_3 >> 1) + ((((int)threadIdx.x) & 3) >> 1)) & 1) * 8)) + (((((((int)threadIdx.x) & 31) >> 4) + (((int)threadIdx.x) & 1)) & 1) * 4)) + ((((int)threadIdx.x) & 15) >> 2))];
          }
        }
        for (int i_8 = 0; i_8 < 4; ++i_8) {
          for (int j_4 = 0; j_4 < 4; ++j_4) {
            tl::mma_sync<tl::DataType::kTensorFloat32, tl::DataType::kTensorFloat32, tl::DataType::kFloat32, 16, 8, 8, false, true>(reinterpret_cast<float*>(x_grad_frag + ((i_8 * 32) + (j_4 * 8))), reinterpret_cast<const uint32_t*>(A_local_1 + (i_8 * 4)), reinterpret_cast<const uint32_t*>(B_local_1 + (j_4 * 4)));
            tl::mma_sync<tl::DataType::kTensorFloat32, tl::DataType::kTensorFloat32, tl::DataType::kFloat32, 16, 8, 8, false, true>(reinterpret_cast<float*>(x_grad_frag + (((i_8 * 32) + (j_4 * 8)) + 4)), reinterpret_cast<const uint32_t*>(A_local_1 + (i_8 * 4)), reinterpret_cast<const uint32_t*>(B_local_1 + ((j_4 * 4) + 2)));
          }
        }
      }
    }
    #pragma unroll
    for (int i_9 = 0; i_9 < 8; ++i_9) {
      float condval_5;
      if ((((((px * 128) + (((((int)threadIdx.x) & 63) >> 5) * 64)) + (i_9 * 8)) + ((((int)threadIdx.x) & 31) >> 2)) < num_tokens)) {
        condval_5 = sqrsum_grad[((((((int64_t)px) * (int64_t)128) + (((((int64_t)((int)threadIdx.x)) & (int64_t)63) >> (int64_t)5) * (int64_t)64)) + (((int64_t)i_9) * (int64_t)8)) + ((((int64_t)((int)threadIdx.x)) & (int64_t)31) >> (int64_t)2))];
      } else {
        condval_5 = 0x0p+0f/*0.000000e+00*/;
      }
      sqrsum_grad_frag[i_9] = condval_5;
    }
    #pragma unroll
    for (int i_10 = 0; i_10 < 64; ++i_10) {
      float broadcast_var_8 = 0x1p+1f/*2.000000e+00*/;
      float2 __3;
        float2 __4;
          float2 v__2 = make_float2(broadcast_var_8, broadcast_var_8);
          float2 v__3 = *(float2*)(((float*)buf_dyn_shmem) + ((((((((((((((int)threadIdx.x) >> 6) * 8192) + (((i_10 & 15) >> 3) * 4096)) + (((((int)threadIdx.x) & 63) >> 5) * 2048)) + ((i_10 >> 4) * 512)) + ((i_10 & 1) * 256)) + (((((int)threadIdx.x) & 31) >> 2) * 32)) + (((((((int)threadIdx.x) & 31) >> 4) + ((i_10 & 7) >> 2)) & 1) * 16)) + (((((((int)threadIdx.x) & 15) >> 3) + ((i_10 & 3) >> 1)) & 1) * 8)) + (((((((int)threadIdx.x) & 7) >> 2) + ((((int)threadIdx.x) & 3) >> 1)) & 1) * 4)) + ((((int)threadIdx.x) & 1) * 2)) + 4096));
          *(float2*)(&(__4.x)) = tl::mul2(*(float2*)(&(v__2.x)), *(float2*)(&(v__3.x)));
        float2 v__4 = make_float2(sqrsum_grad_frag[(((i_10 >> 4) * 2) + (i_10 & 1))], sqrsum_grad_frag[(((i_10 >> 4) * 2) + (i_10 & 1))]);
        float2 v__5 = *(float2*)(x_grad_frag + (i_10 * 2));
        *(float2*)(&(__3.x)) = tl::fma2(*(float2*)(&(__4.x)), *(float2*)(&(v__4.x)), *(float2*)(&(v__5.x)));
      *(float2*)(x_grad_frag + (i_10 * 2)) = __3;
    }
    #pragma unroll
    for (int i_11 = 0; i_11 < 64; ++i_11) {
      if ((((((px * 128) + (((((int)threadIdx.x) & 63) >> 5) * 64)) + ((i_11 >> 4) * 16)) + ((i_11 & 1) * 8)) + ((((int)threadIdx.x) & 31) >> 2)) < num_tokens) {
        uint1 __5;
        float2 v__6 = *(float2*)(x_grad_frag + (i_11 * 2));
        (reinterpret_cast<__nv_bfloat162*>(&__5))[0] = __float22bfloat162_rn(((float2*)(&v__6))[0]);
        *(uint1*)(x_grad_local_cast_3 + 0) = __5;
        *(uint1*)(x_grad + (((((((((((int64_t)px) * (int64_t)3670016) + (((((int64_t)((int)threadIdx.x)) & (int64_t)63) >> (int64_t)5) * (int64_t)1835008)) + ((((int64_t)i_11) >> (int64_t)4) * (int64_t)458752)) + ((((int64_t)i_11) & (int64_t)1) * (int64_t)229376)) + (((((int64_t)((int)threadIdx.x)) & (int64_t)31) >> (int64_t)2) * (int64_t)28672)) + (((int64_t)((int)blockIdx.y)) * (int64_t)128)) + ((((int64_t)((int)threadIdx.x)) >> (int64_t)6) * (int64_t)64)) + (((((int64_t)i_11) & (int64_t)15) >> (int64_t)1) * (int64_t)8)) + ((((int64_t)((int)threadIdx.x)) & (int64_t)3) * (int64_t)2))) = *(uint1*)(x_grad_local_cast_3 + 0);
      }
    }
  }
  #pragma unroll
  for (int i_12 = 0; i_12 < 16; ++i_12) {
    if (((((((int)threadIdx.x) & 63) >> 5) * 2) + (i_12 & 1)) < 3) {
      *(float2*)(fn_grad + (((((((((((int)threadIdx.x) & 63) >> 5) * 458752) + ((i_12 & 1) * 229376)) + (((((int)threadIdx.x) & 31) >> 2) * 28672)) + (((int)blockIdx.y) * 128)) + ((((int)threadIdx.x) >> 6) * 64)) + ((i_12 >> 1) * 8)) + ((((int)threadIdx.x) & 3) * 2))) = *(float2*)(fn_grad_frag + (i_12 * 2));
    }
  }
}

