// TileKernels CUDA dump (generated by scripts/dump_cuda_sources.py)
// Source Python: tile_kernels/mhc/norm_fn_kernel.py
// JIT factory: _mhc_pre_norm_fn_fwd_mul
// prim_func: _mhc_pre_norm_fn_fwd_mul_kernel
// Compile args: {"args": [24, 1, 28672], "kwargs": {}}
// Public API: tile_kernels.modeling.mhc.ops.norm_fn.mhc_pre_norm_fn
#include <tl_templates/cuda/instruction/mma.h>
#include <tl_templates/cuda/gemm.h>
#include <tl_templates/cuda/copy.h>
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#include <tl_templates/cuda/debug.h>
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void _mhc_pre_norm_fn_fwd_mul_kernel_kernel(__grid_constant__ const CUtensorMap fn_desc, float* __restrict__ out, float* __restrict__ sqrsum, __grid_constant__ const CUtensorMap x_desc, int num_tokens);
extern "C" __global__ void __launch_bounds__(256, 1) _mhc_pre_norm_fn_fwd_mul_kernel_kernel(__grid_constant__ const CUtensorMap fn_desc, float* __restrict__ out, float* __restrict__ sqrsum, __grid_constant__ const CUtensorMap x_desc, int num_tokens) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  __shared__ __align__(16) uint64_t mbarrier_mem[8];
  auto mbarrier = reinterpret_cast<Barrier*>(mbarrier_mem);
  float out_frag[8];
  float sqrsum_part[2];
  float sqrsum_l[2];
  bfloat16_t x_frag_16[128];
  float x_frag[128];
  if (tl::tl_shuffle_elect<0>()) {
    tl::prefetch_tma_descriptor(x_desc);
    tl::prefetch_tma_descriptor(fn_desc);
  }
  if (tl::tl_shuffle_elect<0>()) {
    mbarrier[0].init(1);
    mbarrier[1].init(1);
    mbarrier[2].init(1);
    mbarrier[3].init(1);
    mbarrier[4].init(128);
    mbarrier[5].init(128);
    mbarrier[6].init(128);
    mbarrier[7].init(128);
  }
  tl::fence_barrier_init();
  __syncthreads();
  if (128 <= ((int)threadIdx.x)) {
    tl::warpgroup_reg_dealloc<24>();
    for (int pz = 0; pz < 112; ++pz) {
      mbarrier[((pz & 1) + 4)].wait((((pz & 3) >> 1) ^ 1));
      if (tl::tl_shuffle_elect<128>()) {
        mbarrier[(pz & 1)].arrive_and_expect_tx(16384);
        tl::tma_load(x_desc, mbarrier[(pz & 1)], (&(((bfloat16_t*)buf_dyn_shmem)[(((pz & 1) * 8192) + 32768)])), (pz * 256), (((int)blockIdx.x) * 32));
        tl::tma_load(x_desc, mbarrier[(pz & 1)], (&(((bfloat16_t*)buf_dyn_shmem)[(((pz & 1) * 8192) + 34816)])), ((pz * 256) + 64), (((int)blockIdx.x) * 32));
        tl::tma_load(x_desc, mbarrier[(pz & 1)], (&(((bfloat16_t*)buf_dyn_shmem)[(((pz & 1) * 8192) + 36864)])), ((pz * 256) + 128), (((int)blockIdx.x) * 32));
        tl::tma_load(x_desc, mbarrier[(pz & 1)], (&(((bfloat16_t*)buf_dyn_shmem)[(((pz & 1) * 8192) + 38912)])), ((pz * 256) + 192), (((int)blockIdx.x) * 32));
      }
      mbarrier[((pz & 1) + 6)].wait((((pz & 3) >> 1) ^ 1));
      if (tl::tl_shuffle_elect<128>()) {
        mbarrier[((pz & 1) + 2)].arrive_and_expect_tx(32768);
        tl::tma_load(fn_desc, mbarrier[((pz & 1) + 2)], (&(((float*)buf_dyn_shmem)[((pz & 1) * 8192)])), (pz * 256), 0);
        tl::tma_load(fn_desc, mbarrier[((pz & 1) + 2)], (&(((float*)buf_dyn_shmem)[(((pz & 1) * 8192) + 1024)])), ((pz * 256) + 32), 0);
        tl::tma_load(fn_desc, mbarrier[((pz & 1) + 2)], (&(((float*)buf_dyn_shmem)[(((pz & 1) * 8192) + 2048)])), ((pz * 256) + 64), 0);
        tl::tma_load(fn_desc, mbarrier[((pz & 1) + 2)], (&(((float*)buf_dyn_shmem)[(((pz & 1) * 8192) + 3072)])), ((pz * 256) + 96), 0);
        tl::tma_load(fn_desc, mbarrier[((pz & 1) + 2)], (&(((float*)buf_dyn_shmem)[(((pz & 1) * 8192) + 4096)])), ((pz * 256) + 128), 0);
        tl::tma_load(fn_desc, mbarrier[((pz & 1) + 2)], (&(((float*)buf_dyn_shmem)[(((pz & 1) * 8192) + 5120)])), ((pz * 256) + 160), 0);
        tl::tma_load(fn_desc, mbarrier[((pz & 1) + 2)], (&(((float*)buf_dyn_shmem)[(((pz & 1) * 8192) + 6144)])), ((pz * 256) + 192), 0);
        tl::tma_load(fn_desc, mbarrier[((pz & 1) + 2)], (&(((float*)buf_dyn_shmem)[(((pz & 1) * 8192) + 7168)])), ((pz * 256) + 224), 0);
      }
    }
  } else {
    tl::warpgroup_reg_alloc<240>();
    #pragma unroll
    for (int i = 0; i < 2; ++i) {
      float broadcast_var = 0x0p+0f/*0.000000e+00*/;
      *(float4*)(out_frag + (i * 4)) = make_float4(broadcast_var, broadcast_var, broadcast_var, broadcast_var);
    }
    float broadcast_var_1 = 0x0p+0f/*0.000000e+00*/;
    *(float2*)(sqrsum_part + 0) = make_float2(broadcast_var_1, broadcast_var_1);
    for (int pz_1 = 0; pz_1 < 112; ++pz_1) {
      mbarrier[(pz_1 & 1)].wait(((pz_1 & 3) >> 1));
      #pragma unroll
      for (int i_1 = 0; i_1 < 128; ++i_1) {
        x_frag_16[i_1] = ((bfloat16_t*)buf_dyn_shmem)[((((((((((((pz_1 & 1) * 8192) + ((i_1 >> 5) * 2048)) + (((((int)threadIdx.x) & 63) >> 5) * 1024)) + ((i_1 & 1) * 512)) + (((((int)threadIdx.x) & 31) >> 2) * 64)) + (((((i_1 & 31) >> 4) + ((((int)threadIdx.x) & 31) >> 4)) & 1) * 32)) + (((((i_1 & 15) >> 3) + ((((int)threadIdx.x) & 15) >> 3)) & 1) * 16)) + (((((i_1 & 7) >> 2) + ((((int)threadIdx.x) & 7) >> 2)) & 1) * 8)) + (((i_1 & 3) >> 1) * 4)) + (((int)threadIdx.x) & 3)) + 32768)];
      }
      mbarrier[((pz_1 & 1) + 4)].arrive();
      #pragma unroll
      for (int i_2 = 0; i_2 < 32; ++i_2) {
        float4 __1;
        uint2 v_ = *(uint2*)(x_frag_16 + (i_2 * 4));
        ((float2*)(&__1))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[0]);
        ((float2*)(&__1))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[1]);
        *(float4*)(x_frag + (i_2 * 4)) = __1;
      }
      for (int jj = 0; jj < 64; ++jj) {
        #pragma unroll
        for (int i_3 = 0; i_3 < 2; ++i_3) {
          sqrsum_part[i_3] = (sqrsum_part[i_3] + (x_frag[((jj * 2) + i_3)] * x_frag[((jj * 2) + i_3)]));
        }
      }
      mbarrier[((pz_1 & 1) + 2)].wait(((pz_1 & 3) >> 1));
      {
        float B_local[4];
        for (int ki = 0; ki < 32; ++ki) {
          tl::ptx_ldmatrix_x4((&(((float*)buf_dyn_shmem)[(((((((((pz_1 & 1) * 8192) + ((ki >> 2) * 1024)) + ((((int)threadIdx.x) >> 6) * 512)) + (((((int)threadIdx.x) & 31) >> 4) * 256)) + ((((int)threadIdx.x) & 7) * 32)) + (((((((int)threadIdx.x) & 7) >> 2) + ((ki & 3) >> 1)) & 1) * 16)) + (((((((int)threadIdx.x) & 3) >> 1) + (ki & 1)) & 1) * 8)) + (((((((int)threadIdx.x) & 15) >> 3) + (((int)threadIdx.x) & 1)) & 1) * 4))])), (&(B_local[0])));
          tl::mma_sync<tl::DataType::kTensorFloat32, tl::DataType::kTensorFloat32, tl::DataType::kFloat32, 16, 8, 8, false, true>(reinterpret_cast<float*>(out_frag + 0), reinterpret_cast<const uint32_t*>(x_frag + (ki * 4)), reinterpret_cast<const uint32_t*>(B_local + 0));
          tl::mma_sync<tl::DataType::kTensorFloat32, tl::DataType::kTensorFloat32, tl::DataType::kFloat32, 16, 8, 8, false, true>(reinterpret_cast<float*>(out_frag + 4), reinterpret_cast<const uint32_t*>(x_frag + (ki * 4)), reinterpret_cast<const uint32_t*>(B_local + 2));
        }
      }
      mbarrier[((pz_1 & 1) + 6)].arrive();
    }
    #pragma unroll
    for (int i_4 = 0; i_4 < 2; ++i_4) {
      sqrsum_l[i_4] = 0x0p+0f/*0.000000e+00*/;
      sqrsum_l[i_4] = (sqrsum_l[i_4] + sqrsum_part[i_4]);
      sqrsum_l[i_4] = tl::AllReduce<tl::SumOp, 4, 1, 0, tl::NamedBarrier<128>>::run(sqrsum_l[i_4]);
    }
    if ((((((int)threadIdx.x) & 3) * 2) + (((int)threadIdx.x) >> 6)) == 0) {
      #pragma unroll
      for (int i_5 = 0; i_5 < 2; ++i_5) {
        if (((((((int)blockIdx.x) * 32) + (((((int)threadIdx.x) & 63) >> 5) * 16)) + (i_5 * 8)) + ((((int)threadIdx.x) & 31) >> 2)) < num_tokens) {
          sqrsum[((((((int64_t)((int)blockIdx.x)) * (int64_t)32) + (((((int64_t)((int)threadIdx.x)) & (int64_t)63) >> (int64_t)5) * (int64_t)16)) + (((int64_t)i_5) * (int64_t)8)) + ((((int64_t)((int)threadIdx.x)) & (int64_t)31) >> (int64_t)2))] = sqrsum_l[i_5];
        }
      }
    }
    #pragma unroll
    for (int i_6 = 0; i_6 < 4; ++i_6) {
      if ((((((int)threadIdx.x) >> 6) * 2) + (i_6 >> 1)) < 3) {
        if (((((((int)blockIdx.x) * 32) + (((((int)threadIdx.x) & 63) >> 5) * 16)) + ((i_6 & 1) * 8)) + ((((int)threadIdx.x) & 31) >> 2)) < num_tokens) {
          *(float2*)(out + (((((((((int64_t)((int)blockIdx.x)) * (int64_t)768) + (((((int64_t)((int)threadIdx.x)) & (int64_t)63) >> (int64_t)5) * (int64_t)384)) + ((((int64_t)i_6) & (int64_t)1) * (int64_t)192)) + (((((int64_t)((int)threadIdx.x)) & (int64_t)31) >> (int64_t)2) * (int64_t)24)) + ((((int64_t)((int)threadIdx.x)) >> (int64_t)6) * (int64_t)16)) + ((((int64_t)i_6) >> (int64_t)1) * (int64_t)8)) + ((((int64_t)((int)threadIdx.x)) & (int64_t)3) * (int64_t)2))) = *(float2*)(out_frag + (i_6 * 2));
        }
      }
    }
  }
}

