// TileKernels CUDA dump (generated by scripts/dump_cuda_sources.py)
// Source Python: tile_kernels/mhc/norm_fn_kernel.py
// JIT factory: _mhc_pre_norm_fn_fwd_norm
// prim_func: _mhc_pre_norm_fn_fwd_norm_kernel
// Compile args: {"args": [24, 1, 28672, 1e-06, 1], "kwargs": {}}
// Public API: tile_kernels.modeling.mhc.ops.norm_fn.mhc_pre_norm_fn
#include <tl_templates/cuda/gemm.h>
#include <tl_templates/cuda/copy.h>
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#include <tl_templates/cuda/debug.h>
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void _mhc_pre_norm_fn_fwd_norm_kernel_kernel(float* __restrict__ out, float* __restrict__ out_mul, const float* __restrict__ out_mul_splitted, float* __restrict__ sqrsum, const float* __restrict__ sqrsum_splitted, int num_tokens);
extern "C" __global__ void __launch_bounds__(32, 1) _mhc_pre_norm_fn_fwd_norm_kernel_kernel(float* __restrict__ out, float* __restrict__ out_mul, const float* __restrict__ out_mul_splitted, float* __restrict__ sqrsum, const float* __restrict__ sqrsum_splitted, int num_tokens) {
  float out_l[1];
  float rms[1];
  float out_l0[1];
  if (((int)threadIdx.x) < 24) {
    out_l[0] = 0x0p+0f/*0.000000e+00*/;
  }
  rms[0] = 0x0p+0f/*0.000000e+00*/;
  rms[0] = (rms[0] + sqrsum_splitted[((int64_t)((int)blockIdx.x))]);
  if (((int)threadIdx.x) == 0) {
    sqrsum[((int64_t)((int)blockIdx.x))] = rms[0];
  }
  rms[0] = rsqrtf(((rms[0] / 0x1.cp+14f/*2.867200e+04*/) + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/));
  if (((int)threadIdx.x) < 24) {
    out_l0[0] = 0x0p+0f/*0.000000e+00*/;
    out_l0[0] = (out_l0[0] + out_mul_splitted[((((int64_t)((int)blockIdx.x)) * (int64_t)24) + ((int64_t)((int)threadIdx.x)))]);
    out_l[0] = (out_l[0] + (out_l0[0] * rms[0]));
    out_mul[((((int64_t)((int)blockIdx.x)) * (int64_t)24) + ((int64_t)((int)threadIdx.x)))] = out_l0[0];
    out[((((int64_t)((int)blockIdx.x)) * (int64_t)24) + ((int64_t)((int)threadIdx.x)))] = out_l[0];
  }
}

