// TileKernels CUDA dump (generated by scripts/dump_cuda_sources.py)
// Source Python: tile_kernels/mhc/norm_fn_kernel.py
// JIT factory: _mhc_fn_normw_merge_bwd
// prim_func: _mhc_fn_normw_merge_bwd_
// Compile args: {"args": [4096, 28672], "kwargs": {}}
// Public API: tile_kernels.modeling.mhc.ops.norm_fn.mhc_fn_normw_merge
#include <tl_templates/cuda/gemm.h>
#include <tl_templates/cuda/copy.h>
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#include <tl_templates/cuda/debug.h>
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void _mhc_fn_normw_merge_bwd__kernel(const float* __restrict__ fn, float* __restrict__ fn_grad, const float* __restrict__ normw, float* __restrict__ normw_grad, const float* __restrict__ out_fn_grad);
extern "C" __global__ void __launch_bounds__(128, 1) _mhc_fn_normw_merge_bwd__kernel(const float* __restrict__ fn, float* __restrict__ fn_grad, const float* __restrict__ normw, float* __restrict__ normw_grad, const float* __restrict__ out_fn_grad) {
  float normw_frag[2];
  float normw_grad_frag[2];
  *(float2*)(normw_frag + 0) = *(float2*)(normw + ((((int)blockIdx.x) * 256) + (((int)threadIdx.x) * 2)));
  float broadcast_var = 0x0p+0f/*0.000000e+00*/;
  *(float2*)(normw_grad_frag + 0) = make_float2(broadcast_var, broadcast_var);
  for (int i_m = 0; i_m < 4096; ++i_m) {
    float2 __1;
      float2 v_ = *(float2*)(out_fn_grad + (((i_m * 28672) + (((int)blockIdx.x) * 256)) + (((int)threadIdx.x) * 2)));
      float2 v__1 = *(float2*)(normw_frag + 0);
      float2 v__2 = *(float2*)(fn_grad + (((i_m * 28672) + (((int)blockIdx.x) * 256)) + (((int)threadIdx.x) * 2)));
      *(float2*)(&(__1.x)) = tl::fma2(*(float2*)(&(v_.x)), *(float2*)(&(v__1.x)), *(float2*)(&(v__2.x)));
    *(float2*)(fn_grad + (((i_m * 28672) + (((int)blockIdx.x) * 256)) + (((int)threadIdx.x) * 2))) = __1;
    float2 __2;
      float2 v__3 = *(float2*)(out_fn_grad + (((i_m * 28672) + (((int)blockIdx.x) * 256)) + (((int)threadIdx.x) * 2)));
      float2 v__4 = *(float2*)(fn + (((i_m * 28672) + (((int)blockIdx.x) * 256)) + (((int)threadIdx.x) * 2)));
      float2 v__5 = *(float2*)(normw_grad_frag + 0);
      *(float2*)(&(__2.x)) = tl::fma2(*(float2*)(&(v__3.x)), *(float2*)(&(v__4.x)), *(float2*)(&(v__5.x)));
    *(float2*)(normw_grad_frag + 0) = __2;
  }
  float2 __3;
    float2 v__6 = *(float2*)(normw_grad + ((((int)blockIdx.x) * 256) + (((int)threadIdx.x) * 2)));
    float2 v__7 = *(float2*)(normw_grad_frag + 0);
    *(float2*)(&(__3.x)) = tl::add2(*(float2*)(&(v__6.x)), *(float2*)(&(v__7.x)));
  *(float2*)(normw_grad + ((((int)blockIdx.x) * 256) + (((int)threadIdx.x) * 2))) = __3;
}

