// TileKernels CUDA dump (generated by scripts/dump_cuda_sources.py)
// Source Python: tile_kernels/mhc/norm_fn_kernel.py
// JIT factory: _mhc_fn_normw_merge_fwd
// prim_func: _mhc_fn_normw_merge_fwd_
// Compile args: {"args": [4096, 28672], "kwargs": {}}
// Public API: tile_kernels.modeling.mhc.ops.norm_fn.mhc_fn_normw_merge
#include <tl_templates/cuda/gemm.h>
#include <tl_templates/cuda/copy.h>
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#include <tl_templates/cuda/debug.h>
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void _mhc_fn_normw_merge_fwd__kernel(const float* __restrict__ fn, const float* __restrict__ normw, float* __restrict__ out_fn);
extern "C" __global__ void __launch_bounds__(128, 1) _mhc_fn_normw_merge_fwd__kernel(const float* __restrict__ fn, const float* __restrict__ normw, float* __restrict__ out_fn) {
  float2 __1;
    float2 v_ = *(float2*)(fn + (((((int)blockIdx.x) * 28672) + (((int)blockIdx.y) * 256)) + (((int)threadIdx.x) * 2)));
    float2 v__1 = *(float2*)(normw + ((((int)blockIdx.y) * 256) + (((int)threadIdx.x) * 2)));
    *(float2*)(&(__1.x)) = tl::mul2(*(float2*)(&(v_.x)), *(float2*)(&(v__1.x)));
  *(float2*)(out_fn + (((((int)blockIdx.x) * 28672) + (((int)blockIdx.y) * 256)) + (((int)threadIdx.x) * 2))) = __1;
}

