// TileKernels CUDA dump (generated by scripts/dump_cuda_sources.py)
// Source Python: tile_kernels/mhc/post_kernel.py
// JIT factory: _mhc_post_fwd
// prim_func: _mhc_post_fwd_kernel
// Compile args: {"args": [4, 7168], "kwargs": {}}
// Public API: tile_kernels.modeling.mhc.ops.post.mhc_post
#include <tl_templates/cuda/gemm.h>
#include <tl_templates/cuda/copy.h>
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#include <tl_templates/cuda/debug.h>
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void _mhc_post_fwd_kernel_kernel(const float* a, const bfloat16_t* b, const float* c, const bfloat16_t* d, bfloat16_t* x, int num_tokens);
extern "C" __global__ void __launch_bounds__(128, 1) _mhc_post_fwd_kernel_kernel(const float* a, const bfloat16_t* b, const float* c, const bfloat16_t* d, bfloat16_t* x, int num_tokens) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  float a_local[16];
  float c_local[4];
  float b_local[32];
  float d_local[8];
  float x_local[32];
  #pragma unroll
  for (int i = 0; i < 4; ++i) {
    *(float4*)(a_local + (i * 4)) = *(float4*)(a + ((((int64_t)((int)blockIdx.x)) * (int64_t)16) + (((int64_t)i) * (int64_t)4)));
  }
  *(float4*)(c_local + 0) = *(float4*)(c + (((int64_t)((int)blockIdx.x)) * (int64_t)4));
  cudaGridDependencySynchronize();
  #pragma unroll
  for (int i_1 = 0; i_1 < 4; ++i_1) {
    tl::cp_async_gs<16>((&(((bfloat16_t*)buf_dyn_shmem)[((i_1 * 1024) + (((int)threadIdx.x) * 8))])), (&(b[(((((int64_t)((int)blockIdx.x)) * (int64_t)28672) + (((int64_t)i_1) * (int64_t)7168)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8))])));
  }
  tl::cp_async_commit();
  tl::cp_async_gs<16>((&(((bfloat16_t*)buf_dyn_shmem)[((((int)threadIdx.x) * 8) + 8192)])), (&(d[((((int64_t)((int)blockIdx.x)) * (int64_t)7168) + (((int64_t)((int)threadIdx.x)) * (int64_t)8))])));
  tl::cp_async_commit();
  #pragma unroll
  for (int i_2 = 0; i_2 < 4; ++i_2) {
    tl::cp_async_gs<16>((&(((bfloat16_t*)buf_dyn_shmem)[(((i_2 * 1024) + (((int)threadIdx.x) * 8)) + 4096)])), (&(b[((((((int64_t)((int)blockIdx.x)) * (int64_t)28672) + (((int64_t)i_2) * (int64_t)7168)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8)) + (int64_t)1024)])));
  }
  tl::cp_async_commit();
  tl::cp_async_gs<16>((&(((bfloat16_t*)buf_dyn_shmem)[((((int)threadIdx.x) * 8) + 9216)])), (&(d[(((((int64_t)((int)blockIdx.x)) * (int64_t)7168) + (((int64_t)((int)threadIdx.x)) * (int64_t)8)) + (int64_t)1024)])));
  tl::cp_async_commit();
  for (int i0_h = 0; i0_h < 5; ++i0_h) {
    tl::cp_async_wait<1>();
    __syncthreads();
    #pragma unroll
    for (int i_3 = 0; i_3 < 32; ++i_3) {
      b_local[i_3] = ((float)((bfloat16_t*)buf_dyn_shmem)[((((i0_h & 1) * 4096) + (i_3 * 128)) + ((int)threadIdx.x))]);
    }
    __syncthreads();
    #pragma unroll
    for (int i_4 = 0; i_4 < 4; ++i_4) {
      tl::cp_async_gs<16>((&(((bfloat16_t*)buf_dyn_shmem)[((((i0_h & 1) * 4096) + (i_4 * 1024)) + (((int)threadIdx.x) * 8))])), (&(b[(((((((int64_t)((int)blockIdx.x)) * (int64_t)28672) + (((int64_t)i_4) * (int64_t)7168)) + (((int64_t)i0_h) * (int64_t)1024)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8)) + (int64_t)2048)])));
    }
    tl::cp_async_commit();
    tl::cp_async_wait<1>();
    __syncthreads();
    #pragma unroll
    for (int i_5 = 0; i_5 < 8; ++i_5) {
      d_local[i_5] = ((float)((bfloat16_t*)buf_dyn_shmem)[(((((i0_h & 1) * 1024) + (i_5 * 128)) + ((int)threadIdx.x)) + 8192)]);
    }
    __syncthreads();
    tl::cp_async_gs<16>((&(((bfloat16_t*)buf_dyn_shmem)[((((i0_h & 1) * 1024) + (((int)threadIdx.x) * 8)) + 8192)])), (&(d[((((((int64_t)((int)blockIdx.x)) * (int64_t)7168) + (((int64_t)i0_h) * (int64_t)1024)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8)) + (int64_t)2048)])));
    tl::cp_async_commit();
    #pragma unroll
    for (int i_6 = 0; i_6 < 32; ++i_6) {
      x_local[i_6] = (c_local[(i_6 >> 3)] * d_local[(i_6 & 7)]);
      for (int i_mhci = 0; i_mhci < 4; ++i_mhci) {
        x_local[i_6] = (x_local[i_6] + (a_local[((i_mhci * 4) + (i_6 >> 3))] * b_local[((i_mhci * 8) + (i_6 & 7))]));
      }
    }
    __syncthreads();
    #pragma unroll
    for (int i_7 = 0; i_7 < 32; ++i_7) {
      ((bfloat16_t*)buf_dyn_shmem)[(((i_7 * 128) + ((int)threadIdx.x)) + 10240)] = ((bfloat16_t)x_local[i_7]);
    }
    __syncthreads();
    #pragma unroll
    for (int i_8 = 0; i_8 < 4; ++i_8) {
      *(uint4*)(x + ((((((int64_t)((int)blockIdx.x)) * (int64_t)28672) + (((int64_t)i_8) * (int64_t)7168)) + (((int64_t)i0_h) * (int64_t)1024)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8))) = *(uint4*)(((bfloat16_t*)buf_dyn_shmem) + (((i_8 * 1024) + (((int)threadIdx.x) * 8)) + 10240));
    }
  }
  tl::cp_async_wait<1>();
  __syncthreads();
  #pragma unroll
  for (int i_9 = 0; i_9 < 32; ++i_9) {
    b_local[i_9] = ((float)((bfloat16_t*)buf_dyn_shmem)[(((i_9 * 128) + ((int)threadIdx.x)) + 4096)]);
  }
  #pragma unroll
  for (int i_10 = 0; i_10 < 8; ++i_10) {
    d_local[i_10] = ((float)((bfloat16_t*)buf_dyn_shmem)[(((i_10 * 128) + ((int)threadIdx.x)) + 9216)]);
  }
  #pragma unroll
  for (int i_11 = 0; i_11 < 32; ++i_11) {
    x_local[i_11] = (c_local[(i_11 >> 3)] * d_local[(i_11 & 7)]);
    for (int i_mhci_1 = 0; i_mhci_1 < 4; ++i_mhci_1) {
      x_local[i_11] = (x_local[i_11] + (a_local[((i_mhci_1 * 4) + (i_11 >> 3))] * b_local[((i_mhci_1 * 8) + (i_11 & 7))]));
    }
  }
  #pragma unroll
  for (int i_12 = 0; i_12 < 32; ++i_12) {
    ((bfloat16_t*)buf_dyn_shmem)[(((i_12 * 128) + ((int)threadIdx.x)) + 10240)] = ((bfloat16_t)x_local[i_12]);
  }
  __syncthreads();
  #pragma unroll
  for (int i_13 = 0; i_13 < 4; ++i_13) {
    *(uint4*)(x + ((((((int64_t)((int)blockIdx.x)) * (int64_t)28672) + (((int64_t)i_13) * (int64_t)7168)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8)) + (int64_t)5120)) = *(uint4*)(((bfloat16_t*)buf_dyn_shmem) + (((i_13 * 1024) + (((int)threadIdx.x) * 8)) + 10240));
  }
  tl::cp_async_wait<0>();
  __syncthreads();
  #pragma unroll
  for (int i_14 = 0; i_14 < 32; ++i_14) {
    b_local[i_14] = ((float)((bfloat16_t*)buf_dyn_shmem)[((i_14 * 128) + ((int)threadIdx.x))]);
  }
  #pragma unroll
  for (int i_15 = 0; i_15 < 8; ++i_15) {
    d_local[i_15] = ((float)((bfloat16_t*)buf_dyn_shmem)[(((i_15 * 128) + ((int)threadIdx.x)) + 8192)]);
  }
  #pragma unroll
  for (int i_16 = 0; i_16 < 32; ++i_16) {
    x_local[i_16] = (c_local[(i_16 >> 3)] * d_local[(i_16 & 7)]);
    for (int i_mhci_2 = 0; i_mhci_2 < 4; ++i_mhci_2) {
      x_local[i_16] = (x_local[i_16] + (a_local[((i_mhci_2 * 4) + (i_16 >> 3))] * b_local[((i_mhci_2 * 8) + (i_16 & 7))]));
    }
  }
  #pragma unroll
  for (int i_17 = 0; i_17 < 32; ++i_17) {
    ((bfloat16_t*)buf_dyn_shmem)[(((i_17 * 128) + ((int)threadIdx.x)) + 10240)] = ((bfloat16_t)x_local[i_17]);
  }
  __syncthreads();
  #pragma unroll
  for (int i_18 = 0; i_18 < 4; ++i_18) {
    *(uint4*)(x + ((((((int64_t)((int)blockIdx.x)) * (int64_t)28672) + (((int64_t)i_18) * (int64_t)7168)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8)) + (int64_t)6144)) = *(uint4*)(((bfloat16_t*)buf_dyn_shmem) + (((i_18 * 1024) + (((int)threadIdx.x) * 8)) + 10240));
  }
}

