// TileKernels CUDA dump (generated by scripts/dump_cuda_sources.py)
// Source Python: tile_kernels/mhc/post_kernel.py
// JIT factory: _mhc_post_bwd
// prim_func: _mhc_post_bwd_kernel
// Compile args: {"args": [4, 7168], "kwargs": {}}
// Public API: tile_kernels.modeling.mhc.ops.post.mhc_post
#include <tl_templates/cuda/gemm.h>
#include <tl_templates/cuda/copy.h>
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#include <tl_templates/cuda/debug.h>
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void _mhc_post_bwd_kernel_kernel(const float* __restrict__ a, const bfloat16_t* __restrict__ b, const float* __restrict__ c, const bfloat16_t* __restrict__ d, float* __restrict__ da, bfloat16_t* __restrict__ db, float* __restrict__ dc, bfloat16_t* __restrict__ dd, const bfloat16_t* __restrict__ dx, int num_tokens);
extern "C" __global__ void __launch_bounds__(128, 1) _mhc_post_bwd_kernel_kernel(const float* __restrict__ a, const bfloat16_t* __restrict__ b, const float* __restrict__ c, const bfloat16_t* __restrict__ d, float* __restrict__ da, bfloat16_t* __restrict__ db, float* __restrict__ dc, bfloat16_t* __restrict__ dd, const bfloat16_t* __restrict__ dx, int num_tokens) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  float a_local[16];
  float c_local[4];
  float da_reducer[16];
  float dc_reducer[4];
  float dx_local[8];
  float b_local[8];
  float d_local[2];
  float db_local[8];
  float dd_local[2];
  #pragma unroll
  for (int i = 0; i < 4; ++i) {
    *(float4*)(a_local + (i * 4)) = *(float4*)(a + ((((int64_t)((int)blockIdx.x)) * (int64_t)16) + (((int64_t)i) * (int64_t)4)));
  }
  *(float4*)(c_local + 0) = *(float4*)(c + (((int64_t)((int)blockIdx.x)) * (int64_t)4));
  #pragma unroll
  for (int i_1 = 0; i_1 < 4; ++i_1) {
    float broadcast_var = 0x0p+0f/*0.000000e+00*/;
    *(float4*)(da_reducer + (i_1 * 4)) = make_float4(broadcast_var, broadcast_var, broadcast_var, broadcast_var);
  }
  float broadcast_var_1 = 0x0p+0f/*0.000000e+00*/;
  *(float4*)(dc_reducer + 0) = make_float4(broadcast_var_1, broadcast_var_1, broadcast_var_1, broadcast_var_1);
  tl::cp_async_gs<16>((&(((bfloat16_t*)buf_dyn_shmem)[(((int)threadIdx.x) * 8)])), (&(dx[(((((int64_t)((int)blockIdx.x)) * (int64_t)28672) + ((((int64_t)((int)threadIdx.x)) >> (int64_t)5) * (int64_t)7168)) + ((((int64_t)((int)threadIdx.x)) & (int64_t)31) * (int64_t)8))])));
  tl::cp_async_commit();
  tl::cp_async_gs<16>((&(((bfloat16_t*)buf_dyn_shmem)[((((int)threadIdx.x) * 8) + 3072)])), (&(b[(((((int64_t)((int)blockIdx.x)) * (int64_t)28672) + ((((int64_t)((int)threadIdx.x)) >> (int64_t)5) * (int64_t)7168)) + ((((int64_t)((int)threadIdx.x)) & (int64_t)31) * (int64_t)8))])));
  tl::cp_async_commit();
  tl::cp_async_gs<4>((&(((bfloat16_t*)buf_dyn_shmem)[((((int)threadIdx.x) * 2) + 6144)])), (&(d[((((int64_t)((int)blockIdx.x)) * (int64_t)7168) + (((int64_t)((int)threadIdx.x)) * (int64_t)2))])));
  tl::cp_async_commit();
  tl::cp_async_gs<16>((&(((bfloat16_t*)buf_dyn_shmem)[((((int)threadIdx.x) * 8) + 1024)])), (&(dx[((((((int64_t)((int)blockIdx.x)) * (int64_t)28672) + ((((int64_t)((int)threadIdx.x)) >> (int64_t)5) * (int64_t)7168)) + ((((int64_t)((int)threadIdx.x)) & (int64_t)31) * (int64_t)8)) + (int64_t)256)])));
  tl::cp_async_commit();
  tl::cp_async_gs<16>((&(((bfloat16_t*)buf_dyn_shmem)[((((int)threadIdx.x) * 8) + 4096)])), (&(b[((((((int64_t)((int)blockIdx.x)) * (int64_t)28672) + ((((int64_t)((int)threadIdx.x)) >> (int64_t)5) * (int64_t)7168)) + ((((int64_t)((int)threadIdx.x)) & (int64_t)31) * (int64_t)8)) + (int64_t)256)])));
  tl::cp_async_commit();
  tl::cp_async_gs<4>((&(((bfloat16_t*)buf_dyn_shmem)[((((int)threadIdx.x) * 2) + 6400)])), (&(d[(((((int64_t)((int)blockIdx.x)) * (int64_t)7168) + (((int64_t)((int)threadIdx.x)) * (int64_t)2)) + (int64_t)256)])));
  tl::cp_async_commit();
  tl::cp_async_gs<16>((&(((bfloat16_t*)buf_dyn_shmem)[((((int)threadIdx.x) * 8) + 2048)])), (&(dx[((((((int64_t)((int)blockIdx.x)) * (int64_t)28672) + ((((int64_t)((int)threadIdx.x)) >> (int64_t)5) * (int64_t)7168)) + ((((int64_t)((int)threadIdx.x)) & (int64_t)31) * (int64_t)8)) + (int64_t)512)])));
  tl::cp_async_commit();
  tl::cp_async_gs<16>((&(((bfloat16_t*)buf_dyn_shmem)[((((int)threadIdx.x) * 8) + 5120)])), (&(b[((((((int64_t)((int)blockIdx.x)) * (int64_t)28672) + ((((int64_t)((int)threadIdx.x)) >> (int64_t)5) * (int64_t)7168)) + ((((int64_t)((int)threadIdx.x)) & (int64_t)31) * (int64_t)8)) + (int64_t)512)])));
  tl::cp_async_commit();
  tl::cp_async_gs<4>((&(((bfloat16_t*)buf_dyn_shmem)[((((int)threadIdx.x) * 2) + 6656)])), (&(d[(((((int64_t)((int)blockIdx.x)) * (int64_t)7168) + (((int64_t)((int)threadIdx.x)) * (int64_t)2)) + (int64_t)512)])));
  tl::cp_async_commit();
  for (int i0_h = 0; i0_h < 25; ++i0_h) {
    tl::cp_async_wait<2>();
    __syncthreads();
    #pragma unroll
    for (int i_2 = 0; i_2 < 8; ++i_2) {
      dx_local[i_2] = ((float)((bfloat16_t*)buf_dyn_shmem)[((((i0_h % 3) * 1024) + (i_2 * 128)) + ((int)threadIdx.x))]);
    }
    __syncthreads();
    tl::cp_async_gs<16>((&(((bfloat16_t*)buf_dyn_shmem)[(((i0_h % 3) * 1024) + (((int)threadIdx.x) * 8))])), (&(dx[(((((((int64_t)((int)blockIdx.x)) * (int64_t)28672) + ((((int64_t)((int)threadIdx.x)) >> (int64_t)5) * (int64_t)7168)) + (((int64_t)i0_h) * (int64_t)256)) + ((((int64_t)((int)threadIdx.x)) & (int64_t)31) * (int64_t)8)) + (int64_t)768)])));
    tl::cp_async_commit();
    tl::cp_async_wait<2>();
    __syncthreads();
    #pragma unroll
    for (int i_3 = 0; i_3 < 8; ++i_3) {
      b_local[i_3] = ((float)((bfloat16_t*)buf_dyn_shmem)[(((((i0_h % 3) * 1024) + (i_3 * 128)) + ((int)threadIdx.x)) + 3072)]);
    }
    __syncthreads();
    tl::cp_async_gs<16>((&(((bfloat16_t*)buf_dyn_shmem)[((((i0_h % 3) * 1024) + (((int)threadIdx.x) * 8)) + 3072)])), (&(b[(((((((int64_t)((int)blockIdx.x)) * (int64_t)28672) + ((((int64_t)((int)threadIdx.x)) >> (int64_t)5) * (int64_t)7168)) + (((int64_t)i0_h) * (int64_t)256)) + ((((int64_t)((int)threadIdx.x)) & (int64_t)31) * (int64_t)8)) + (int64_t)768)])));
    tl::cp_async_commit();
    tl::cp_async_wait<2>();
    __syncthreads();
    #pragma unroll
    for (int i_4 = 0; i_4 < 2; ++i_4) {
      d_local[i_4] = ((float)((bfloat16_t*)buf_dyn_shmem)[(((((i0_h % 3) * 256) + (i_4 * 128)) + ((int)threadIdx.x)) + 6144)]);
    }
    __syncthreads();
    tl::cp_async_gs<4>((&(((bfloat16_t*)buf_dyn_shmem)[((((i0_h % 3) * 256) + (((int)threadIdx.x) * 2)) + 6144)])), (&(d[((((((int64_t)((int)blockIdx.x)) * (int64_t)7168) + (((int64_t)i0_h) * (int64_t)256)) + (((int64_t)((int)threadIdx.x)) * (int64_t)2)) + (int64_t)768)])));
    tl::cp_async_commit();
    #pragma unroll
    for (int i_5 = 0; i_5 < 2; ++i_5) {
      float broadcast_var_2 = 0x0p+0f/*0.000000e+00*/;
      *(float4*)(db_local + (i_5 * 4)) = make_float4(broadcast_var_2, broadcast_var_2, broadcast_var_2, broadcast_var_2);
    }
    for (int i_mhci = 0; i_mhci < 4; ++i_mhci) {
      for (int i_mhco = 0; i_mhco < 4; ++i_mhco) {
        #pragma unroll
        for (int i_6 = 0; i_6 < 2; ++i_6) {
          db_local[((i_mhci * 2) + i_6)] = (db_local[((i_mhci * 2) + i_6)] + (a_local[((i_mhci * 4) + i_mhco)] * dx_local[((i_mhco * 2) + i_6)]));
          da_reducer[((i_mhci * 4) + i_mhco)] = (da_reducer[((i_mhci * 4) + i_mhco)] + (b_local[((i_mhci * 2) + i_6)] * dx_local[((i_mhco * 2) + i_6)]));
        }
      }
    }
    float broadcast_var_3 = 0x0p+0f/*0.000000e+00*/;
    *(float2*)(dd_local + 0) = make_float2(broadcast_var_3, broadcast_var_3);
    for (int i_mhc = 0; i_mhc < 4; ++i_mhc) {
      #pragma unroll
      for (int i_7 = 0; i_7 < 2; ++i_7) {
        dc_reducer[i_mhc] = (dc_reducer[i_mhc] + (d_local[i_7] * dx_local[((i_mhc * 2) + i_7)]));
        dd_local[i_7] = (dd_local[i_7] + (c_local[i_mhc] * dx_local[((i_mhc * 2) + i_7)]));
      }
    }
    __syncthreads();
    #pragma unroll
    for (int i_8 = 0; i_8 < 8; ++i_8) {
      ((bfloat16_t*)buf_dyn_shmem)[(((i_8 * 128) + ((int)threadIdx.x)) + 6912)] = ((bfloat16_t)db_local[i_8]);
    }
    #pragma unroll
    for (int i_9 = 0; i_9 < 2; ++i_9) {
      ((bfloat16_t*)buf_dyn_shmem)[(((i_9 * 128) + ((int)threadIdx.x)) + 7936)] = ((bfloat16_t)dd_local[i_9]);
    }
    __syncthreads();
    *(uint4*)(db + ((((((int64_t)((int)blockIdx.x)) * (int64_t)28672) + ((((int64_t)((int)threadIdx.x)) >> (int64_t)5) * (int64_t)7168)) + (((int64_t)i0_h) * (int64_t)256)) + ((((int64_t)((int)threadIdx.x)) & (int64_t)31) * (int64_t)8))) = *(uint4*)(((bfloat16_t*)buf_dyn_shmem) + ((((int)threadIdx.x) * 8) + 6912));
    *(uint1*)(dd + (((((int64_t)((int)blockIdx.x)) * (int64_t)7168) + (((int64_t)i0_h) * (int64_t)256)) + (((int64_t)((int)threadIdx.x)) * (int64_t)2))) = *(uint1*)(((bfloat16_t*)buf_dyn_shmem) + ((((int)threadIdx.x) * 2) + 7936));
  }
  tl::cp_async_wait<2>();
  __syncthreads();
  #pragma unroll
  for (int i_10 = 0; i_10 < 8; ++i_10) {
    dx_local[i_10] = ((float)((bfloat16_t*)buf_dyn_shmem)[(((i_10 * 128) + ((int)threadIdx.x)) + 1024)]);
  }
  #pragma unroll
  for (int i_11 = 0; i_11 < 8; ++i_11) {
    b_local[i_11] = ((float)((bfloat16_t*)buf_dyn_shmem)[(((i_11 * 128) + ((int)threadIdx.x)) + 4096)]);
  }
  #pragma unroll
  for (int i_12 = 0; i_12 < 2; ++i_12) {
    d_local[i_12] = ((float)((bfloat16_t*)buf_dyn_shmem)[(((i_12 * 128) + ((int)threadIdx.x)) + 6400)]);
  }
  #pragma unroll
  for (int i_13 = 0; i_13 < 2; ++i_13) {
    float broadcast_var_4 = 0x0p+0f/*0.000000e+00*/;
    *(float4*)(db_local + (i_13 * 4)) = make_float4(broadcast_var_4, broadcast_var_4, broadcast_var_4, broadcast_var_4);
  }
  for (int i_mhci_1 = 0; i_mhci_1 < 4; ++i_mhci_1) {
    for (int i_mhco_1 = 0; i_mhco_1 < 4; ++i_mhco_1) {
      #pragma unroll
      for (int i_14 = 0; i_14 < 2; ++i_14) {
        db_local[((i_mhci_1 * 2) + i_14)] = (db_local[((i_mhci_1 * 2) + i_14)] + (a_local[((i_mhci_1 * 4) + i_mhco_1)] * dx_local[((i_mhco_1 * 2) + i_14)]));
        da_reducer[((i_mhci_1 * 4) + i_mhco_1)] = (da_reducer[((i_mhci_1 * 4) + i_mhco_1)] + (b_local[((i_mhci_1 * 2) + i_14)] * dx_local[((i_mhco_1 * 2) + i_14)]));
      }
    }
  }
  float broadcast_var_5 = 0x0p+0f/*0.000000e+00*/;
  *(float2*)(dd_local + 0) = make_float2(broadcast_var_5, broadcast_var_5);
  for (int i_mhc_1 = 0; i_mhc_1 < 4; ++i_mhc_1) {
    #pragma unroll
    for (int i_15 = 0; i_15 < 2; ++i_15) {
      dc_reducer[i_mhc_1] = (dc_reducer[i_mhc_1] + (d_local[i_15] * dx_local[((i_mhc_1 * 2) + i_15)]));
      dd_local[i_15] = (dd_local[i_15] + (c_local[i_mhc_1] * dx_local[((i_mhc_1 * 2) + i_15)]));
    }
  }
  #pragma unroll
  for (int i_16 = 0; i_16 < 8; ++i_16) {
    ((bfloat16_t*)buf_dyn_shmem)[(((i_16 * 128) + ((int)threadIdx.x)) + 6912)] = ((bfloat16_t)db_local[i_16]);
  }
  #pragma unroll
  for (int i_17 = 0; i_17 < 2; ++i_17) {
    ((bfloat16_t*)buf_dyn_shmem)[(((i_17 * 128) + ((int)threadIdx.x)) + 7936)] = ((bfloat16_t)dd_local[i_17]);
  }
  __syncthreads();
  *(uint4*)(db + ((((((int64_t)((int)blockIdx.x)) * (int64_t)28672) + ((((int64_t)((int)threadIdx.x)) >> (int64_t)5) * (int64_t)7168)) + ((((int64_t)((int)threadIdx.x)) & (int64_t)31) * (int64_t)8)) + (int64_t)6400)) = *(uint4*)(((bfloat16_t*)buf_dyn_shmem) + ((((int)threadIdx.x) * 8) + 6912));
  *(uint1*)(dd + (((((int64_t)((int)blockIdx.x)) * (int64_t)7168) + (((int64_t)((int)threadIdx.x)) * (int64_t)2)) + (int64_t)6400)) = *(uint1*)(((bfloat16_t*)buf_dyn_shmem) + ((((int)threadIdx.x) * 2) + 7936));
  tl::cp_async_wait<2>();
  __syncthreads();
  #pragma unroll
  for (int i_18 = 0; i_18 < 8; ++i_18) {
    dx_local[i_18] = ((float)((bfloat16_t*)buf_dyn_shmem)[(((i_18 * 128) + ((int)threadIdx.x)) + 2048)]);
  }
  #pragma unroll
  for (int i_19 = 0; i_19 < 8; ++i_19) {
    b_local[i_19] = ((float)((bfloat16_t*)buf_dyn_shmem)[(((i_19 * 128) + ((int)threadIdx.x)) + 5120)]);
  }
  #pragma unroll
  for (int i_20 = 0; i_20 < 2; ++i_20) {
    d_local[i_20] = ((float)((bfloat16_t*)buf_dyn_shmem)[(((i_20 * 128) + ((int)threadIdx.x)) + 6656)]);
  }
  #pragma unroll
  for (int i_21 = 0; i_21 < 2; ++i_21) {
    float broadcast_var_6 = 0x0p+0f/*0.000000e+00*/;
    *(float4*)(db_local + (i_21 * 4)) = make_float4(broadcast_var_6, broadcast_var_6, broadcast_var_6, broadcast_var_6);
  }
  for (int i_mhci_2 = 0; i_mhci_2 < 4; ++i_mhci_2) {
    for (int i_mhco_2 = 0; i_mhco_2 < 4; ++i_mhco_2) {
      #pragma unroll
      for (int i_22 = 0; i_22 < 2; ++i_22) {
        db_local[((i_mhci_2 * 2) + i_22)] = (db_local[((i_mhci_2 * 2) + i_22)] + (a_local[((i_mhci_2 * 4) + i_mhco_2)] * dx_local[((i_mhco_2 * 2) + i_22)]));
        da_reducer[((i_mhci_2 * 4) + i_mhco_2)] = (da_reducer[((i_mhci_2 * 4) + i_mhco_2)] + (b_local[((i_mhci_2 * 2) + i_22)] * dx_local[((i_mhco_2 * 2) + i_22)]));
      }
    }
  }
  float broadcast_var_7 = 0x0p+0f/*0.000000e+00*/;
  *(float2*)(dd_local + 0) = make_float2(broadcast_var_7, broadcast_var_7);
  for (int i_mhc_2 = 0; i_mhc_2 < 4; ++i_mhc_2) {
    #pragma unroll
    for (int i_23 = 0; i_23 < 2; ++i_23) {
      dc_reducer[i_mhc_2] = (dc_reducer[i_mhc_2] + (d_local[i_23] * dx_local[((i_mhc_2 * 2) + i_23)]));
      dd_local[i_23] = (dd_local[i_23] + (c_local[i_mhc_2] * dx_local[((i_mhc_2 * 2) + i_23)]));
    }
  }
  #pragma unroll
  for (int i_24 = 0; i_24 < 8; ++i_24) {
    ((bfloat16_t*)buf_dyn_shmem)[(((i_24 * 128) + ((int)threadIdx.x)) + 6912)] = ((bfloat16_t)db_local[i_24]);
  }
  #pragma unroll
  for (int i_25 = 0; i_25 < 2; ++i_25) {
    ((bfloat16_t*)buf_dyn_shmem)[(((i_25 * 128) + ((int)threadIdx.x)) + 7936)] = ((bfloat16_t)dd_local[i_25]);
  }
  __syncthreads();
  *(uint4*)(db + ((((((int64_t)((int)blockIdx.x)) * (int64_t)28672) + ((((int64_t)((int)threadIdx.x)) >> (int64_t)5) * (int64_t)7168)) + ((((int64_t)((int)threadIdx.x)) & (int64_t)31) * (int64_t)8)) + (int64_t)6656)) = *(uint4*)(((bfloat16_t*)buf_dyn_shmem) + ((((int)threadIdx.x) * 8) + 6912));
  *(uint1*)(dd + (((((int64_t)((int)blockIdx.x)) * (int64_t)7168) + (((int64_t)((int)threadIdx.x)) * (int64_t)2)) + (int64_t)6656)) = *(uint1*)(((bfloat16_t*)buf_dyn_shmem) + ((((int)threadIdx.x) * 2) + 7936));
  tl::cp_async_wait<0>();
  __syncthreads();
  #pragma unroll
  for (int i_26 = 0; i_26 < 8; ++i_26) {
    dx_local[i_26] = ((float)((bfloat16_t*)buf_dyn_shmem)[((i_26 * 128) + ((int)threadIdx.x))]);
  }
  #pragma unroll
  for (int i_27 = 0; i_27 < 8; ++i_27) {
    b_local[i_27] = ((float)((bfloat16_t*)buf_dyn_shmem)[(((i_27 * 128) + ((int)threadIdx.x)) + 3072)]);
  }
  #pragma unroll
  for (int i_28 = 0; i_28 < 2; ++i_28) {
    d_local[i_28] = ((float)((bfloat16_t*)buf_dyn_shmem)[(((i_28 * 128) + ((int)threadIdx.x)) + 6144)]);
  }
  #pragma unroll
  for (int i_29 = 0; i_29 < 2; ++i_29) {
    float broadcast_var_8 = 0x0p+0f/*0.000000e+00*/;
    *(float4*)(db_local + (i_29 * 4)) = make_float4(broadcast_var_8, broadcast_var_8, broadcast_var_8, broadcast_var_8);
  }
  for (int i_mhci_3 = 0; i_mhci_3 < 4; ++i_mhci_3) {
    for (int i_mhco_3 = 0; i_mhco_3 < 4; ++i_mhco_3) {
      #pragma unroll
      for (int i_30 = 0; i_30 < 2; ++i_30) {
        db_local[((i_mhci_3 * 2) + i_30)] = (db_local[((i_mhci_3 * 2) + i_30)] + (a_local[((i_mhci_3 * 4) + i_mhco_3)] * dx_local[((i_mhco_3 * 2) + i_30)]));
        da_reducer[((i_mhci_3 * 4) + i_mhco_3)] = (da_reducer[((i_mhci_3 * 4) + i_mhco_3)] + (b_local[((i_mhci_3 * 2) + i_30)] * dx_local[((i_mhco_3 * 2) + i_30)]));
      }
    }
  }
  float broadcast_var_9 = 0x0p+0f/*0.000000e+00*/;
  *(float2*)(dd_local + 0) = make_float2(broadcast_var_9, broadcast_var_9);
  for (int i_mhc_3 = 0; i_mhc_3 < 4; ++i_mhc_3) {
    #pragma unroll
    for (int i_31 = 0; i_31 < 2; ++i_31) {
      dc_reducer[i_mhc_3] = (dc_reducer[i_mhc_3] + (d_local[i_31] * dx_local[((i_mhc_3 * 2) + i_31)]));
      dd_local[i_31] = (dd_local[i_31] + (c_local[i_mhc_3] * dx_local[((i_mhc_3 * 2) + i_31)]));
    }
  }
  #pragma unroll
  for (int i_32 = 0; i_32 < 8; ++i_32) {
    ((bfloat16_t*)buf_dyn_shmem)[(((i_32 * 128) + ((int)threadIdx.x)) + 6912)] = ((bfloat16_t)db_local[i_32]);
  }
  #pragma unroll
  for (int i_33 = 0; i_33 < 2; ++i_33) {
    ((bfloat16_t*)buf_dyn_shmem)[(((i_33 * 128) + ((int)threadIdx.x)) + 7936)] = ((bfloat16_t)dd_local[i_33]);
  }
  __syncthreads();
  *(uint4*)(db + ((((((int64_t)((int)blockIdx.x)) * (int64_t)28672) + ((((int64_t)((int)threadIdx.x)) >> (int64_t)5) * (int64_t)7168)) + ((((int64_t)((int)threadIdx.x)) & (int64_t)31) * (int64_t)8)) + (int64_t)6912)) = *(uint4*)(((bfloat16_t*)buf_dyn_shmem) + ((((int)threadIdx.x) * 8) + 6912));
  *(uint1*)(dd + (((((int64_t)((int)blockIdx.x)) * (int64_t)7168) + (((int64_t)((int)threadIdx.x)) * (int64_t)2)) + (int64_t)6912)) = *(uint1*)(((bfloat16_t*)buf_dyn_shmem) + ((((int)threadIdx.x) * 2) + 7936));
  __syncthreads();
  for (int __finred_0 = 0; __finred_0 < 16; ++__finred_0) {
    da_reducer[__finred_0] = tl::AllReduce<tl::SumOp, 128, 1, 0, tl::NamedBarrier<128>>::run(da_reducer[__finred_0], (&(((float*)buf_dyn_shmem)[0])));
  }
  __syncthreads();
  for (int __finred_0_1 = 0; __finred_0_1 < 4; ++__finred_0_1) {
    dc_reducer[__finred_0_1] = tl::AllReduce<tl::SumOp, 128, 1, 0, tl::NamedBarrier<128>>::run(dc_reducer[__finred_0_1], (&(((float*)buf_dyn_shmem)[0])));
  }
  if ((((int)threadIdx.x) >> 4) == 0) {
    da[((((int64_t)((int)blockIdx.x)) * (int64_t)16) + (((int64_t)((int)threadIdx.x)) & (int64_t)15))] = da_reducer[(((int)threadIdx.x) & 15)];
  }
  if ((((int)threadIdx.x) >> 2) == 0) {
    dc[((((int64_t)((int)blockIdx.x)) * (int64_t)4) + (((int64_t)((int)threadIdx.x)) & (int64_t)3))] = dc_reducer[(((int)threadIdx.x) & 3)];
  }
}

