// TileKernels CUDA dump (generated by scripts/dump_cuda_sources.py)
// Source Python: tile_kernels/mhc/pre_split_mixes_kernel.py
// JIT factory: _mhc_pre_split_mixes_fwd
// prim_func: mhc_pre_split_mixes_fwd_kernel
// Compile args: {"args": [4, 1.0, 1e-06, 32], "kwargs": {}}
// Public API: tile_kernels.modeling.mhc.ops.pre_split_mixes.mhc_pre_split_mixes
#include <tl_templates/cuda/gemm.h>
#include <tl_templates/cuda/copy.h>
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#include <tl_templates/cuda/debug.h>
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void mhc_pre_split_mixes_fwd_kernel_kernel(float* __restrict__ comb_res_mix, const float* __restrict__ input_mixes, const float* __restrict__ mhc_base, const float* __restrict__ mhc_scale, float* __restrict__ post_layer_mix, float* __restrict__ pre_layer_mix, int num_tokens);
extern "C" __global__ void __launch_bounds__(128, 1) mhc_pre_split_mixes_fwd_kernel_kernel(float* __restrict__ comb_res_mix, const float* __restrict__ input_mixes, const float* __restrict__ mhc_base, const float* __restrict__ mhc_scale, float* __restrict__ post_layer_mix, float* __restrict__ pre_layer_mix, int num_tokens) {
  float input_mixes_frag[24];
  float pre_layer_mix_frag[24];
  float post_layer_mix_frag[4];
  float comb_res_mix_frag[16];
  if (((int)threadIdx.x) < 32) {
    #pragma unroll
    for (int i = 0; i < 3; ++i) {
      float broadcast_var = 0x0p+0f/*0.000000e+00*/;
      ulonglong4 condval;
      if ((((((int)blockIdx.x) * 32) + ((int)threadIdx.x)) < num_tokens)) {
        condval = tl::load_global_256(&(*(ulonglong4*)(input_mixes + (((((int64_t)((int)blockIdx.x)) * (int64_t)768) + (((int64_t)((int)threadIdx.x)) * (int64_t)24)) + (((int64_t)i) * (int64_t)8)))));
      } else {
        condval = make_ulonglong4(*(unsigned long long*)&make_float2(broadcast_var, broadcast_var), *(unsigned long long*)&make_float2(broadcast_var, broadcast_var), *(unsigned long long*)&make_float2(broadcast_var, broadcast_var), *(unsigned long long*)&make_float2(broadcast_var, broadcast_var));
      }
      *(ulonglong4*)(input_mixes_frag + (i * 8)) = condval;
    }
    #pragma unroll
    for (int i_1 = 0; i_1 < 3; ++i_1) {
      for (int vec_s = 0; vec_s < 8; ++vec_s) {
        if (((i_1 * 2) + (vec_s >> 2)) < 1) {
          pre_layer_mix_frag[((i_1 * 8) + vec_s)] = ((0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - ((input_mixes_frag[((i_1 * 8) + vec_s)] * mhc_scale[0]) + mhc_base[((i_1 * 8) + vec_s)]))))) + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/);
        }
      }
    }
    float broadcast_var_1 = 0x1p+0f/*1.000000e+00*/;
    float broadcast_var_2 = 0x1p+0f/*1.000000e+00*/;
    float broadcast_var_3 = 0x0p+0f/*0.000000e+00*/;
    float4 __1;
      float4 v_ = make_float4(broadcast_var_1, broadcast_var_1, broadcast_var_1, broadcast_var_1);
      float4 __2;
        float4 v__1 = make_float4(broadcast_var_2, broadcast_var_2, broadcast_var_2, broadcast_var_2);
        float4 __3;
        float4 __4;
          float4 v__2 = make_float4(broadcast_var_3, broadcast_var_3, broadcast_var_3, broadcast_var_3);
          float4 __5;
            float4 v__3 = *(float4*)(input_mixes_frag + 4);
            float4 v__4 = make_float4(mhc_scale[1], mhc_scale[1], mhc_scale[1], mhc_scale[1]);
            float4 v__5 = *(float4*)(mhc_base + 4);
            *(float2*)(&(__5.x)) = tl::fma2(*(float2*)(&(v__3.x)), *(float2*)(&(v__4.x)), *(float2*)(&(v__5.x)));
            *(float2*)(&(__5.z)) = tl::fma2(*(float2*)(&(v__3.z)), *(float2*)(&(v__4.z)), *(float2*)(&(v__5.z)));
          *(float2*)(&(__4.x)) = tl::sub2(*(float2*)(&(v__2.x)), *(float2*)(&(__5.x)));
          *(float2*)(&(__4.z)) = tl::sub2(*(float2*)(&(v__2.z)), *(float2*)(&(__5.z)));
        __3.x = expf(__4.x);
        __3.y = expf(__4.y);
        __3.z = expf(__4.z);
        __3.w = expf(__4.w);
        *(float2*)(&(__2.x)) = tl::add2(*(float2*)(&(v__1.x)), *(float2*)(&(__3.x)));
        *(float2*)(&(__2.z)) = tl::add2(*(float2*)(&(v__1.z)), *(float2*)(&(__3.z)));
      __1.x = (v_.x/__2.x);
      __1.y = (v_.y/__2.y);
      __1.z = (v_.z/__2.z);
      __1.w = (v_.w/__2.w);
    *(float4*)(post_layer_mix_frag + 0) = __1;
    #pragma unroll
    for (int i_2 = 0; i_2 < 2; ++i_2) {
      ulonglong4 __6;
        ulonglong4 v__6 = *(ulonglong4*)(input_mixes_frag + ((i_2 * 8) + 8));
        ulonglong4 v__7 = make_ulonglong4(*(unsigned long long*)&make_float2(mhc_scale[2], mhc_scale[2]), *(unsigned long long*)&make_float2(mhc_scale[2], mhc_scale[2]), *(unsigned long long*)&make_float2(mhc_scale[2], mhc_scale[2]), *(unsigned long long*)&make_float2(mhc_scale[2], mhc_scale[2]));
        ulonglong4 v__8 = tl::load_global_256(&(*(ulonglong4*)(mhc_base + ((i_2 * 8) + 8))));
        *(float2*)(&(__6.x)) = tl::fma2(*(float2*)(&(v__6.x)), *(float2*)(&(v__7.x)), *(float2*)(&(v__8.x)));
        *(float2*)(&(__6.y)) = tl::fma2(*(float2*)(&(v__6.y)), *(float2*)(&(v__7.y)), *(float2*)(&(v__8.y)));
        *(float2*)(&(__6.z)) = tl::fma2(*(float2*)(&(v__6.z)), *(float2*)(&(v__7.z)), *(float2*)(&(v__8.z)));
        *(float2*)(&(__6.w)) = tl::fma2(*(float2*)(&(v__6.w)), *(float2*)(&(v__7.w)), *(float2*)(&(v__8.w)));
      *(ulonglong4*)(comb_res_mix_frag + (i_2 * 8)) = __6;
    }
    if (((((int)blockIdx.x) * 32) + ((int)threadIdx.x)) < num_tokens) {
      #pragma unroll
      for (int i_3 = 0; i_3 < 6; ++i_3) {
        if (i_3 < 1) {
          *(float4*)(pre_layer_mix + (((((int64_t)((int)blockIdx.x)) * (int64_t)128) + (((int64_t)((int)threadIdx.x)) * (int64_t)4)) + (((int64_t)i_3) * (int64_t)4))) = *(float4*)(pre_layer_mix_frag + 0);
        }
      }
      *(float4*)(post_layer_mix + ((((int64_t)((int)blockIdx.x)) * (int64_t)128) + (((int64_t)((int)threadIdx.x)) * (int64_t)4))) = *(float4*)(post_layer_mix_frag + 0);
      #pragma unroll
      for (int i_4 = 0; i_4 < 2; ++i_4) {
        tl::store_global_256(&(*(ulonglong4*)(comb_res_mix + (((((int64_t)((int)blockIdx.x)) * (int64_t)512) + (((int64_t)((int)threadIdx.x)) * (int64_t)16)) + (((int64_t)i_4) * (int64_t)8)))), *(ulonglong4*)(comb_res_mix_frag + (i_4 * 8)));
      }
    }
  }
}

