// TileKernels CUDA dump (generated by scripts/dump_cuda_sources.py)
// Source Python: tile_kernels/mhc/pre_split_mixes_kernel.py
// JIT factory: _mhc_pre_split_mixes_bwd
// prim_func: mhc_pre_split_mixes_bwd_kernel
// Compile args: {"args": [4, 1.0, 32, 188], "kwargs": {}}
// Public API: tile_kernels.modeling.mhc.ops.pre_split_mixes.mhc_pre_split_mixes
#include <tl_templates/cuda/gemm.h>
#include <tl_templates/cuda/copy.h>
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#include <tl_templates/cuda/debug.h>
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void mhc_pre_split_mixes_bwd_kernel_kernel(const float* __restrict__ comb_res_mix_grad, const float* __restrict__ input_mixes, float* __restrict__ input_mixes_grad, const float* __restrict__ mhc_base, float* __restrict__ mhc_base_grad_partial, const float* __restrict__ mhc_scale, float* __restrict__ mhc_scale_grad_partial, const float* __restrict__ post_layer_mix, const float* __restrict__ post_layer_mix_grad, const float* __restrict__ pre_layer_mix_grad, int num_tokens);
extern "C" __global__ void __launch_bounds__(128, 1) mhc_pre_split_mixes_bwd_kernel_kernel(const float* __restrict__ comb_res_mix_grad, const float* __restrict__ input_mixes, float* __restrict__ input_mixes_grad, const float* __restrict__ mhc_base, float* __restrict__ mhc_base_grad_partial, const float* __restrict__ mhc_scale, float* __restrict__ mhc_scale_grad_partial, const float* __restrict__ post_layer_mix, const float* __restrict__ post_layer_mix_grad, const float* __restrict__ pre_layer_mix_grad, int num_tokens) {
  float mhc_scale_grad_frag[3];
  float mhc_base_grad_frag[24];
  float pre_layer_mix_grad_frag[24];
  float post_layer_mix_grad_frag[4];
  float comb_res_mix_grad_frag[16];
  float post_layer_mix_frag[4];
  float input_mixes_frag[24];
  float input_mixes_grad_frag[24];
  float pre_layer_mix_frag[24];
  float mhc_base_grad_frag_clear[24];
  extern __shared__ __align__(1024) float workspace[];
  #pragma unroll
  for (int i = 0; i < 3; ++i) {
    mhc_scale_grad_frag[i] = 0x0p+0f/*0.000000e+00*/;
  }
  if (((int)threadIdx.x) < 32) {
    #pragma unroll
    for (int i_1 = 0; i_1 < 6; ++i_1) {
      float broadcast_var = 0x0p+0f/*0.000000e+00*/;
      *(float4*)(mhc_base_grad_frag + (i_1 * 4)) = make_float4(broadcast_var, broadcast_var, broadcast_var, broadcast_var);
    }
  }
  for (int w = 0; w < ((num_tokens + 6015) / 6016); ++w) {
    if (((int)threadIdx.x) < 32) {
      #pragma unroll
      for (int i_2 = 0; i_2 < 6; ++i_2) {
        if (i_2 < 1) {
          float broadcast_var_1 = 0x0p+0f/*0.000000e+00*/;
          float4 condval;
          if (((((w * 6016) + (((int)blockIdx.x) * 32)) + ((int)threadIdx.x)) < num_tokens)) {
            condval = *(float4*)(pre_layer_mix_grad + ((((((int64_t)w) * (int64_t)24064) + (((int64_t)((int)blockIdx.x)) * (int64_t)128)) + (((int64_t)((int)threadIdx.x)) * (int64_t)4)) + (((int64_t)i_2) * (int64_t)4)));
          } else {
            condval = make_float4(broadcast_var_1, broadcast_var_1, broadcast_var_1, broadcast_var_1);
          }
          *(float4*)(pre_layer_mix_grad_frag + 0) = condval;
        }
      }
      float broadcast_var_2 = 0x0p+0f/*0.000000e+00*/;
      float4 condval_1;
      if (((((w * 6016) + (((int)blockIdx.x) * 32)) + ((int)threadIdx.x)) < num_tokens)) {
        condval_1 = *(float4*)(post_layer_mix_grad + (((((int64_t)w) * (int64_t)24064) + (((int64_t)((int)blockIdx.x)) * (int64_t)128)) + (((int64_t)((int)threadIdx.x)) * (int64_t)4)));
      } else {
        condval_1 = make_float4(broadcast_var_2, broadcast_var_2, broadcast_var_2, broadcast_var_2);
      }
      *(float4*)(post_layer_mix_grad_frag + 0) = condval_1;
      #pragma unroll
      for (int i_3 = 0; i_3 < 2; ++i_3) {
        float broadcast_var_3 = 0x0p+0f/*0.000000e+00*/;
        ulonglong4 condval_2;
        if (((((w * 6016) + (((int)blockIdx.x) * 32)) + ((int)threadIdx.x)) < num_tokens)) {
          condval_2 = tl::load_global_256(&(*(ulonglong4*)(comb_res_mix_grad + ((((((int64_t)w) * (int64_t)96256) + (((int64_t)((int)blockIdx.x)) * (int64_t)512)) + (((int64_t)((int)threadIdx.x)) * (int64_t)16)) + (((int64_t)i_3) * (int64_t)8)))));
        } else {
          condval_2 = make_ulonglong4(*(unsigned long long*)&make_float2(broadcast_var_3, broadcast_var_3), *(unsigned long long*)&make_float2(broadcast_var_3, broadcast_var_3), *(unsigned long long*)&make_float2(broadcast_var_3, broadcast_var_3), *(unsigned long long*)&make_float2(broadcast_var_3, broadcast_var_3));
        }
        *(ulonglong4*)(comb_res_mix_grad_frag + (i_3 * 8)) = condval_2;
      }
      float broadcast_var_4 = 0x0p+0f/*0.000000e+00*/;
      float4 condval_3;
      if (((((w * 6016) + (((int)blockIdx.x) * 32)) + ((int)threadIdx.x)) < num_tokens)) {
        condval_3 = *(float4*)(post_layer_mix + (((((int64_t)w) * (int64_t)24064) + (((int64_t)((int)blockIdx.x)) * (int64_t)128)) + (((int64_t)((int)threadIdx.x)) * (int64_t)4)));
      } else {
        condval_3 = make_float4(broadcast_var_4, broadcast_var_4, broadcast_var_4, broadcast_var_4);
      }
      *(float4*)(post_layer_mix_frag + 0) = condval_3;
      #pragma unroll
      for (int i_4 = 0; i_4 < 3; ++i_4) {
        float broadcast_var_5 = 0x0p+0f/*0.000000e+00*/;
        ulonglong4 condval_4;
        if (((((w * 6016) + (((int)blockIdx.x) * 32)) + ((int)threadIdx.x)) < num_tokens)) {
          condval_4 = tl::load_global_256(&(*(ulonglong4*)(input_mixes + ((((((int64_t)w) * (int64_t)144384) + (((int64_t)((int)blockIdx.x)) * (int64_t)768)) + (((int64_t)((int)threadIdx.x)) * (int64_t)24)) + (((int64_t)i_4) * (int64_t)8)))));
        } else {
          condval_4 = make_ulonglong4(*(unsigned long long*)&make_float2(broadcast_var_5, broadcast_var_5), *(unsigned long long*)&make_float2(broadcast_var_5, broadcast_var_5), *(unsigned long long*)&make_float2(broadcast_var_5, broadcast_var_5), *(unsigned long long*)&make_float2(broadcast_var_5, broadcast_var_5));
        }
        *(ulonglong4*)(input_mixes_frag + (i_4 * 8)) = condval_4;
      }
      #pragma unroll
      for (int i_5 = 0; i_5 < 3; ++i_5) {
        for (int vec_s = 0; vec_s < 8; ++vec_s) {
          if (((i_5 * 2) + (vec_s >> 2)) < 1) {
            pre_layer_mix_frag[((i_5 * 8) + vec_s)] = (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - ((input_mixes_frag[((i_5 * 8) + vec_s)] * mhc_scale[0]) + mhc_base[((i_5 * 8) + vec_s)])))));
          }
        }
        for (int vec_s_1 = 0; vec_s_1 < 8; ++vec_s_1) {
          if (((i_5 * 2) + (vec_s_1 >> 2)) < 1) {
            input_mixes_grad_frag[((i_5 * 8) + vec_s_1)] = ((pre_layer_mix_grad_frag[((i_5 * 8) + vec_s_1)] * pre_layer_mix_frag[((i_5 * 8) + vec_s_1)]) * (0x1p+0f/*1.000000e+00*/ - pre_layer_mix_frag[((i_5 * 8) + vec_s_1)]));
          }
        }
      }
      #pragma unroll
      for (int i_6 = 0; i_6 < 4; ++i_6) {
        input_mixes_grad_frag[(i_6 + 4)] = ((post_layer_mix_grad_frag[i_6] * post_layer_mix_frag[i_6]) * (0x1p+0f/*1.000000e+00*/ - post_layer_mix_frag[i_6]));
      }
      #pragma unroll
      for (int i_7 = 0; i_7 < 16; ++i_7) {
        input_mixes_grad_frag[(i_7 + 8)] = comb_res_mix_grad_frag[i_7];
      }
      #pragma unroll
      for (int i_8 = 0; i_8 < 24; ++i_8) {
        mhc_base_grad_frag_clear[i_8] = 0x0p+0f/*0.000000e+00*/;
        mhc_base_grad_frag_clear[i_8] = (mhc_base_grad_frag_clear[i_8] + input_mixes_grad_frag[i_8]);
        mhc_base_grad_frag_clear[i_8] = tl::AllReduce<tl::SumOp, 32, 1, 0, tl::NamedBarrier<128>>::run(mhc_base_grad_frag_clear[i_8]);
        mhc_base_grad_frag[i_8] = (mhc_base_grad_frag[i_8] + mhc_base_grad_frag_clear[i_8]);
      }
      #pragma unroll
      for (int i_9 = 0; i_9 < 24; ++i_9) {
        mhc_scale_grad_frag[min(2, (i_9 >> 2))] = (mhc_scale_grad_frag[min(2, (i_9 >> 2))] + (input_mixes_grad_frag[i_9] * input_mixes_frag[i_9]));
        input_mixes_grad_frag[i_9] = (input_mixes_grad_frag[i_9] * mhc_scale[min(2, (i_9 >> 2))]);
      }
      if ((((w * 6016) + (((int)blockIdx.x) * 32)) + ((int)threadIdx.x)) < num_tokens) {
        #pragma unroll
        for (int i_10 = 0; i_10 < 3; ++i_10) {
          tl::store_global_256(&(*(ulonglong4*)(input_mixes_grad + ((((((int64_t)w) * (int64_t)144384) + (((int64_t)((int)blockIdx.x)) * (int64_t)768)) + (((int64_t)((int)threadIdx.x)) * (int64_t)24)) + (((int64_t)i_10) * (int64_t)8)))), *(ulonglong4*)(input_mixes_grad_frag + (i_10 * 8)));
        }
      }
    }
  }
  if (((((int)threadIdx.x) / 24) == 0) && (((int)threadIdx.x) < 120)) {
    mhc_base_grad_partial[((((int)blockIdx.x) * 24) + (((int)threadIdx.x) % 24))] = mhc_base_grad_frag[(((int)threadIdx.x) % 24)];
  }
  __syncthreads();
  for (int __finred_0 = 0; __finred_0 < 3; ++__finred_0) {
    mhc_scale_grad_frag[__finred_0] = tl::AllReduce<tl::SumOp, 128, 1, 0, tl::NamedBarrier<128>>::run(mhc_scale_grad_frag[__finred_0], (&(workspace[0])));
  }
  if (((((int)threadIdx.x) / 3) == 0) && (((int)threadIdx.x) < 126)) {
    mhc_scale_grad_partial[((((int)blockIdx.x) * 3) + (((int)threadIdx.x) % 3))] = mhc_scale_grad_frag[(((int)threadIdx.x) % 3)];
  }
}

