// TileKernels CUDA dump (generated by scripts/dump_cuda_sources.py)
// Source Python: tile_kernels/mhc/pre_big_fuse_kernel.py
// JIT factory: _mhc_pre_big_fuse
// prim_func: mhc_pre_big_fuse
// Compile args: {"args": [7168, 1e-06, 1e-06, 1e-06, 1.0, 10], "kwargs": {}}
// Public API: tile_kernels.modeling.mhc.ops.pre_big_fuse.mhc_pre_big_fuse
#include <math_constants.h>
#include <tl_templates/cuda/gemm.h>
#include <tl_templates/cuda/copy.h>
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#include <tl_templates/cuda/debug.h>
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void mhc_pre_big_fuse_kernel(float* __restrict__ comb_mix, const float* __restrict__ gemm_out_mul, const float* __restrict__ gemm_out_sqrsum, bfloat16_t* __restrict__ layer_input, const float* __restrict__ mhc_base, const float* __restrict__ mhc_scale, float* __restrict__ post_mix, const bfloat16_t* __restrict__ residual, int num_tokens);
extern "C" __global__ void __launch_bounds__(96, 1) mhc_pre_big_fuse_kernel(float* __restrict__ comb_mix, const float* __restrict__ gemm_out_mul, const float* __restrict__ gemm_out_sqrsum, bfloat16_t* __restrict__ layer_input, const float* __restrict__ mhc_base, const float* __restrict__ mhc_scale, float* __restrict__ post_mix, const bfloat16_t* __restrict__ residual, int num_tokens) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  float mixes[1];
  float rms[1];
  float cm[1];
  float row_max[1];
  float row_sum[1];
  float col_sum[1];
  float xl[32];
  float ol[8];
  bfloat16_t xs_local_cast[8];
  bfloat16_t layer_input_local_cast_1[8];
  bfloat16_t xs_local_cast_2[8];
  bfloat16_t layer_input_local_cast_3[8];
  bfloat16_t xs_local_cast_4[8];
  bfloat16_t layer_input_local_cast_5[8];
  if (((int)threadIdx.x) < 32) {
    if (((int)threadIdx.x) < 24) {
      mixes[0] = 0x0p+0f/*0.000000e+00*/;
    }
    rms[0] = 0x0p+0f/*0.000000e+00*/;
    for (int i_split = 0; i_split < 16; ++i_split) {
      rms[0] = (rms[0] + gemm_out_sqrsum[((((int64_t)i_split) * ((int64_t)num_tokens)) + ((int64_t)((int)blockIdx.x)))]);
    }
    rms[0] = rsqrtf(((rms[0] / 0x1.cp+14f/*2.867200e+04*/) + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/));
    if (((int)threadIdx.x) < 24) {
      mixes[0] = 0x0p+0f/*0.000000e+00*/;
      for (int i_split_1 = 0; i_split_1 < 16; ++i_split_1) {
        mixes[0] = (mixes[0] + gemm_out_mul[(((((int64_t)((int)blockIdx.x)) * (int64_t)24) + ((((int64_t)i_split_1) * ((int64_t)num_tokens)) * (int64_t)24)) + ((int64_t)((int)threadIdx.x)))]);
      }
      mixes[0] = (mixes[0] * rms[0]);
      ((float*)buf_dyn_shmem)[((int)threadIdx.x)] = mixes[0];
    }
  }
  __syncthreads();
  if (((int)threadIdx.x) < 32) {
    if (((int)threadIdx.x) < 4) {
      post_mix[((((int64_t)((int)blockIdx.x)) * (int64_t)4) + ((int64_t)((int)threadIdx.x)))] = (0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - ((((float*)buf_dyn_shmem)[(((int)threadIdx.x) + 4)] * mhc_scale[1]) + mhc_base[(((int)threadIdx.x) + 4)])))));
    }
    cm[0] = ((((float*)buf_dyn_shmem)[((((int)threadIdx.x) & 15) + 8)] * mhc_scale[2]) + mhc_base[((((int)threadIdx.x) & 15) + 8)]);
    row_max[0] = -CUDART_INF_F;
    row_max[0] = max(row_max[0], cm[0]);
    row_max[0] = tl::AllReduce<tl::MaxOp, 4, 1, 0, tl::NamedBarrier<32>>::run(row_max[0]);
    cm[0] = expf((cm[0] - row_max[0]));
    row_sum[0] = 0x0p+0f/*0.000000e+00*/;
    row_sum[0] = (row_sum[0] + cm[0]);
    row_sum[0] = tl::AllReduce<tl::SumOp, 4, 1, 0, tl::NamedBarrier<32>>::run(row_sum[0]);
    cm[0] = ((cm[0] / row_sum[0]) + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/);
    col_sum[0] = 0x0p+0f/*0.000000e+00*/;
    col_sum[0] = (col_sum[0] + cm[0]);
    col_sum[0] = tl::AllReduce<tl::SumOp, 16, 4, 0, tl::NamedBarrier<32>>::run(col_sum[0]);
    cm[0] = (cm[0] / (col_sum[0] + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/));
    for (int __1 = 0; __1 < 9; ++__1) {
      row_sum[0] = 0x0p+0f/*0.000000e+00*/;
      row_sum[0] = (row_sum[0] + cm[0]);
      row_sum[0] = tl::AllReduce<tl::SumOp, 4, 1, 0, tl::NamedBarrier<32>>::run(row_sum[0]);
      cm[0] = (cm[0] / (row_sum[0] + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/));
      col_sum[0] = 0x0p+0f/*0.000000e+00*/;
      col_sum[0] = (col_sum[0] + cm[0]);
      col_sum[0] = tl::AllReduce<tl::SumOp, 16, 4, 0, tl::NamedBarrier<32>>::run(col_sum[0]);
      cm[0] = (cm[0] / (col_sum[0] + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/));
    }
    if ((((int)threadIdx.x) >> 4) == 0) {
      comb_mix[((((int64_t)((int)blockIdx.x)) * (int64_t)16) + (((int64_t)((int)threadIdx.x)) & (int64_t)15))] = cm[0];
    }
  } else {
    if (((int)threadIdx.x) < 36) {
      ((float*)buf_dyn_shmem)[(((int)threadIdx.x) + 2040)] = ((0x1p+0f/*1.000000e+00*/ / (0x1p+0f/*1.000000e+00*/ + expf((0x0p+0f/*0.000000e+00*/ - ((((float*)buf_dyn_shmem)[(((int)threadIdx.x) - 32)] * mhc_scale[0]) + mhc_base[(((int)threadIdx.x) - 32)]))))) + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/);
    }
    tl::__sync_thread_partial<3, 64>();
    #pragma unroll
    for (int i = 0; i < 4; ++i) {
      tl::cp_async_gs<16>((&(((bfloat16_t*)buf_dyn_shmem)[(((i * 512) + (((int)threadIdx.x) * 8)) - 208)])), (&(residual[((((((int64_t)((int)blockIdx.x)) * (int64_t)28672) + (((int64_t)i) * (int64_t)7168)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8)) - (int64_t)256)])));
    }
    tl::cp_async_commit();
    #pragma unroll
    for (int i_1 = 0; i_1 < 4; ++i_1) {
      tl::cp_async_gs<16>((&(((bfloat16_t*)buf_dyn_shmem)[(((i_1 * 512) + (((int)threadIdx.x) * 8)) + 1840)])), (&(residual[((((((int64_t)((int)blockIdx.x)) * (int64_t)28672) + (((int64_t)i_1) * (int64_t)7168)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8)) + (int64_t)256)])));
    }
    tl::cp_async_commit();
    for (int i0_h = 0; i0_h < 12; ++i0_h) {
      tl::cp_async_wait<1>();
      tl::__sync_thread_partial<3, 64>();
      #pragma unroll
      for (int i_2 = 0; i_2 < 4; ++i_2) {
        *(uint4*)(xs_local_cast + 0) = *(uint4*)(((bfloat16_t*)buf_dyn_shmem) + (((((i0_h & 1) * 2048) + (i_2 * 512)) + (((int)threadIdx.x) * 8)) - 208));
        for (int vec = 0; vec < 2; ++vec) {
          float4 __2;
          uint2 v_ = *(uint2*)(xs_local_cast + (vec * 4));
          ((float2*)(&__2))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[0]);
          ((float2*)(&__2))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[1]);
          *(float4*)(xl + ((i_2 * 8) + (vec * 4))) = __2;
        }
      }
      tl::__sync_thread_partial<3, 64>();
      #pragma unroll
      for (int i_3 = 0; i_3 < 4; ++i_3) {
        tl::cp_async_gs<16>((&(((bfloat16_t*)buf_dyn_shmem)[(((((i0_h & 1) * 2048) + (i_3 * 512)) + (((int)threadIdx.x) * 8)) - 208)])), (&(residual[(((((((int64_t)((int)blockIdx.x)) * (int64_t)28672) + (((int64_t)i_3) * (int64_t)7168)) + (((int64_t)i0_h) * (int64_t)512)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8)) + (int64_t)768)])));
      }
      tl::cp_async_commit();
      #pragma unroll
      for (int i_4 = 0; i_4 < 2; ++i_4) {
        float broadcast_var = 0x0p+0f/*0.000000e+00*/;
        *(float4*)(ol + (i_4 * 4)) = make_float4(broadcast_var, broadcast_var, broadcast_var, broadcast_var);
      }
      tl::__sync_thread_partial<3, 64>();
      for (int i_mhc = 0; i_mhc < 4; ++i_mhc) {
        float pre = ((float*)buf_dyn_shmem)[(i_mhc + 2072)];
        #pragma unroll
        for (int i_5 = 0; i_5 < 8; ++i_5) {
          ol[i_5] = (ol[i_5] + (pre * xl[((i_mhc * 8) + i_5)]));
        }
      }
      for (int i_6 = 0; i_6 < 2; ++i_6) {
        uint2 __3;
        float4 v__1 = *(float4*)(ol + (i_6 * 4));
        (reinterpret_cast<__nv_bfloat162*>(&__3))[0] = __float22bfloat162_rn(((float2*)(&v__1))[0]);
        (reinterpret_cast<__nv_bfloat162*>(&__3))[1] = __float22bfloat162_rn(((float2*)(&v__1))[1]);
        *(uint2*)(layer_input_local_cast_1 + (i_6 * 4)) = __3;
      }
      *(uint4*)(layer_input + ((((((int64_t)((int)blockIdx.x)) * (int64_t)7168) + (((int64_t)i0_h) * (int64_t)512)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8)) - (int64_t)256)) = *(uint4*)(layer_input_local_cast_1 + 0);
    }
    tl::cp_async_wait<1>();
    tl::__sync_thread_partial<3, 64>();
    #pragma unroll
    for (int i_7 = 0; i_7 < 4; ++i_7) {
      *(uint4*)(xs_local_cast_2 + 0) = *(uint4*)(((bfloat16_t*)buf_dyn_shmem) + (((i_7 * 512) + (((int)threadIdx.x) * 8)) - 208));
      for (int vec_1 = 0; vec_1 < 2; ++vec_1) {
        float4 __4;
        uint2 v__2 = *(uint2*)(xs_local_cast_2 + (vec_1 * 4));
        ((float2*)(&__4))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__2))[0]);
        ((float2*)(&__4))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__2))[1]);
        *(float4*)(xl + ((i_7 * 8) + (vec_1 * 4))) = __4;
      }
    }
    #pragma unroll
    for (int i_8 = 0; i_8 < 2; ++i_8) {
      float broadcast_var_1 = 0x0p+0f/*0.000000e+00*/;
      *(float4*)(ol + (i_8 * 4)) = make_float4(broadcast_var_1, broadcast_var_1, broadcast_var_1, broadcast_var_1);
    }
    for (int i_mhc_1 = 0; i_mhc_1 < 4; ++i_mhc_1) {
      float pre_1 = ((float*)buf_dyn_shmem)[(i_mhc_1 + 2072)];
      #pragma unroll
      for (int i_9 = 0; i_9 < 8; ++i_9) {
        ol[i_9] = (ol[i_9] + (pre_1 * xl[((i_mhc_1 * 8) + i_9)]));
      }
    }
    for (int i_10 = 0; i_10 < 2; ++i_10) {
      uint2 __5;
      float4 v__3 = *(float4*)(ol + (i_10 * 4));
      (reinterpret_cast<__nv_bfloat162*>(&__5))[0] = __float22bfloat162_rn(((float2*)(&v__3))[0]);
      (reinterpret_cast<__nv_bfloat162*>(&__5))[1] = __float22bfloat162_rn(((float2*)(&v__3))[1]);
      *(uint2*)(layer_input_local_cast_3 + (i_10 * 4)) = __5;
    }
    *(uint4*)(layer_input + (((((int64_t)((int)blockIdx.x)) * (int64_t)7168) + (((int64_t)((int)threadIdx.x)) * (int64_t)8)) + (int64_t)5888)) = *(uint4*)(layer_input_local_cast_3 + 0);
    tl::cp_async_wait<0>();
    tl::__sync_thread_partial<3, 64>();
    #pragma unroll
    for (int i_11 = 0; i_11 < 4; ++i_11) {
      *(uint4*)(xs_local_cast_4 + 0) = *(uint4*)(((bfloat16_t*)buf_dyn_shmem) + (((i_11 * 512) + (((int)threadIdx.x) * 8)) + 1840));
      for (int vec_2 = 0; vec_2 < 2; ++vec_2) {
        float4 __6;
        uint2 v__4 = *(uint2*)(xs_local_cast_4 + (vec_2 * 4));
        ((float2*)(&__6))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__4))[0]);
        ((float2*)(&__6))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__4))[1]);
        *(float4*)(xl + ((i_11 * 8) + (vec_2 * 4))) = __6;
      }
    }
    #pragma unroll
    for (int i_12 = 0; i_12 < 2; ++i_12) {
      float broadcast_var_2 = 0x0p+0f/*0.000000e+00*/;
      *(float4*)(ol + (i_12 * 4)) = make_float4(broadcast_var_2, broadcast_var_2, broadcast_var_2, broadcast_var_2);
    }
    for (int i_mhc_2 = 0; i_mhc_2 < 4; ++i_mhc_2) {
      float pre_2 = ((float*)buf_dyn_shmem)[(i_mhc_2 + 2072)];
      #pragma unroll
      for (int i_13 = 0; i_13 < 8; ++i_13) {
        ol[i_13] = (ol[i_13] + (pre_2 * xl[((i_mhc_2 * 8) + i_13)]));
      }
    }
    for (int i_14 = 0; i_14 < 2; ++i_14) {
      uint2 __7;
      float4 v__5 = *(float4*)(ol + (i_14 * 4));
      (reinterpret_cast<__nv_bfloat162*>(&__7))[0] = __float22bfloat162_rn(((float2*)(&v__5))[0]);
      (reinterpret_cast<__nv_bfloat162*>(&__7))[1] = __float22bfloat162_rn(((float2*)(&v__5))[1]);
      *(uint2*)(layer_input_local_cast_5 + (i_14 * 4)) = __7;
    }
    *(uint4*)(layer_input + (((((int64_t)((int)blockIdx.x)) * (int64_t)7168) + (((int64_t)((int)threadIdx.x)) * (int64_t)8)) + (int64_t)6400)) = *(uint4*)(layer_input_local_cast_5 + 0);
  }
}

