// TileKernels CUDA dump (generated by scripts/dump_cuda_sources.py)
// Source Python: tile_kernels/mhc/pre_apply_mix_kernel.py
// JIT factory: _mhc_pre_apply_mix_bwd
// prim_func: _mhc_pre_apply_mix_bwd_kernel
// Compile args: {"args": [4, 7168], "kwargs": {}}
// Public API: tile_kernels.modeling.mhc.ops.pre_apply_mix.mhc_pre_apply_mix
#include <tl_templates/cuda/gemm.h>
#include <tl_templates/cuda/copy.h>
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#include <tl_templates/cuda/debug.h>
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void _mhc_pre_apply_mix_bwd_kernel_kernel(const float* __restrict__ mix, float* __restrict__ mix_grad, const bfloat16_t* __restrict__ o_grad, const bfloat16_t* __restrict__ x, bfloat16_t* __restrict__ x_grad, int n);
extern "C" __global__ void __launch_bounds__(128, 1) _mhc_pre_apply_mix_bwd_kernel_kernel(const float* __restrict__ mix, float* __restrict__ mix_grad, const bfloat16_t* __restrict__ o_grad, const bfloat16_t* __restrict__ x, bfloat16_t* __restrict__ x_grad, int n) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  float mixl[4];
  float mgl[4];
  float ogl[8];
  float xl[32];
  float xgl[32];
  bfloat16_t ogs_local_cast[8];
  bfloat16_t xs_local_cast_1[8];
  bfloat16_t xgs_local_cast_2[8];
  bfloat16_t x_grad_local_cast_3[8];
  bfloat16_t ogs_local_cast_4[8];
  bfloat16_t xs_local_cast_5[8];
  bfloat16_t xgs_local_cast_6[8];
  bfloat16_t x_grad_local_cast_7[8];
  bfloat16_t ogs_local_cast_8[8];
  bfloat16_t xs_local_cast_9[8];
  bfloat16_t xgs_local_cast_10[8];
  bfloat16_t x_grad_local_cast_11[8];
  *(float4*)(mixl + 0) = *(float4*)(mix + (((int64_t)((int)blockIdx.x)) * (int64_t)4));
  float broadcast_var = 0x0p+0f/*0.000000e+00*/;
  *(float4*)(mgl + 0) = make_float4(broadcast_var, broadcast_var, broadcast_var, broadcast_var);
  tl::cp_async_gs<16>((&(((bfloat16_t*)buf_dyn_shmem)[(((int)threadIdx.x) * 8)])), (&(o_grad[((((int64_t)((int)blockIdx.x)) * (int64_t)7168) + (((int64_t)((int)threadIdx.x)) * (int64_t)8))])));
  tl::cp_async_commit();
  #pragma unroll
  for (int i = 0; i < 4; ++i) {
    tl::cp_async_gs<16>((&(((bfloat16_t*)buf_dyn_shmem)[(((i * 1024) + (((int)threadIdx.x) * 8)) + 2048)])), (&(x[(((((int64_t)((int)blockIdx.x)) * (int64_t)28672) + (((int64_t)i) * (int64_t)7168)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8))])));
  }
  tl::cp_async_commit();
  #pragma unroll
  for (int i_1 = 0; i_1 < 4; ++i_1) {
    tl::cp_async_gs<16>((&(((bfloat16_t*)buf_dyn_shmem)[(((i_1 * 1024) + (((int)threadIdx.x) * 8)) + 10240)])), (&(x_grad[(((((int64_t)((int)blockIdx.x)) * (int64_t)28672) + (((int64_t)i_1) * (int64_t)7168)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8))])));
  }
  tl::cp_async_commit();
  tl::cp_async_gs<16>((&(((bfloat16_t*)buf_dyn_shmem)[((((int)threadIdx.x) * 8) + 1024)])), (&(o_grad[(((((int64_t)((int)blockIdx.x)) * (int64_t)7168) + (((int64_t)((int)threadIdx.x)) * (int64_t)8)) + (int64_t)1024)])));
  tl::cp_async_commit();
  #pragma unroll
  for (int i_2 = 0; i_2 < 4; ++i_2) {
    tl::cp_async_gs<16>((&(((bfloat16_t*)buf_dyn_shmem)[(((i_2 * 1024) + (((int)threadIdx.x) * 8)) + 6144)])), (&(x[((((((int64_t)((int)blockIdx.x)) * (int64_t)28672) + (((int64_t)i_2) * (int64_t)7168)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8)) + (int64_t)1024)])));
  }
  tl::cp_async_commit();
  #pragma unroll
  for (int i_3 = 0; i_3 < 4; ++i_3) {
    tl::cp_async_gs<16>((&(((bfloat16_t*)buf_dyn_shmem)[(((i_3 * 1024) + (((int)threadIdx.x) * 8)) + 14336)])), (&(x_grad[((((((int64_t)((int)blockIdx.x)) * (int64_t)28672) + (((int64_t)i_3) * (int64_t)7168)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8)) + (int64_t)1024)])));
  }
  tl::cp_async_commit();
  for (int i0_h = 0; i0_h < 5; ++i0_h) {
    tl::cp_async_wait<1>();
    __syncthreads();
    *(uint4*)(ogs_local_cast + 0) = *(uint4*)(((bfloat16_t*)buf_dyn_shmem) + (((i0_h & 1) * 1024) + (((int)threadIdx.x) * 8)));
    for (int i_4 = 0; i_4 < 2; ++i_4) {
      float4 __1;
      uint2 v_ = *(uint2*)(ogs_local_cast + (i_4 * 4));
      ((float2*)(&__1))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[0]);
      ((float2*)(&__1))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[1]);
      *(float4*)(ogl + (i_4 * 4)) = __1;
    }
    __syncthreads();
    tl::cp_async_gs<16>((&(((bfloat16_t*)buf_dyn_shmem)[(((i0_h & 1) * 1024) + (((int)threadIdx.x) * 8))])), (&(o_grad[((((((int64_t)((int)blockIdx.x)) * (int64_t)7168) + (((int64_t)i0_h) * (int64_t)1024)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8)) + (int64_t)2048)])));
    tl::cp_async_commit();
    tl::cp_async_wait<1>();
    __syncthreads();
    #pragma unroll
    for (int i_5 = 0; i_5 < 4; ++i_5) {
      *(uint4*)(xs_local_cast_1 + 0) = *(uint4*)(((bfloat16_t*)buf_dyn_shmem) + (((((i0_h & 1) * 4096) + (i_5 * 1024)) + (((int)threadIdx.x) * 8)) + 2048));
      for (int vec = 0; vec < 2; ++vec) {
        float4 __2;
        uint2 v__1 = *(uint2*)(xs_local_cast_1 + (vec * 4));
        ((float2*)(&__2))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__1))[0]);
        ((float2*)(&__2))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__1))[1]);
        *(float4*)(xl + ((i_5 * 8) + (vec * 4))) = __2;
      }
    }
    __syncthreads();
    #pragma unroll
    for (int i_6 = 0; i_6 < 4; ++i_6) {
      tl::cp_async_gs<16>((&(((bfloat16_t*)buf_dyn_shmem)[(((((i0_h & 1) * 4096) + (i_6 * 1024)) + (((int)threadIdx.x) * 8)) + 2048)])), (&(x[(((((((int64_t)((int)blockIdx.x)) * (int64_t)28672) + (((int64_t)i_6) * (int64_t)7168)) + (((int64_t)i0_h) * (int64_t)1024)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8)) + (int64_t)2048)])));
    }
    tl::cp_async_commit();
    tl::cp_async_wait<1>();
    __syncthreads();
    #pragma unroll
    for (int i_7 = 0; i_7 < 4; ++i_7) {
      *(uint4*)(xgs_local_cast_2 + 0) = *(uint4*)(((bfloat16_t*)buf_dyn_shmem) + (((((i0_h & 1) * 4096) + (i_7 * 1024)) + (((int)threadIdx.x) * 8)) + 10240));
      for (int vec_1 = 0; vec_1 < 2; ++vec_1) {
        float4 __3;
        uint2 v__2 = *(uint2*)(xgs_local_cast_2 + (vec_1 * 4));
        ((float2*)(&__3))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__2))[0]);
        ((float2*)(&__3))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__2))[1]);
        *(float4*)(xgl + ((i_7 * 8) + (vec_1 * 4))) = __3;
      }
    }
    __syncthreads();
    #pragma unroll
    for (int i_8 = 0; i_8 < 4; ++i_8) {
      tl::cp_async_gs<16>((&(((bfloat16_t*)buf_dyn_shmem)[(((((i0_h & 1) * 4096) + (i_8 * 1024)) + (((int)threadIdx.x) * 8)) + 10240)])), (&(x_grad[(((((((int64_t)((int)blockIdx.x)) * (int64_t)28672) + (((int64_t)i_8) * (int64_t)7168)) + (((int64_t)i0_h) * (int64_t)1024)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8)) + (int64_t)2048)])));
    }
    tl::cp_async_commit();
    #pragma unroll
    for (int i_9 = 0; i_9 < 32; ++i_9) {
      mgl[(i_9 >> 3)] = (mgl[(i_9 >> 3)] + (ogl[(i_9 & 7)] * xl[i_9]));
      xgl[i_9] = (xgl[i_9] + (mixl[(i_9 >> 3)] * ogl[(i_9 & 7)]));
    }
    #pragma unroll
    for (int i_10 = 0; i_10 < 4; ++i_10) {
      for (int vec_2 = 0; vec_2 < 2; ++vec_2) {
        uint2 __4;
        float4 v__3 = *(float4*)(xgl + ((i_10 * 8) + (vec_2 * 4)));
        (reinterpret_cast<__nv_bfloat162*>(&__4))[0] = __float22bfloat162_rn(((float2*)(&v__3))[0]);
        (reinterpret_cast<__nv_bfloat162*>(&__4))[1] = __float22bfloat162_rn(((float2*)(&v__3))[1]);
        *(uint2*)(x_grad_local_cast_3 + (vec_2 * 4)) = __4;
      }
      *(uint4*)(x_grad + ((((((int64_t)((int)blockIdx.x)) * (int64_t)28672) + (((int64_t)i_10) * (int64_t)7168)) + (((int64_t)i0_h) * (int64_t)1024)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8))) = *(uint4*)(x_grad_local_cast_3 + 0);
    }
  }
  tl::cp_async_wait<1>();
  __syncthreads();
  *(uint4*)(ogs_local_cast_4 + 0) = *(uint4*)(((bfloat16_t*)buf_dyn_shmem) + ((((int)threadIdx.x) * 8) + 1024));
  for (int i_11 = 0; i_11 < 2; ++i_11) {
    float4 __5;
    uint2 v__4 = *(uint2*)(ogs_local_cast_4 + (i_11 * 4));
    ((float2*)(&__5))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__4))[0]);
    ((float2*)(&__5))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__4))[1]);
    *(float4*)(ogl + (i_11 * 4)) = __5;
  }
  #pragma unroll
  for (int i_12 = 0; i_12 < 4; ++i_12) {
    *(uint4*)(xs_local_cast_5 + 0) = *(uint4*)(((bfloat16_t*)buf_dyn_shmem) + (((i_12 * 1024) + (((int)threadIdx.x) * 8)) + 6144));
    for (int vec_3 = 0; vec_3 < 2; ++vec_3) {
      float4 __6;
      uint2 v__5 = *(uint2*)(xs_local_cast_5 + (vec_3 * 4));
      ((float2*)(&__6))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__5))[0]);
      ((float2*)(&__6))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__5))[1]);
      *(float4*)(xl + ((i_12 * 8) + (vec_3 * 4))) = __6;
    }
  }
  #pragma unroll
  for (int i_13 = 0; i_13 < 4; ++i_13) {
    *(uint4*)(xgs_local_cast_6 + 0) = *(uint4*)(((bfloat16_t*)buf_dyn_shmem) + (((i_13 * 1024) + (((int)threadIdx.x) * 8)) + 14336));
    for (int vec_4 = 0; vec_4 < 2; ++vec_4) {
      float4 __7;
      uint2 v__6 = *(uint2*)(xgs_local_cast_6 + (vec_4 * 4));
      ((float2*)(&__7))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__6))[0]);
      ((float2*)(&__7))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__6))[1]);
      *(float4*)(xgl + ((i_13 * 8) + (vec_4 * 4))) = __7;
    }
  }
  #pragma unroll
  for (int i_14 = 0; i_14 < 32; ++i_14) {
    mgl[(i_14 >> 3)] = (mgl[(i_14 >> 3)] + (ogl[(i_14 & 7)] * xl[i_14]));
    xgl[i_14] = (xgl[i_14] + (mixl[(i_14 >> 3)] * ogl[(i_14 & 7)]));
  }
  #pragma unroll
  for (int i_15 = 0; i_15 < 4; ++i_15) {
    for (int vec_5 = 0; vec_5 < 2; ++vec_5) {
      uint2 __8;
      float4 v__7 = *(float4*)(xgl + ((i_15 * 8) + (vec_5 * 4)));
      (reinterpret_cast<__nv_bfloat162*>(&__8))[0] = __float22bfloat162_rn(((float2*)(&v__7))[0]);
      (reinterpret_cast<__nv_bfloat162*>(&__8))[1] = __float22bfloat162_rn(((float2*)(&v__7))[1]);
      *(uint2*)(x_grad_local_cast_7 + (vec_5 * 4)) = __8;
    }
    *(uint4*)(x_grad + ((((((int64_t)((int)blockIdx.x)) * (int64_t)28672) + (((int64_t)i_15) * (int64_t)7168)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8)) + (int64_t)5120)) = *(uint4*)(x_grad_local_cast_7 + 0);
  }
  tl::cp_async_wait<0>();
  __syncthreads();
  *(uint4*)(ogs_local_cast_8 + 0) = *(uint4*)(((bfloat16_t*)buf_dyn_shmem) + (((int)threadIdx.x) * 8));
  for (int i_16 = 0; i_16 < 2; ++i_16) {
    float4 __9;
    uint2 v__8 = *(uint2*)(ogs_local_cast_8 + (i_16 * 4));
    ((float2*)(&__9))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__8))[0]);
    ((float2*)(&__9))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__8))[1]);
    *(float4*)(ogl + (i_16 * 4)) = __9;
  }
  #pragma unroll
  for (int i_17 = 0; i_17 < 4; ++i_17) {
    *(uint4*)(xs_local_cast_9 + 0) = *(uint4*)(((bfloat16_t*)buf_dyn_shmem) + (((i_17 * 1024) + (((int)threadIdx.x) * 8)) + 2048));
    for (int vec_6 = 0; vec_6 < 2; ++vec_6) {
      float4 __10;
      uint2 v__9 = *(uint2*)(xs_local_cast_9 + (vec_6 * 4));
      ((float2*)(&__10))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__9))[0]);
      ((float2*)(&__10))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__9))[1]);
      *(float4*)(xl + ((i_17 * 8) + (vec_6 * 4))) = __10;
    }
  }
  #pragma unroll
  for (int i_18 = 0; i_18 < 4; ++i_18) {
    *(uint4*)(xgs_local_cast_10 + 0) = *(uint4*)(((bfloat16_t*)buf_dyn_shmem) + (((i_18 * 1024) + (((int)threadIdx.x) * 8)) + 10240));
    for (int vec_7 = 0; vec_7 < 2; ++vec_7) {
      float4 __11;
      uint2 v__10 = *(uint2*)(xgs_local_cast_10 + (vec_7 * 4));
      ((float2*)(&__11))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__10))[0]);
      ((float2*)(&__11))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__10))[1]);
      *(float4*)(xgl + ((i_18 * 8) + (vec_7 * 4))) = __11;
    }
  }
  #pragma unroll
  for (int i_19 = 0; i_19 < 32; ++i_19) {
    mgl[(i_19 >> 3)] = (mgl[(i_19 >> 3)] + (ogl[(i_19 & 7)] * xl[i_19]));
    xgl[i_19] = (xgl[i_19] + (mixl[(i_19 >> 3)] * ogl[(i_19 & 7)]));
  }
  #pragma unroll
  for (int i_20 = 0; i_20 < 4; ++i_20) {
    for (int vec_8 = 0; vec_8 < 2; ++vec_8) {
      uint2 __12;
      float4 v__11 = *(float4*)(xgl + ((i_20 * 8) + (vec_8 * 4)));
      (reinterpret_cast<__nv_bfloat162*>(&__12))[0] = __float22bfloat162_rn(((float2*)(&v__11))[0]);
      (reinterpret_cast<__nv_bfloat162*>(&__12))[1] = __float22bfloat162_rn(((float2*)(&v__11))[1]);
      *(uint2*)(x_grad_local_cast_11 + (vec_8 * 4)) = __12;
    }
    *(uint4*)(x_grad + ((((((int64_t)((int)blockIdx.x)) * (int64_t)28672) + (((int64_t)i_20) * (int64_t)7168)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8)) + (int64_t)6144)) = *(uint4*)(x_grad_local_cast_11 + 0);
  }
  __syncthreads();
  for (int __finred_0 = 0; __finred_0 < 4; ++__finred_0) {
    mgl[__finred_0] = tl::AllReduce<tl::SumOp, 128, 1, 0, tl::NamedBarrier<128>>::run(mgl[__finred_0], (&(((float*)buf_dyn_shmem)[0])));
  }
  if ((((int)threadIdx.x) >> 2) == 0) {
    mix_grad[((((int64_t)((int)blockIdx.x)) * (int64_t)4) + (((int64_t)((int)threadIdx.x)) & (int64_t)3))] = mgl[(((int)threadIdx.x) & 3)];
  }
}

