// TileKernels CUDA dump (generated by scripts/dump_cuda_sources.py)
// Source Python: tile_kernels/mhc/pre_apply_mix_kernel.py
// JIT factory: _mhc_pre_apply_mix_fwd
// prim_func: _mhc_pre_apply_mix_fwd_kernel
// Compile args: {"args": [4, 7168], "kwargs": {}}
// Public API: tile_kernels.modeling.mhc.ops.pre_apply_mix.mhc_pre_apply_mix
#include <tl_templates/cuda/gemm.h>
#include <tl_templates/cuda/copy.h>
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#include <tl_templates/cuda/debug.h>
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void _mhc_pre_apply_mix_fwd_kernel_kernel(const float* __restrict__ mix, bfloat16_t* __restrict__ o, const bfloat16_t* __restrict__ x, int n);
extern "C" __global__ void __launch_bounds__(128, 1) _mhc_pre_apply_mix_fwd_kernel_kernel(const float* __restrict__ mix, bfloat16_t* __restrict__ o, const bfloat16_t* __restrict__ x, int n) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  float mixl[4];
  float xl[32];
  float ol[8];
  bfloat16_t xs_local_cast[4];
  bfloat16_t os_local_cast_1[4];
  bfloat16_t xs_local_cast_2[4];
  bfloat16_t os_local_cast_3[4];
  bfloat16_t xs_local_cast_4[4];
  bfloat16_t os_local_cast_5[4];
  *(float4*)(mixl + 0) = *(float4*)(mix + (((int64_t)((int)blockIdx.x)) * (int64_t)4));
  #pragma unroll
  for (int i = 0; i < 4; ++i) {
    tl::cp_async_gs<16>((&(((bfloat16_t*)buf_dyn_shmem)[((i * 1024) + (((int)threadIdx.x) * 8))])), (&(x[(((((int64_t)((int)blockIdx.x)) * (int64_t)28672) + (((int64_t)i) * (int64_t)7168)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8))])));
  }
  tl::cp_async_commit();
  #pragma unroll
  for (int i_1 = 0; i_1 < 4; ++i_1) {
    tl::cp_async_gs<16>((&(((bfloat16_t*)buf_dyn_shmem)[(((i_1 * 1024) + (((int)threadIdx.x) * 8)) + 4096)])), (&(x[((((((int64_t)((int)blockIdx.x)) * (int64_t)28672) + (((int64_t)i_1) * (int64_t)7168)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8)) + (int64_t)1024)])));
  }
  tl::cp_async_commit();
  for (int i0_h = 0; i0_h < 5; ++i0_h) {
    tl::cp_async_wait<1>();
    __syncthreads();
    #pragma unroll
    for (int i_2 = 0; i_2 < 8; ++i_2) {
      *(uint2*)(xs_local_cast + 0) = *(uint2*)(((bfloat16_t*)buf_dyn_shmem) + ((((i0_h & 1) * 4096) + (i_2 * 512)) + (((int)threadIdx.x) * 4)));
      float4 __1;
      uint2 v_ = *(uint2*)(xs_local_cast + 0);
      ((float2*)(&__1))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[0]);
      ((float2*)(&__1))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v_))[1]);
      *(float4*)(xl + (i_2 * 4)) = __1;
    }
    __syncthreads();
    #pragma unroll
    for (int i_3 = 0; i_3 < 4; ++i_3) {
      tl::cp_async_gs<16>((&(((bfloat16_t*)buf_dyn_shmem)[((((i0_h & 1) * 4096) + (i_3 * 1024)) + (((int)threadIdx.x) * 8))])), (&(x[(((((((int64_t)((int)blockIdx.x)) * (int64_t)28672) + (((int64_t)i_3) * (int64_t)7168)) + (((int64_t)i0_h) * (int64_t)1024)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8)) + (int64_t)2048)])));
    }
    tl::cp_async_commit();
    #pragma unroll
    for (int i_4 = 0; i_4 < 2; ++i_4) {
      float broadcast_var = 0x0p+0f/*0.000000e+00*/;
      *(float4*)(ol + (i_4 * 4)) = make_float4(broadcast_var, broadcast_var, broadcast_var, broadcast_var);
    }
    for (int i_mhc = 0; i_mhc < 4; ++i_mhc) {
      #pragma unroll
      for (int i_5 = 0; i_5 < 8; ++i_5) {
        ol[i_5] = (ol[i_5] + (mixl[i_mhc] * xl[((i_mhc * 8) + i_5)]));
      }
    }
    __syncthreads();
    #pragma unroll
    for (int i_6 = 0; i_6 < 2; ++i_6) {
      uint2 __2;
      float4 v__1 = *(float4*)(ol + (i_6 * 4));
      (reinterpret_cast<__nv_bfloat162*>(&__2))[0] = __float22bfloat162_rn(((float2*)(&v__1))[0]);
      (reinterpret_cast<__nv_bfloat162*>(&__2))[1] = __float22bfloat162_rn(((float2*)(&v__1))[1]);
      *(uint2*)(os_local_cast_1 + 0) = __2;
      *(uint2*)(((bfloat16_t*)buf_dyn_shmem) + (((i_6 * 512) + (((int)threadIdx.x) * 4)) + 8192)) = *(uint2*)(os_local_cast_1 + 0);
    }
    __syncthreads();
    *(uint4*)(o + (((((int64_t)((int)blockIdx.x)) * (int64_t)7168) + (((int64_t)i0_h) * (int64_t)1024)) + (((int64_t)((int)threadIdx.x)) * (int64_t)8))) = *(uint4*)(((bfloat16_t*)buf_dyn_shmem) + ((((int)threadIdx.x) * 8) + 8192));
  }
  tl::cp_async_wait<1>();
  __syncthreads();
  #pragma unroll
  for (int i_7 = 0; i_7 < 8; ++i_7) {
    *(uint2*)(xs_local_cast_2 + 0) = *(uint2*)(((bfloat16_t*)buf_dyn_shmem) + (((i_7 * 512) + (((int)threadIdx.x) * 4)) + 4096));
    float4 __3;
    uint2 v__2 = *(uint2*)(xs_local_cast_2 + 0);
    ((float2*)(&__3))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__2))[0]);
    ((float2*)(&__3))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__2))[1]);
    *(float4*)(xl + (i_7 * 4)) = __3;
  }
  #pragma unroll
  for (int i_8 = 0; i_8 < 2; ++i_8) {
    float broadcast_var_1 = 0x0p+0f/*0.000000e+00*/;
    *(float4*)(ol + (i_8 * 4)) = make_float4(broadcast_var_1, broadcast_var_1, broadcast_var_1, broadcast_var_1);
  }
  for (int i_mhc_1 = 0; i_mhc_1 < 4; ++i_mhc_1) {
    #pragma unroll
    for (int i_9 = 0; i_9 < 8; ++i_9) {
      ol[i_9] = (ol[i_9] + (mixl[i_mhc_1] * xl[((i_mhc_1 * 8) + i_9)]));
    }
  }
  #pragma unroll
  for (int i_10 = 0; i_10 < 2; ++i_10) {
    uint2 __4;
    float4 v__3 = *(float4*)(ol + (i_10 * 4));
    (reinterpret_cast<__nv_bfloat162*>(&__4))[0] = __float22bfloat162_rn(((float2*)(&v__3))[0]);
    (reinterpret_cast<__nv_bfloat162*>(&__4))[1] = __float22bfloat162_rn(((float2*)(&v__3))[1]);
    *(uint2*)(os_local_cast_3 + 0) = __4;
    *(uint2*)(((bfloat16_t*)buf_dyn_shmem) + (((i_10 * 512) + (((int)threadIdx.x) * 4)) + 8192)) = *(uint2*)(os_local_cast_3 + 0);
  }
  __syncthreads();
  *(uint4*)(o + (((((int64_t)((int)blockIdx.x)) * (int64_t)7168) + (((int64_t)((int)threadIdx.x)) * (int64_t)8)) + (int64_t)5120)) = *(uint4*)(((bfloat16_t*)buf_dyn_shmem) + ((((int)threadIdx.x) * 8) + 8192));
  tl::cp_async_wait<0>();
  __syncthreads();
  #pragma unroll
  for (int i_11 = 0; i_11 < 8; ++i_11) {
    *(uint2*)(xs_local_cast_4 + 0) = *(uint2*)(((bfloat16_t*)buf_dyn_shmem) + ((i_11 * 512) + (((int)threadIdx.x) * 4)));
    float4 __5;
    uint2 v__4 = *(uint2*)(xs_local_cast_4 + 0);
    ((float2*)(&__5))[0] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__4))[0]);
    ((float2*)(&__5))[1] = __bfloat1622float2((reinterpret_cast<__nv_bfloat162*>(&v__4))[1]);
    *(float4*)(xl + (i_11 * 4)) = __5;
  }
  #pragma unroll
  for (int i_12 = 0; i_12 < 2; ++i_12) {
    float broadcast_var_2 = 0x0p+0f/*0.000000e+00*/;
    *(float4*)(ol + (i_12 * 4)) = make_float4(broadcast_var_2, broadcast_var_2, broadcast_var_2, broadcast_var_2);
  }
  for (int i_mhc_2 = 0; i_mhc_2 < 4; ++i_mhc_2) {
    #pragma unroll
    for (int i_13 = 0; i_13 < 8; ++i_13) {
      ol[i_13] = (ol[i_13] + (mixl[i_mhc_2] * xl[((i_mhc_2 * 8) + i_13)]));
    }
  }
  #pragma unroll
  for (int i_14 = 0; i_14 < 2; ++i_14) {
    uint2 __6;
    float4 v__5 = *(float4*)(ol + (i_14 * 4));
    (reinterpret_cast<__nv_bfloat162*>(&__6))[0] = __float22bfloat162_rn(((float2*)(&v__5))[0]);
    (reinterpret_cast<__nv_bfloat162*>(&__6))[1] = __float22bfloat162_rn(((float2*)(&v__5))[1]);
    *(uint2*)(os_local_cast_5 + 0) = __6;
    *(uint2*)(((bfloat16_t*)buf_dyn_shmem) + (((i_14 * 512) + (((int)threadIdx.x) * 4)) + 8192)) = *(uint2*)(os_local_cast_5 + 0);
  }
  __syncthreads();
  *(uint4*)(o + (((((int64_t)((int)blockIdx.x)) * (int64_t)7168) + (((int64_t)((int)threadIdx.x)) * (int64_t)8)) + (int64_t)6144)) = *(uint4*)(((bfloat16_t*)buf_dyn_shmem) + ((((int)threadIdx.x) * 8) + 8192));
}

