// TileKernels CUDA dump (generated by scripts/dump_cuda_sources.py)
// Source Python: tile_kernels/mhc/sinkhorn_kernel.py
// JIT factory: _mhc_sinkhorn_fwd
// prim_func: mhc_sinkhorn_kernel
// Compile args: {"args": [4, 1, 10, 1e-06], "kwargs": {}}
// Public API: tile_kernels.modeling.mhc.ops.sinkhorn.sinkhorn_normalize
#include <math_constants.h>
#include <tl_templates/cuda/gemm.h>
#include <tl_templates/cuda/copy.h>
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#include <tl_templates/cuda/debug.h>
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void mhc_sinkhorn_kernel_kernel(const float* __restrict__ comb_res_mix, float* __restrict__ comb_res_mix_out, int num_tokens);
extern "C" __global__ void __launch_bounds__(128, 1) mhc_sinkhorn_kernel_kernel(const float* __restrict__ comb_res_mix, float* __restrict__ comb_res_mix_out, int num_tokens) {
  float comb_frag[1];
  float row_max[1];
  float row_sum[1];
  float col_sum[1];
  comb_frag[0] = comb_res_mix[((((int64_t)((int)blockIdx.x)) * (int64_t)16) + (((int64_t)((int)threadIdx.x)) & (int64_t)15))];
  row_max[0] = -CUDART_INF_F;
  row_max[0] = max(row_max[0], comb_frag[0]);
  row_max[0] = tl::AllReduce<tl::MaxOp, 4, 1, 0, tl::NamedBarrier<128>>::run(row_max[0]);
  comb_frag[0] = expf((comb_frag[0] - row_max[0]));
  row_sum[0] = 0x0p+0f/*0.000000e+00*/;
  row_sum[0] = (row_sum[0] + comb_frag[0]);
  row_sum[0] = tl::AllReduce<tl::SumOp, 4, 1, 0, tl::NamedBarrier<128>>::run(row_sum[0]);
  comb_frag[0] = ((comb_frag[0] / row_sum[0]) + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/);
  col_sum[0] = 0x0p+0f/*0.000000e+00*/;
  col_sum[0] = (col_sum[0] + comb_frag[0]);
  col_sum[0] = tl::AllReduce<tl::SumOp, 16, 4, 0, tl::NamedBarrier<128>>::run(col_sum[0]);
  comb_frag[0] = (comb_frag[0] / (col_sum[0] + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/));
  for (int __1 = 0; __1 < 9; ++__1) {
    row_sum[0] = 0x0p+0f/*0.000000e+00*/;
    row_sum[0] = (row_sum[0] + comb_frag[0]);
    row_sum[0] = tl::AllReduce<tl::SumOp, 4, 1, 0, tl::NamedBarrier<128>>::run(row_sum[0]);
    comb_frag[0] = (comb_frag[0] / (row_sum[0] + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/));
    col_sum[0] = 0x0p+0f/*0.000000e+00*/;
    col_sum[0] = (col_sum[0] + comb_frag[0]);
    col_sum[0] = tl::AllReduce<tl::SumOp, 16, 4, 0, tl::NamedBarrier<128>>::run(col_sum[0]);
    comb_frag[0] = (comb_frag[0] / (col_sum[0] + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/));
  }
  if ((((int)threadIdx.x) >> 4) == 0) {
    comb_res_mix_out[((((int64_t)((int)blockIdx.x)) * (int64_t)16) + (((int64_t)((int)threadIdx.x)) & (int64_t)15))] = comb_frag[0];
  }
}

