// TileKernels CUDA dump (generated by scripts/dump_cuda_sources.py)
// Source Python: tile_kernels/mhc/sinkhorn_kernel.py
// JIT factory: _mhc_sinkhorn_bwd
// prim_func: mhc_sinkhorn_backward_kernel
// Compile args: {"args": [4, 32, 10, 1e-06], "kwargs": {}}
// Public API: tile_kernels.modeling.mhc.ops.sinkhorn.sinkhorn_normalize
#include <math_constants.h>
#include <tl_templates/cuda/gemm.h>
#include <tl_templates/cuda/copy.h>
#include <tl_templates/cuda/reduce.h>
#include <tl_templates/cuda/ldsm.h>
#include <tl_templates/cuda/threadblock_swizzle.h>
#include <tl_templates/cuda/debug.h>
#ifdef ENABLE_BF16
#include <tl_templates/cuda/cuda_bf16_fallbacks.cuh>
#endif

extern "C" __global__ void mhc_sinkhorn_backward_kernel_kernel(float* __restrict__ grad_input, const float* __restrict__ grad_output, const float* __restrict__ x, int num_tokens);
extern "C" __global__ void __launch_bounds__(128, 1) mhc_sinkhorn_backward_kernel_kernel(float* __restrict__ grad_input, const float* __restrict__ grad_output, const float* __restrict__ x, int num_tokens) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  float grad_frag[4];
  float x_frag[4];
  float row_max[1];
  float row_sum[1];
  float col_sum[4];
  float x_inter[4];
  float temp[4];
  float col_sum2[4];
  float row_sum2[1];
  float broadcast_var = 0x0p+0f/*0.000000e+00*/;
  float4 condval;
  if ((((((int)blockIdx.x) * 32) + (((int)threadIdx.x) >> 2)) < num_tokens)) {
    condval = *(float4*)(grad_output + ((((int64_t)((int)blockIdx.x)) * (int64_t)512) + (((int64_t)((int)threadIdx.x)) * (int64_t)4)));
  } else {
    condval = make_float4(broadcast_var, broadcast_var, broadcast_var, broadcast_var);
  }
  *(float4*)(grad_frag + 0) = condval;
  float broadcast_var_1 = 0x0p+0f/*0.000000e+00*/;
  float4 condval_1;
  if ((((((int)blockIdx.x) * 32) + (((int)threadIdx.x) >> 2)) < num_tokens)) {
    condval_1 = *(float4*)(x + ((((int64_t)((int)blockIdx.x)) * (int64_t)512) + (((int64_t)((int)threadIdx.x)) * (int64_t)4)));
  } else {
    condval_1 = make_float4(broadcast_var_1, broadcast_var_1, broadcast_var_1, broadcast_var_1);
  }
  *(float4*)(x_frag + 0) = condval_1;
  row_max[0] = -CUDART_INF_F;
  #pragma unroll
  for (int rv = 0; rv < 4; ++rv) {
    row_max[0] = max(row_max[0], x_frag[rv]);
  }
  #pragma unroll
  for (int i = 0; i < 4; ++i) {
    x_frag[i] = expf((x_frag[i] - row_max[0]));
  }
  row_sum[0] = 0x0p+0f/*0.000000e+00*/;
  #pragma unroll
  for (int rv_1 = 0; rv_1 < 4; ++rv_1) {
    row_sum[0] = (row_sum[0] + x_frag[rv_1]);
  }
  #pragma unroll
  for (int i_1 = 0; i_1 < 4; ++i_1) {
    x_frag[i_1] = (x_frag[i_1] / row_sum[0]);
  }
  *(float4*)(((float*)buf_dyn_shmem) + (((int)threadIdx.x) * 4)) = *(float4*)(x_frag + 0);
  #pragma unroll
  for (int i_2 = 0; i_2 < 4; ++i_2) {
    x_frag[i_2] = (x_frag[i_2] + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/);
  }
  *(float4*)(((float*)buf_dyn_shmem) + ((((int)threadIdx.x) * 4) + 512)) = *(float4*)(x_frag + 0);
  #pragma unroll
  for (int i_3 = 0; i_3 < 4; ++i_3) {
    col_sum[i_3] = 0x0p+0f/*0.000000e+00*/;
    col_sum[i_3] = (col_sum[i_3] + x_frag[i_3]);
    col_sum[i_3] = tl::AllReduce<tl::SumOp, 4, 1, 0, tl::NamedBarrier<128>>::run(col_sum[i_3]);
  }
  ((float*)buf_dyn_shmem)[(((int)threadIdx.x) + 10368)] = col_sum[(((int)threadIdx.x) & 3)];
  #pragma unroll
  for (int i_4 = 0; i_4 < 4; ++i_4) {
    x_frag[i_4] = (x_frag[i_4] / (col_sum[i_4] + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/));
  }
  for (int step = 0; step < 9; ++step) {
    row_sum[0] = 0x0p+0f/*0.000000e+00*/;
    #pragma unroll
    for (int rv_2 = 0; rv_2 < 4; ++rv_2) {
      row_sum[0] = (row_sum[0] + x_frag[rv_2]);
    }
    ((float*)buf_dyn_shmem)[(((step * 256) + ((int)threadIdx.x)) + 10496)] = row_sum[0];
    *(float4*)(((float*)buf_dyn_shmem) + (((step * 1024) + (((int)threadIdx.x) * 4)) + 1024)) = *(float4*)(x_frag + 0);
    #pragma unroll
    for (int i_5 = 0; i_5 < 4; ++i_5) {
      x_frag[i_5] = (x_frag[i_5] / (row_sum[0] + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/));
    }
    #pragma unroll
    for (int i_6 = 0; i_6 < 4; ++i_6) {
      col_sum[i_6] = 0x0p+0f/*0.000000e+00*/;
      col_sum[i_6] = (col_sum[i_6] + x_frag[i_6]);
      col_sum[i_6] = tl::AllReduce<tl::SumOp, 4, 1, 0, tl::NamedBarrier<128>>::run(col_sum[i_6]);
    }
    ((float*)buf_dyn_shmem)[(((step * 256) + ((int)threadIdx.x)) + 10624)] = col_sum[(((int)threadIdx.x) & 3)];
    *(float4*)(((float*)buf_dyn_shmem) + (((step * 1024) + (((int)threadIdx.x) * 4)) + 1536)) = *(float4*)(x_frag + 0);
    #pragma unroll
    for (int i_7 = 0; i_7 < 4; ++i_7) {
      x_frag[i_7] = (x_frag[i_7] / (col_sum[i_7] + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/));
    }
  }
  __syncthreads();
  for (int inv_step = 0; inv_step < 19; ++inv_step) {
    *(float4*)(x_inter + 0) = *(float4*)(((float*)buf_dyn_shmem) + (((((int)threadIdx.x) * 4) + 9728) - (inv_step * 512)));
    if ((inv_step % 2) == 0) {
      *(float4*)(col_sum + 0) = *(float4*)(((float*)buf_dyn_shmem) + ((((((int)threadIdx.x) >> 2) * 4) + 12672) - (inv_step * 128)));
      #pragma unroll
      for (int i_8 = 0; i_8 < 4; ++i_8) {
        temp[i_8] = (grad_frag[i_8] * x_inter[i_8]);
      }
      #pragma unroll
      for (int i_9 = 0; i_9 < 4; ++i_9) {
        col_sum2[i_9] = 0x0p+0f/*0.000000e+00*/;
        col_sum2[i_9] = (col_sum2[i_9] + temp[i_9]);
        col_sum2[i_9] = tl::AllReduce<tl::SumOp, 4, 1, 0, tl::NamedBarrier<128>>::run(col_sum2[i_9]);
      }
      #pragma unroll
      for (int i_10 = 0; i_10 < 4; ++i_10) {
        col_sum2[i_10] = (col_sum2[i_10] / (col_sum[i_10] + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/));
      }
      #pragma unroll
      for (int i_11 = 0; i_11 < 4; ++i_11) {
        grad_frag[i_11] = ((grad_frag[i_11] - col_sum2[i_11]) / (col_sum[i_11] + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/));
      }
    } else {
      row_sum[0] = ((float*)buf_dyn_shmem)[((((int)threadIdx.x) + 12672) - (inv_step * 128))];
      #pragma unroll
      for (int i_12 = 0; i_12 < 4; ++i_12) {
        temp[i_12] = (grad_frag[i_12] * x_inter[i_12]);
      }
      row_sum2[0] = 0x0p+0f/*0.000000e+00*/;
      #pragma unroll
      for (int rv_3 = 0; rv_3 < 4; ++rv_3) {
        row_sum2[0] = (row_sum2[0] + temp[rv_3]);
      }
      row_sum2[0] = (row_sum2[0] / (row_sum[0] + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/));
      #pragma unroll
      for (int i_13 = 0; i_13 < 4; ++i_13) {
        grad_frag[i_13] = ((grad_frag[i_13] - row_sum2[0]) / (row_sum[0] + 0x1.0c6f7a0b5ed8dp-20f/*1.000000e-06*/));
      }
    }
  }
  *(float4*)(x_inter + 0) = *(float4*)(((float*)buf_dyn_shmem) + (((int)threadIdx.x) * 4));
  #pragma unroll
  for (int i_14 = 0; i_14 < 4; ++i_14) {
    temp[i_14] = (grad_frag[i_14] * x_inter[i_14]);
  }
  row_sum[0] = 0x0p+0f/*0.000000e+00*/;
  #pragma unroll
  for (int rv_4 = 0; rv_4 < 4; ++rv_4) {
    row_sum[0] = (row_sum[0] + temp[rv_4]);
  }
  #pragma unroll
  for (int i_15 = 0; i_15 < 4; ++i_15) {
    grad_frag[i_15] = ((grad_frag[i_15] - row_sum[0]) * x_inter[i_15]);
  }
  if (((((int)blockIdx.x) * 32) + (((int)threadIdx.x) >> 2)) < num_tokens) {
    *(float4*)(grad_input + ((((int64_t)((int)blockIdx.x)) * (int64_t)512) + (((int64_t)((int)threadIdx.x)) * (int64_t)4))) = *(float4*)(grad_frag + 0);
  }
}

